export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const animeSketches: GalleryArtwork[] = [
  {
    "id": 208,
    "title": "Silent Ronin",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/JIB_81_14_Preface_2_sf.JPG",
    "likes": 5830,
    "views": 82597,
    "year": 2021,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 209,
    "title": "Moon Princess",
    "artist": "Torii Kiyonaga",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124156.jpg",
    "likes": 4926,
    "views": 80757,
    "year": 2020,
    "style": "Ukiyo-e"
  },
  {
    "id": 210,
    "title": "Shadow Ninja",
    "artist": "Kitagawa Utamaro",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135624.jpg",
    "likes": 8762,
    "views": 82560,
    "year": 2023,
    "style": "Japanese Print Art"
  },
  {
    "id": 211,
    "title": "Spirit Warrior",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132785.jpg",
    "likes": 979,
    "views": 64014,
    "year": 2021,
    "style": "Edo Period Art"
  },
  {
    "id": 212,
    "title": "Wandering Samurai",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141236.jpg",
    "likes": 7364,
    "views": 93845,
    "year": 2020,
    "style": "Kabuki Art"
  },
  {
    "id": 213,
    "title": "Fallen Hero",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP134578.jpg",
    "likes": 8532,
    "views": 3812,
    "year": 2024,
    "style": "Japanese Portrait"
  },
  {
    "id": 214,
    "title": "Rising Guardian",
    "artist": "Katsushika Hokusai 葛飾北斎",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/LC-2013_723_005_crd.jpg",
    "likes": 4207,
    "views": 14462,
    "year": 2025,
    "style": "Japanese Character Art"
  },
  {
    "id": 215,
    "title": "Hidden Sensei",
    "artist": "Hishikawa Moronobu",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124571.jpg",
    "likes": 3186,
    "views": 27906,
    "year": 2021,
    "style": "Traditional Japanese"
  },
  {
    "id": 216,
    "title": "Brave Spirit",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP121523.jpg",
    "likes": 497,
    "views": 87980,
    "year": 2023,
    "style": "Manga Style"
  },
  {
    "id": 217,
    "title": "Dark Phoenix",
    "artist": "Katsukawa Shunshō　勝川春���",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132849.jpg",
    "likes": 414,
    "views": 59169,
    "year": 2022,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 218,
    "title": "Eternal Dragon",
    "artist": "Utagawa (Gountei) Sadahide",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2007_49_335.JPG",
    "likes": 2324,
    "views": 23761,
    "year": 2025,
    "style": "Ukiyo-e"
  },
  {
    "id": 219,
    "title": "Crimson Fox",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP121502.jpg",
    "likes": 1697,
    "views": 42540,
    "year": 2020,
    "style": "Japanese Print Art"
  },
  {
    "id": 220,
    "title": "Azure Oracle",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141056.jpg",
    "likes": 6967,
    "views": 56548,
    "year": 2024,
    "style": "Edo Period Art"
  },
  {
    "id": 221,
    "title": "Jade Archer",
    "artist": "Katsukawa Shunkō",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141321.jpg",
    "likes": 519,
    "views": 79732,
    "year": 2023,
    "style": "Kabuki Art"
  },
  {
    "id": 222,
    "title": "Obsidian Storm",
    "artist": "Kubo Shunman",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138388.jpg",
    "likes": 8788,
    "views": 65003,
    "year": 2020,
    "style": "Japanese Portrait"
  },
  {
    "id": 223,
    "title": "Silent Princess",
    "artist": "Okumura Masanobu",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124534.jpg",
    "likes": 1808,
    "views": 3883,
    "year": 2023,
    "style": "Japanese Character Art"
  },
  {
    "id": 224,
    "title": "Moon Ninja",
    "artist": "Katsukawa Shunzan",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP145665.jpg",
    "likes": 8110,
    "views": 90591,
    "year": 2022,
    "style": "Traditional Japanese"
  },
  {
    "id": 225,
    "title": "Shadow Warrior",
    "artist": "Utagawa Yoshitora",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP148054.jpg",
    "likes": 8615,
    "views": 11639,
    "year": 2023,
    "style": "Manga Style"
  },
  {
    "id": 226,
    "title": "Spirit Samurai",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141017.jpg",
    "likes": 9658,
    "views": 11334,
    "year": 2022,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 227,
    "title": "Wandering Hero",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132802.jpg",
    "likes": 7273,
    "views": 8943,
    "year": 2022,
    "style": "Ukiyo-e"
  },
  {
    "id": 228,
    "title": "Fallen Guardian",
    "artist": "Katsukawa Shunsen",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123627.jpg",
    "likes": 6556,
    "views": 61544,
    "year": 2024,
    "style": "Japanese Print Art"
  },
  {
    "id": 229,
    "title": "Rising Sensei",
    "artist": "Yuki Nakamura",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123195.jpg",
    "likes": 7142,
    "views": 95056,
    "year": 2025,
    "style": "Edo Period Art"
  },
  {
    "id": 230,
    "title": "Hidden Spirit",
    "artist": "Totoya Hokkei",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP139070.jpg",
    "likes": 1685,
    "views": 82952,
    "year": 2021,
    "style": "Kabuki Art"
  },
  {
    "id": 231,
    "title": "Brave Phoenix",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141025.jpg",
    "likes": 1002,
    "views": 37510,
    "year": 2020,
    "style": "Japanese Portrait"
  },
  {
    "id": 232,
    "title": "Dark Dragon",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123567.jpg",
    "likes": 9348,
    "views": 98953,
    "year": 2024,
    "style": "Japanese Character Art"
  },
  {
    "id": 233,
    "title": "Eternal Fox",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122813.jpg",
    "likes": 7077,
    "views": 97772,
    "year": 2022,
    "style": "Traditional Japanese"
  },
  {
    "id": 234,
    "title": "Crimson Oracle",
    "artist": "Kitagawa Utamaro",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP144592.jpg",
    "likes": 2583,
    "views": 24514,
    "year": 2025,
    "style": "Manga Style"
  },
  {
    "id": 235,
    "title": "Azure Archer",
    "artist": "Utagawa Yoshikazu",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP148021.jpg",
    "likes": 7739,
    "views": 39260,
    "year": 2025,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 236,
    "title": "Jade Storm",
    "artist": "Kawamura Bunpō 河村文鳳",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_659_05_crd.jpg",
    "likes": 6493,
    "views": 3582,
    "year": 2024,
    "style": "Ukiyo-e"
  },
  {
    "id": 237,
    "title": "Obsidian Ronin",
    "artist": "Katsukawa Shun'ei",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP136897.jpg",
    "likes": 3265,
    "views": 27590,
    "year": 2022,
    "style": "Japanese Print Art"
  },
  {
    "id": 238,
    "title": "Silent Warrior",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP140954.jpg",
    "likes": 8326,
    "views": 93919,
    "year": 2021,
    "style": "Edo Period Art"
  },
  {
    "id": 239,
    "title": "Moon Samurai",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP143425.jpg",
    "likes": 5426,
    "views": 62896,
    "year": 2023,
    "style": "Kabuki Art"
  },
  {
    "id": 240,
    "title": "Shadow Hero",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132824.jpg",
    "likes": 1807,
    "views": 64250,
    "year": 2024,
    "style": "Japanese Portrait"
  },
  {
    "id": 241,
    "title": "Spirit Guardian",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123271.jpg",
    "likes": 9675,
    "views": 68717,
    "year": 2021,
    "style": "Japanese Character Art"
  },
  {
    "id": 242,
    "title": "Wandering Sensei",
    "artist": "Okumura Masanobu",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124499.jpg",
    "likes": 804,
    "views": 69580,
    "year": 2021,
    "style": "Traditional Japanese"
  },
  {
    "id": 243,
    "title": "Fallen Spirit",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141264.jpg",
    "likes": 7956,
    "views": 8823,
    "year": 2023,
    "style": "Manga Style"
  },
  {
    "id": 244,
    "title": "Rising Phoenix",
    "artist": "Ishikawa Toyonobu",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP146886.jpg",
    "likes": 8687,
    "views": 9466,
    "year": 2025,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 245,
    "title": "Hidden Dragon",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122853.jpg",
    "likes": 5490,
    "views": 89087,
    "year": 2021,
    "style": "Ukiyo-e"
  },
  {
    "id": 246,
    "title": "Brave Fox",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP146849.jpg",
    "likes": 5231,
    "views": 58936,
    "year": 2025,
    "style": "Japanese Print Art"
  },
  {
    "id": 247,
    "title": "Dark Oracle",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135867.jpg",
    "likes": 5618,
    "views": 72151,
    "year": 2024,
    "style": "Edo Period Art"
  },
  {
    "id": 248,
    "title": "Eternal Archer",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP121486.jpg",
    "likes": 9660,
    "views": 8784,
    "year": 2024,
    "style": "Kabuki Art"
  },
  {
    "id": 249,
    "title": "Crimson Storm",
    "artist": "Keisai Eisen",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135775.jpg",
    "likes": 7806,
    "views": 62487,
    "year": 2022,
    "style": "Japanese Portrait"
  },
  {
    "id": 250,
    "title": "Azure Ronin",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141096.jpg",
    "likes": 8084,
    "views": 94143,
    "year": 2020,
    "style": "Japanese Character Art"
  },
  {
    "id": 251,
    "title": "Jade Princess",
    "artist": "Kuwagata Keisai",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124553.jpg",
    "likes": 1040,
    "views": 88893,
    "year": 2022,
    "style": "Traditional Japanese"
  },
  {
    "id": 252,
    "title": "Obsidian Ninja",
    "artist": "Yashima Gakutei",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135709.jpg",
    "likes": 280,
    "views": 54037,
    "year": 2025,
    "style": "Manga Style"
  },
  {
    "id": 253,
    "title": "Silent Hero",
    "artist": "Kubo Shunman",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-14464-025.jpg",
    "likes": 199,
    "views": 82008,
    "year": 2021,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 254,
    "title": "Moon Guardian",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP140956.jpg",
    "likes": 7084,
    "views": 35709,
    "year": 2022,
    "style": "Ukiyo-e"
  },
  {
    "id": 255,
    "title": "Shadow Sensei",
    "artist": "Utagawa Yoshitora",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP142175.jpg",
    "likes": 6075,
    "views": 57317,
    "year": 2020,
    "style": "Japanese Print Art"
  },
  {
    "id": 256,
    "title": "Spirit Phoenix",
    "artist": "Yashima Gakutei",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP143395.jpg",
    "likes": 1044,
    "views": 38240,
    "year": 2025,
    "style": "Edo Period Art"
  },
  {
    "id": 257,
    "title": "Wandering Dragon",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP120470.jpg",
    "likes": 1146,
    "views": 92971,
    "year": 2022,
    "style": "Kabuki Art"
  },
  {
    "id": 258,
    "title": "Fallen Fox",
    "artist": "Utagawa Kuniyoshi",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-16050-001.jpg",
    "likes": 5204,
    "views": 33973,
    "year": 2021,
    "style": "Japanese Portrait"
  },
  {
    "id": 259,
    "title": "Rising Oracle",
    "artist": "Kubo Shunman",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138963.jpg",
    "likes": 8754,
    "views": 82307,
    "year": 2021,
    "style": "Japanese Character Art"
  },
  {
    "id": 260,
    "title": "Hidden Archer",
    "artist": "Kawamura Bunpō",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_663_a_c_a_21_crd.jpg",
    "likes": 2168,
    "views": 54455,
    "year": 2021,
    "style": "Traditional Japanese"
  },
  {
    "id": 261,
    "title": "Brave Storm",
    "artist": "Utagawa (Gountei) Sadahide",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP148152.jpg",
    "likes": 9078,
    "views": 31963,
    "year": 2025,
    "style": "Manga Style"
  },
  {
    "id": 262,
    "title": "Dark Ronin",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP145646.jpg",
    "likes": 8698,
    "views": 20490,
    "year": 2022,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 263,
    "title": "Eternal Princess",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132860.jpg",
    "likes": 4839,
    "views": 72455,
    "year": 2024,
    "style": "Ukiyo-e"
  },
  {
    "id": 264,
    "title": "Crimson Ninja",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141118.jpg",
    "likes": 7109,
    "views": 47183,
    "year": 2024,
    "style": "Japanese Print Art"
  },
  {
    "id": 265,
    "title": "Azure Warrior",
    "artist": "Kubo Shunman",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-14464-013.jpg",
    "likes": 1582,
    "views": 34697,
    "year": 2021,
    "style": "Edo Period Art"
  },
  {
    "id": 266,
    "title": "Jade Samurai",
    "artist": "Numata Kashū 沼田荷舟",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/JIB002_004_crd.jpg",
    "likes": 2868,
    "views": 8437,
    "year": 2024,
    "style": "Kabuki Art"
  },
  {
    "id": 267,
    "title": "Obsidian Hero",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132786.jpg",
    "likes": 8772,
    "views": 44004,
    "year": 2022,
    "style": "Japanese Portrait"
  },
  {
    "id": 268,
    "title": "Silent Guardian",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123207.jpg",
    "likes": 220,
    "views": 81895,
    "year": 2020,
    "style": "Japanese Character Art"
  },
  {
    "id": 269,
    "title": "Moon Sensei",
    "artist": "Utagawa Hiroshige 歌川広重",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_690_44_crd.jpg",
    "likes": 2864,
    "views": 59140,
    "year": 2022,
    "style": "Traditional Japanese"
  },
  {
    "id": 270,
    "title": "Shadow Phoenix",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP140959.jpg",
    "likes": 8036,
    "views": 86727,
    "year": 2023,
    "style": "Manga Style"
  },
  {
    "id": 271,
    "title": "Spirit Dragon",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP120464.jpg",
    "likes": 5785,
    "views": 55902,
    "year": 2023,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 272,
    "title": "Wandering Fox",
    "artist": "Hasegawa Sadanobu",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP130166.jpg",
    "likes": 9554,
    "views": 3459,
    "year": 2024,
    "style": "Ukiyo-e"
  },
  {
    "id": 273,
    "title": "Fallen Oracle",
    "artist": "Utagawa Yoshitora",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP148042.jpg",
    "likes": 6356,
    "views": 2241,
    "year": 2023,
    "style": "Japanese Print Art"
  },
  {
    "id": 274,
    "title": "Rising Archer",
    "artist": "Utagawa Kuniyoshi",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124496.jpg",
    "likes": 8326,
    "views": 60468,
    "year": 2022,
    "style": "Edo Period Art"
  },
  {
    "id": 275,
    "title": "Hidden Storm",
    "artist": "Hishikawa Moronobu",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124573.jpg",
    "likes": 8681,
    "views": 38070,
    "year": 2025,
    "style": "Kabuki Art"
  },
  {
    "id": 276,
    "title": "Brave Ronin",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP121494.jpg",
    "likes": 3220,
    "views": 73102,
    "year": 2022,
    "style": "Japanese Portrait"
  },
  {
    "id": 277,
    "title": "Dark Princess",
    "artist": "Ogura Tōkei 小倉東渓",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_846_04_crd.jpg",
    "likes": 1536,
    "views": 68098,
    "year": 2022,
    "style": "Japanese Character Art"
  },
  {
    "id": 278,
    "title": "Eternal Ninja",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP151591.jpg",
    "likes": 3335,
    "views": 27463,
    "year": 2022,
    "style": "Traditional Japanese"
  },
  {
    "id": 279,
    "title": "Crimson Warrior",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132845.jpg",
    "likes": 9595,
    "views": 45523,
    "year": 2021,
    "style": "Manga Style"
  },
  {
    "id": 280,
    "title": "Azure Samurai",
    "artist": "Kubo Shunman",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP139013.jpg",
    "likes": 9552,
    "views": 56262,
    "year": 2023,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 281,
    "title": "Jade Hero",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP134605.jpg",
    "likes": 6563,
    "views": 29698,
    "year": 2025,
    "style": "Ukiyo-e"
  },
  {
    "id": 282,
    "title": "Obsidian Guardian",
    "artist": "Katsukawa Shun'ei 勝川春英",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP136869.jpg",
    "likes": 5908,
    "views": 7908,
    "year": 2023,
    "style": "Japanese Print Art"
  },
  {
    "id": 283,
    "title": "Silent Sensei",
    "artist": "Utagawa Kunisada",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149204.jpg",
    "likes": 8375,
    "views": 44717,
    "year": 2022,
    "style": "Edo Period Art"
  },
  {
    "id": 284,
    "title": "Moon Phoenix",
    "artist": "Kubo Shunman",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138343.jpg",
    "likes": 6858,
    "views": 84150,
    "year": 2021,
    "style": "Kabuki Art"
  },
  {
    "id": 285,
    "title": "Shadow Dragon",
    "artist": "Shōtei Hokuju 昇亭北寿",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123614.jpg",
    "likes": 4383,
    "views": 69581,
    "year": 2024,
    "style": "Japanese Portrait"
  },
  {
    "id": 286,
    "title": "Spirit Fox",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123587.jpg",
    "likes": 727,
    "views": 51175,
    "year": 2022,
    "style": "Japanese Character Art"
  },
  {
    "id": 287,
    "title": "Wandering Oracle",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132856.jpg",
    "likes": 4894,
    "views": 67887,
    "year": 2021,
    "style": "Traditional Japanese"
  },
  {
    "id": 288,
    "title": "Fallen Archer",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141087.jpg",
    "likes": 6363,
    "views": 39161,
    "year": 2022,
    "style": "Manga Style"
  },
  {
    "id": 289,
    "title": "Rising Storm",
    "artist": "Kitagawa Utamaro 喜多川歌麿",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_854_a_b_a_04_crd.jpg",
    "likes": 3911,
    "views": 65530,
    "year": 2025,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 290,
    "title": "Hidden Ronin",
    "artist": "Kuwagata Keisai",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124554.jpg",
    "likes": 4119,
    "views": 11753,
    "year": 2021,
    "style": "Ukiyo-e"
  },
  {
    "id": 291,
    "title": "Brave Princess",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-34295-001.jpg",
    "likes": 7884,
    "views": 38261,
    "year": 2023,
    "style": "Japanese Print Art"
  },
  {
    "id": 292,
    "title": "Dark Ninja",
    "artist": "Katsushika Hokusai",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141049.jpg",
    "likes": 327,
    "views": 14305,
    "year": 2022,
    "style": "Edo Period Art"
  },
  {
    "id": 293,
    "title": "Eternal Warrior",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123607.jpg",
    "likes": 2239,
    "views": 49163,
    "year": 2020,
    "style": "Kabuki Art"
  },
  {
    "id": 294,
    "title": "Crimson Samurai",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122187.jpg",
    "likes": 2310,
    "views": 27037,
    "year": 2025,
    "style": "Japanese Portrait"
  },
  {
    "id": 295,
    "title": "Azure Hero",
    "artist": "Torii Kiyomasu I",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP144555.jpg",
    "likes": 6534,
    "views": 29110,
    "year": 2022,
    "style": "Japanese Character Art"
  },
  {
    "id": 296,
    "title": "Jade Guardian",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122175.jpg",
    "likes": 4754,
    "views": 73273,
    "year": 2024,
    "style": "Traditional Japanese"
  },
  {
    "id": 297,
    "title": "Obsidian Sensei",
    "artist": "Suzuki Harunobu 鈴木春信",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_687_a_c_a_04_crd.jpg",
    "likes": 4931,
    "views": 19840,
    "year": 2020,
    "style": "Manga Style"
  },
  {
    "id": 298,
    "title": "Silent Phoenix",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138903.jpg",
    "likes": 5030,
    "views": 42308,
    "year": 2025,
    "style": "Japanese Woodblock Print"
  },
  {
    "id": 299,
    "title": "Moon Dragon",
    "artist": "Yōshū (Hashimoto) Chikanobu",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149405.jpg",
    "likes": 1986,
    "views": 80279,
    "year": 2025,
    "style": "Ukiyo-e"
  },
  {
    "id": 300,
    "title": "Shadow Fox",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135830.jpg",
    "likes": 6337,
    "views": 35627,
    "year": 2020,
    "style": "Japanese Print Art"
  },
  {
    "id": 301,
    "title": "Spirit Oracle",
    "artist": "Yōshū (Hashimoto) Chikanobu",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149434.jpg",
    "likes": 9234,
    "views": 10031,
    "year": 2021,
    "style": "Edo Period Art"
  },
  {
    "id": 302,
    "title": "Wandering Archer",
    "artist": "Kitagawa Utamaro 喜多���歌麿",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135576.jpg",
    "likes": 4703,
    "views": 95579,
    "year": 2025,
    "style": "Kabuki Art"
  },
  {
    "id": 303,
    "title": "Fallen Storm",
    "artist": "Utagawa Hiroshige",
    "category": "Anime Sketches",
    "description": "A stunning Japanese woodblock print with fluid lines and expressive artistry.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122766.jpg",
    "likes": 189,
    "views": 25591,
    "year": 2025,
    "style": "Japanese Portrait"
  },
  {
    "id": 304,
    "title": "Rising Ronin",
    "artist": "Torii Kiyomasu I",
    "category": "Anime Sketches",
    "description": "Beautiful ukiyo-e print capturing the spirit of Edo period artistic tradition.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123689.jpg",
    "likes": 5873,
    "views": 54094,
    "year": 2025,
    "style": "Japanese Character Art"
  },
  {
    "id": 305,
    "title": "Hidden Princess",
    "artist": "Torii Kiyomasu I",
    "category": "Anime Sketches",
    "description": "Elegant Japanese print with bold outlines and dramatic use of color blocks.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123691.jpg",
    "likes": 3955,
    "views": 31218,
    "year": 2023,
    "style": "Traditional Japanese"
  },
  {
    "id": 306,
    "title": "Brave Ninja",
    "artist": "Suzuki Harunobu",
    "category": "Anime Sketches",
    "description": "Graceful traditional Japanese illustration with deep cultural heritage.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP114915.jpg",
    "likes": 4774,
    "views": 53471,
    "year": 2024,
    "style": "Manga Style"
  },
  {
    "id": 307,
    "title": "Dark Warrior",
    "artist": "Kitagawa Utamaro",
    "category": "Anime Sketches",
    "description": "Masterful woodblock print with intricate detail and timeless emotional depth.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141306.jpg",
    "likes": 3105,
    "views": 78023,
    "year": 2020,
    "style": "Japanese Woodblock Print"
  }
];
