export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const animeSketches: GalleryArtwork[] = [
  {
    "id": 301,
    "title": "Obsidian Paladin",
    "artist": "Benjamin Miller",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/301/800/1000",
    "likes": 535,
    "views": 57280,
    "year": 2020,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 302,
    "title": "Azure Mage",
    "artist": "Emily Jackson",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/302/800/1000",
    "likes": 8353,
    "views": 49307,
    "year": 2025,
    "style": "Anime Boy"
  },
  {
    "id": 303,
    "title": "Azure Angel",
    "artist": "Mei Jackson",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/303/800/1000",
    "likes": 2218,
    "views": 84697,
    "year": 2024,
    "style": "Anime Girl"
  },
  {
    "id": 304,
    "title": "Crimson Mage",
    "artist": "Mei Harris",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/304/800/1000",
    "likes": 3397,
    "views": 30565,
    "year": 2022,
    "style": "Original Manga Style"
  },
  {
    "id": 305,
    "title": "Amber Fox",
    "artist": "Mia Kim",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/305/800/1000",
    "likes": 391,
    "views": 94545,
    "year": 2025,
    "style": "Anime Character Design"
  },
  {
    "id": 306,
    "title": "Dreaming Oracle",
    "artist": "Harper Yamamoto",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/306/800/1000",
    "likes": 2523,
    "views": 62079,
    "year": 2021,
    "style": "Black and White Sketch"
  },
  {
    "id": 307,
    "title": "Rising Seer",
    "artist": "Noah Patel",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/307/800/1000",
    "likes": 2444,
    "views": 64971,
    "year": 2022,
    "style": "Chibi"
  },
  {
    "id": 308,
    "title": "Jade Witch",
    "artist": "Liam Thomas",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/308/800/1000",
    "likes": 391,
    "views": 9440,
    "year": 2020,
    "style": "Anime Expressions"
  },
  {
    "id": 309,
    "title": "Light Princess",
    "artist": "Sophia Rodriguez",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/309/800/1000",
    "likes": 6454,
    "views": 56034,
    "year": 2023,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 310,
    "title": "Eternal Paladin",
    "artist": "Isabella Singh",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/310/800/1000",
    "likes": 9852,
    "views": 1562,
    "year": 2022,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 311,
    "title": "Rising Fighter",
    "artist": "Noah Miller",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/311/800/1000",
    "likes": 6682,
    "views": 85975,
    "year": 2023,
    "style": "Anime Boy"
  },
  {
    "id": 312,
    "title": "Dark Princess",
    "artist": "James Garcia",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/312/800/1000",
    "likes": 2764,
    "views": 84442,
    "year": 2025,
    "style": "Anime Girl"
  },
  {
    "id": 313,
    "title": "Rising Hero",
    "artist": "Mei Tanaka",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/313/800/1000",
    "likes": 2130,
    "views": 69750,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 314,
    "title": "Wind Dragon",
    "artist": "James Rodriguez",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/314/800/1000",
    "likes": 2649,
    "views": 42839,
    "year": 2022,
    "style": "Anime Character Design"
  },
  {
    "id": 315,
    "title": "Dreaming Warrior",
    "artist": "Oliver Yamamoto",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/315/800/1000",
    "likes": 7388,
    "views": 29333,
    "year": 2023,
    "style": "Black and White Sketch"
  },
  {
    "id": 316,
    "title": "Ivory Dragon",
    "artist": "Yuki Nguyen",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/316/800/1000",
    "likes": 3489,
    "views": 87927,
    "year": 2024,
    "style": "Chibi"
  },
  {
    "id": 317,
    "title": "Hidden Blade",
    "artist": "William Thomas",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/317/800/1000",
    "likes": 3770,
    "views": 8628,
    "year": 2023,
    "style": "Anime Expressions"
  },
  {
    "id": 318,
    "title": "Brave Fox",
    "artist": "James Rodriguez",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/318/800/1000",
    "likes": 4103,
    "views": 78626,
    "year": 2024,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 319,
    "title": "Moon Fighter",
    "artist": "Lucas Miller",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/319/800/1000",
    "likes": 7626,
    "views": 10114,
    "year": 2022,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 320,
    "title": "Azure Phoenix",
    "artist": "Ethan Garcia",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/320/800/1000",
    "likes": 6217,
    "views": 80780,
    "year": 2024,
    "style": "Anime Boy"
  },
  {
    "id": 321,
    "title": "Storm Princess",
    "artist": "Liam Kim",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/321/800/1000",
    "likes": 4323,
    "views": 5258,
    "year": 2023,
    "style": "Anime Girl"
  },
  {
    "id": 322,
    "title": "Crimson Knight",
    "artist": "Isabella Anderson",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/322/800/1000",
    "likes": 6938,
    "views": 90604,
    "year": 2021,
    "style": "Original Manga Style"
  },
  {
    "id": 323,
    "title": "Eternal Witch",
    "artist": "Charlotte Martinez",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/323/800/1000",
    "likes": 7956,
    "views": 54121,
    "year": 2023,
    "style": "Anime Character Design"
  },
  {
    "id": 324,
    "title": "Thunder Witch",
    "artist": "Amelia Davis",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/324/800/1000",
    "likes": 1779,
    "views": 17427,
    "year": 2022,
    "style": "Black and White Sketch"
  },
  {
    "id": 325,
    "title": "Moon Samurai",
    "artist": "Priya Rodriguez",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/325/800/1000",
    "likes": 1746,
    "views": 79654,
    "year": 2021,
    "style": "Chibi"
  },
  {
    "id": 326,
    "title": "Storm Knight",
    "artist": "Mia Rodriguez",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/326/800/1000",
    "likes": 7221,
    "views": 34581,
    "year": 2020,
    "style": "Anime Expressions"
  },
  {
    "id": 327,
    "title": "Jade Blade",
    "artist": "Harper Johnson",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/327/800/1000",
    "likes": 8672,
    "views": 2182,
    "year": 2024,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 328,
    "title": "Hidden Hero",
    "artist": "Elijah Carter",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/328/800/1000",
    "likes": 1876,
    "views": 55150,
    "year": 2020,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 329,
    "title": "Wind Phoenix",
    "artist": "Emma Anderson",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/329/800/1000",
    "likes": 1692,
    "views": 57558,
    "year": 2023,
    "style": "Anime Boy"
  },
  {
    "id": 330,
    "title": "Spirit Storm",
    "artist": "Harper Yamamoto",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/330/800/1000",
    "likes": 3095,
    "views": 35017,
    "year": 2023,
    "style": "Anime Girl"
  },
  {
    "id": 331,
    "title": "Crimson Princess",
    "artist": "Liam Brown",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/331/800/1000",
    "likes": 4503,
    "views": 38165,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 332,
    "title": "Dark Soul",
    "artist": "Emily Yamamoto",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/332/800/1000",
    "likes": 1876,
    "views": 48248,
    "year": 2025,
    "style": "Anime Character Design"
  },
  {
    "id": 333,
    "title": "Burning Guardian",
    "artist": "Ava White",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/333/800/1000",
    "likes": 293,
    "views": 37404,
    "year": 2025,
    "style": "Black and White Sketch"
  },
  {
    "id": 334,
    "title": "Shadow Hero",
    "artist": "Isabella Harris",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/334/800/1000",
    "likes": 128,
    "views": 7768,
    "year": 2023,
    "style": "Chibi"
  },
  {
    "id": 335,
    "title": "Jade Blade",
    "artist": "Elijah Brown",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/335/800/1000",
    "likes": 6657,
    "views": 65016,
    "year": 2020,
    "style": "Anime Expressions"
  },
  {
    "id": 336,
    "title": "Hidden Princess",
    "artist": "Lucas Davis",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/336/800/1000",
    "likes": 3014,
    "views": 47963,
    "year": 2023,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 337,
    "title": "Eternal Soul",
    "artist": "James White",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/337/800/1000",
    "likes": 6690,
    "views": 4940,
    "year": 2020,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 338,
    "title": "Silent Guardian",
    "artist": "Yuki Chen",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/338/800/1000",
    "likes": 6010,
    "views": 60358,
    "year": 2025,
    "style": "Anime Boy"
  },
  {
    "id": 339,
    "title": "Eternal Samurai",
    "artist": "Noah Taylor",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/339/800/1000",
    "likes": 4318,
    "views": 91654,
    "year": 2024,
    "style": "Anime Girl"
  },
  {
    "id": 340,
    "title": "Crimson Sensei",
    "artist": "Sophia Davis",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/340/800/1000",
    "likes": 6678,
    "views": 79516,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 341,
    "title": "Dreaming Guardian",
    "artist": "Mei Rodriguez",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/341/800/1000",
    "likes": 7952,
    "views": 98445,
    "year": 2024,
    "style": "Anime Character Design"
  },
  {
    "id": 342,
    "title": "Amber Paladin",
    "artist": "Amelia Jones",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/342/800/1000",
    "likes": 2219,
    "views": 44689,
    "year": 2025,
    "style": "Black and White Sketch"
  },
  {
    "id": 343,
    "title": "Dreaming Guardian",
    "artist": "Ava Tanaka",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/343/800/1000",
    "likes": 726,
    "views": 76599,
    "year": 2024,
    "style": "Chibi"
  },
  {
    "id": 344,
    "title": "Moon Knight",
    "artist": "Benjamin Williams",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/344/800/1000",
    "likes": 8747,
    "views": 33622,
    "year": 2024,
    "style": "Anime Expressions"
  },
  {
    "id": 345,
    "title": "Spirit Ninja",
    "artist": "Aiko Anderson",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/345/800/1000",
    "likes": 5648,
    "views": 41530,
    "year": 2022,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 346,
    "title": "Frozen Angel",
    "artist": "Sophia Smith",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/346/800/1000",
    "likes": 7079,
    "views": 3927,
    "year": 2025,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 347,
    "title": "Spirit Witch",
    "artist": "Priya Harris",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/347/800/1000",
    "likes": 6908,
    "views": 99026,
    "year": 2024,
    "style": "Anime Boy"
  },
  {
    "id": 348,
    "title": "Frozen Angel",
    "artist": "Oliver Davis",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/348/800/1000",
    "likes": 7086,
    "views": 48256,
    "year": 2023,
    "style": "Anime Girl"
  },
  {
    "id": 349,
    "title": "Crimson Spirit",
    "artist": "James Kim",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/349/800/1000",
    "likes": 2518,
    "views": 27266,
    "year": 2024,
    "style": "Original Manga Style"
  },
  {
    "id": 350,
    "title": "Rising Princess",
    "artist": "Rahul Jackson",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/350/800/1000",
    "likes": 3053,
    "views": 93077,
    "year": 2023,
    "style": "Anime Character Design"
  },
  {
    "id": 351,
    "title": "Dreaming Dragon",
    "artist": "Isabella Johnson",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/351/800/1000",
    "likes": 1175,
    "views": 90085,
    "year": 2023,
    "style": "Black and White Sketch"
  },
  {
    "id": 352,
    "title": "Ivory Guardian",
    "artist": "James Johnson",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/352/800/1000",
    "likes": 2542,
    "views": 68575,
    "year": 2021,
    "style": "Chibi"
  },
  {
    "id": 353,
    "title": "Jade Warrior",
    "artist": "Emma Patel",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/353/800/1000",
    "likes": 7747,
    "views": 50791,
    "year": 2021,
    "style": "Anime Expressions"
  },
  {
    "id": 354,
    "title": "Spirit Angel",
    "artist": "Liam Patel",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/354/800/1000",
    "likes": 6014,
    "views": 98800,
    "year": 2020,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 355,
    "title": "Rising Sensei",
    "artist": "Amelia Miller",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/355/800/1000",
    "likes": 5832,
    "views": 49699,
    "year": 2022,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 356,
    "title": "Amber Fighter",
    "artist": "Amelia Nguyen",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/356/800/1000",
    "likes": 6733,
    "views": 38075,
    "year": 2024,
    "style": "Anime Boy"
  },
  {
    "id": 357,
    "title": "Rising Samurai",
    "artist": "James Tanaka",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/357/800/1000",
    "likes": 1556,
    "views": 35081,
    "year": 2023,
    "style": "Anime Girl"
  },
  {
    "id": 358,
    "title": "Wandering Hero",
    "artist": "Alexander Taylor",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/358/800/1000",
    "likes": 904,
    "views": 67395,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 359,
    "title": "Light Spirit",
    "artist": "James Carter",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/359/800/1000",
    "likes": 3191,
    "views": 93772,
    "year": 2025,
    "style": "Anime Character Design"
  },
  {
    "id": 360,
    "title": "Brave Knight",
    "artist": "Emily Anderson",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/360/800/1000",
    "likes": 5105,
    "views": 76604,
    "year": 2020,
    "style": "Black and White Sketch"
  },
  {
    "id": 361,
    "title": "Rising Blade",
    "artist": "Mia Tanaka",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/361/800/1000",
    "likes": 4497,
    "views": 11577,
    "year": 2024,
    "style": "Chibi"
  },
  {
    "id": 362,
    "title": "Lost Witch",
    "artist": "James Rodriguez",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/362/800/1000",
    "likes": 384,
    "views": 55147,
    "year": 2021,
    "style": "Anime Expressions"
  },
  {
    "id": 363,
    "title": "Jade Blade",
    "artist": "Amelia Tanaka",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/363/800/1000",
    "likes": 2028,
    "views": 88840,
    "year": 2021,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 364,
    "title": "Ivory Storm",
    "artist": "Liam Harris",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/364/800/1000",
    "likes": 6080,
    "views": 10430,
    "year": 2024,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 365,
    "title": "Obsidian Witch",
    "artist": "Emily Nguyen",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/365/800/1000",
    "likes": 4241,
    "views": 31838,
    "year": 2024,
    "style": "Anime Boy"
  },
  {
    "id": 366,
    "title": "Lost Demon",
    "artist": "James Kim",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/366/800/1000",
    "likes": 708,
    "views": 51541,
    "year": 2025,
    "style": "Anime Girl"
  },
  {
    "id": 367,
    "title": "Dreaming Ronin",
    "artist": "Yuki Nguyen",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/367/800/1000",
    "likes": 1705,
    "views": 90426,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 368,
    "title": "Moon Paladin",
    "artist": "James Smith",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/368/800/1000",
    "likes": 3837,
    "views": 97574,
    "year": 2024,
    "style": "Anime Character Design"
  },
  {
    "id": 369,
    "title": "Wind Hero",
    "artist": "Liam Williams",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/369/800/1000",
    "likes": 1575,
    "views": 46592,
    "year": 2024,
    "style": "Black and White Sketch"
  },
  {
    "id": 370,
    "title": "Spirit Sensei",
    "artist": "Mei Taylor",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/370/800/1000",
    "likes": 7346,
    "views": 84667,
    "year": 2021,
    "style": "Chibi"
  },
  {
    "id": 371,
    "title": "Eternal Warrior",
    "artist": "Aiko Kim",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/371/800/1000",
    "likes": 2717,
    "views": 53334,
    "year": 2020,
    "style": "Anime Expressions"
  },
  {
    "id": 372,
    "title": "Frozen Dragon",
    "artist": "Mia Chen",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/372/800/1000",
    "likes": 2654,
    "views": 10160,
    "year": 2024,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 373,
    "title": "Moon Ronin",
    "artist": "Amelia Kim",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/373/800/1000",
    "likes": 9484,
    "views": 7247,
    "year": 2021,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 374,
    "title": "Azure Blade",
    "artist": "Lucas Anderson",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/374/800/1000",
    "likes": 3276,
    "views": 53211,
    "year": 2020,
    "style": "Anime Boy"
  },
  {
    "id": 375,
    "title": "Lost Archer",
    "artist": "Emily Chen",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/375/800/1000",
    "likes": 1306,
    "views": 39929,
    "year": 2022,
    "style": "Anime Girl"
  },
  {
    "id": 376,
    "title": "Moon Dragon",
    "artist": "Ethan Carter",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/376/800/1000",
    "likes": 5542,
    "views": 66808,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 377,
    "title": "Storm Storm",
    "artist": "Mia Okonkwo",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/377/800/1000",
    "likes": 5471,
    "views": 51141,
    "year": 2023,
    "style": "Anime Character Design"
  },
  {
    "id": 378,
    "title": "Jade Mage",
    "artist": "Ethan Brown",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/378/800/1000",
    "likes": 9389,
    "views": 12495,
    "year": 2023,
    "style": "Black and White Sketch"
  },
  {
    "id": 379,
    "title": "Silent Princess",
    "artist": "Mei Carter",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/379/800/1000",
    "likes": 2285,
    "views": 92919,
    "year": 2022,
    "style": "Chibi"
  },
  {
    "id": 380,
    "title": "Crimson Guardian",
    "artist": "Lucas Patel",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/380/800/1000",
    "likes": 8824,
    "views": 48827,
    "year": 2021,
    "style": "Anime Expressions"
  },
  {
    "id": 381,
    "title": "Obsidian Oracle",
    "artist": "Harper Patel",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/381/800/1000",
    "likes": 2178,
    "views": 48871,
    "year": 2023,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 382,
    "title": "Burning Demon",
    "artist": "Noah Davis",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/382/800/1000",
    "likes": 9538,
    "views": 61333,
    "year": 2020,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 383,
    "title": "Lost Mage",
    "artist": "William Brown",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/383/800/1000",
    "likes": 4214,
    "views": 7489,
    "year": 2025,
    "style": "Anime Boy"
  },
  {
    "id": 384,
    "title": "Silent Witch",
    "artist": "Rahul Rodriguez",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/384/800/1000",
    "likes": 2519,
    "views": 60172,
    "year": 2020,
    "style": "Anime Girl"
  },
  {
    "id": 385,
    "title": "Jade Oracle",
    "artist": "Benjamin Davis",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/385/800/1000",
    "likes": 2511,
    "views": 38880,
    "year": 2022,
    "style": "Original Manga Style"
  },
  {
    "id": 386,
    "title": "Shadow Sensei",
    "artist": "Yuki Brown",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/386/800/1000",
    "likes": 2458,
    "views": 38344,
    "year": 2022,
    "style": "Anime Character Design"
  },
  {
    "id": 387,
    "title": "Wandering Warrior",
    "artist": "Olivia White",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/387/800/1000",
    "likes": 9949,
    "views": 45923,
    "year": 2025,
    "style": "Black and White Sketch"
  },
  {
    "id": 388,
    "title": "Storm Knight",
    "artist": "James Thomas",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/388/800/1000",
    "likes": 4259,
    "views": 37328,
    "year": 2021,
    "style": "Chibi"
  },
  {
    "id": 389,
    "title": "Burning Witch",
    "artist": "Harper White",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/389/800/1000",
    "likes": 6335,
    "views": 24416,
    "year": 2020,
    "style": "Anime Expressions"
  },
  {
    "id": 390,
    "title": "Silent Witch",
    "artist": "Priya Kim",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/390/800/1000",
    "likes": 6441,
    "views": 47542,
    "year": 2020,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 391,
    "title": "Light Mage",
    "artist": "Mei Garcia",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/391/800/1000",
    "likes": 901,
    "views": 39315,
    "year": 2023,
    "style": "Anime Pencil Sketch"
  },
  {
    "id": 392,
    "title": "Fallen Ronin",
    "artist": "Charlotte Davis",
    "category": "Anime Sketches",
    "description": "Black and white manga-style illustration with clean, confident linework.",
    "image": "https://picsum.photos/id/392/800/1000",
    "likes": 1226,
    "views": 81139,
    "year": 2022,
    "style": "Anime Boy"
  },
  {
    "id": 393,
    "title": "Thunder Fighter",
    "artist": "Mei Thomas",
    "category": "Anime Sketches",
    "description": "Chibi character design with adorably exaggerated features and expressions.",
    "image": "https://picsum.photos/id/393/800/1000",
    "likes": 8684,
    "views": 74204,
    "year": 2021,
    "style": "Anime Girl"
  },
  {
    "id": 394,
    "title": "Hidden Witch",
    "artist": "James Singh",
    "category": "Anime Sketches",
    "description": "Anime protagonist in a dynamic action pose showing strength and spirit.",
    "image": "https://picsum.photos/id/394/800/1000",
    "likes": 8920,
    "views": 13391,
    "year": 2020,
    "style": "Original Manga Style"
  },
  {
    "id": 395,
    "title": "Storm Warrior",
    "artist": "Alexander Rodriguez",
    "category": "Anime Sketches",
    "description": "Soft pencil sketch of an anime girl with flowing hair and emotional depth.",
    "image": "https://picsum.photos/id/395/800/1000",
    "likes": 7366,
    "views": 70937,
    "year": 2020,
    "style": "Anime Character Design"
  },
  {
    "id": 396,
    "title": "Frozen Oracle",
    "artist": "Sophia Thomas",
    "category": "Anime Sketches",
    "description": "Original anime character with a unique and detailed costume design.",
    "image": "https://picsum.photos/id/396/800/1000",
    "likes": 4090,
    "views": 87310,
    "year": 2024,
    "style": "Black and White Sketch"
  },
  {
    "id": 397,
    "title": "Shadow Phoenix",
    "artist": "Benjamin Johnson",
    "category": "Anime Sketches",
    "description": "Manga-style panel illustration with dramatic ink shading and composition.",
    "image": "https://picsum.photos/id/397/800/1000",
    "likes": 2778,
    "views": 69082,
    "year": 2022,
    "style": "Chibi"
  },
  {
    "id": 398,
    "title": "Lost Seer",
    "artist": "Lucas Kim",
    "category": "Anime Sketches",
    "description": "Fantasy anime character with elemental powers and ethereal costume.",
    "image": "https://picsum.photos/id/398/800/1000",
    "likes": 4311,
    "views": 97325,
    "year": 2020,
    "style": "Anime Expressions"
  },
  {
    "id": 399,
    "title": "Frozen Mage",
    "artist": "Oliver Carter",
    "category": "Anime Sketches",
    "description": "Expressive anime expression study showing a wide range of emotions.",
    "image": "https://picsum.photos/id/399/800/1000",
    "likes": 6218,
    "views": 72303,
    "year": 2021,
    "style": "Fantasy Anime Character"
  },
  {
    "id": 400,
    "title": "Fallen Samurai",
    "artist": "Sophia Harris",
    "category": "Anime Sketches",
    "description": "A detailed pencil sketch of an original anime character with expressive eyes.",
    "image": "https://picsum.photos/id/400/800/1000",
    "likes": 1273,
    "views": 79329,
    "year": 2022,
    "style": "Anime Pencil Sketch"
  }
];
