export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const creativePortraits: GalleryArtwork[] = [
  {
    "id": 501,
    "title": "Broken Story",
    "artist": "Mia Patel",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/501/800/1000",
    "likes": 6851,
    "views": 70737,
    "year": 2021,
    "style": "Pencil Portrait"
  },
  {
    "id": 502,
    "title": "Warm Voice",
    "artist": "Harper Jones",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/502/800/1000",
    "likes": 129,
    "views": 87081,
    "year": 2023,
    "style": "Charcoal Portrait"
  },
  {
    "id": 503,
    "title": "Pale Gaze",
    "artist": "Isabella Davis",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/503/800/1000",
    "likes": 1191,
    "views": 60352,
    "year": 2024,
    "style": "Watercolor Portrait"
  },
  {
    "id": 504,
    "title": "The Shadow",
    "artist": "Ava Nguyen",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/504/800/1000",
    "likes": 951,
    "views": 80213,
    "year": 2022,
    "style": "Digital Portrait"
  },
  {
    "id": 505,
    "title": "Tender Face",
    "artist": "Charlotte Harris",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/505/800/1000",
    "likes": 517,
    "views": 5941,
    "year": 2022,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 506,
    "title": "Found Whisper",
    "artist": "Ethan Thomas",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/506/800/1000",
    "likes": 3938,
    "views": 24961,
    "year": 2021,
    "style": "Fantasy Portrait"
  },
  {
    "id": 507,
    "title": "Distant Touch",
    "artist": "Isabella Thomas",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/507/800/1000",
    "likes": 1698,
    "views": 30013,
    "year": 2023,
    "style": "Male Portrait"
  },
  {
    "id": 508,
    "title": "Golden Portrait",
    "artist": "Aiko Smith",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/508/800/1000",
    "likes": 2204,
    "views": 27148,
    "year": 2025,
    "style": "Female Portrait"
  },
  {
    "id": 509,
    "title": "Warm Light",
    "artist": "Lucas Kim",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/509/800/1000",
    "likes": 5952,
    "views": 68602,
    "year": 2022,
    "style": "Creative Face Illustration"
  },
  {
    "id": 510,
    "title": "Warm Voice",
    "artist": "Ava Patel",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/510/800/1000",
    "likes": 5149,
    "views": 39159,
    "year": 2024,
    "style": "Pencil Portrait"
  },
  {
    "id": 511,
    "title": "The Soul",
    "artist": "Alexander Carter",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/511/800/1000",
    "likes": 5450,
    "views": 91976,
    "year": 2025,
    "style": "Charcoal Portrait"
  },
  {
    "id": 512,
    "title": "Vivid Emotion",
    "artist": "Emma Smith",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/512/800/1000",
    "likes": 6356,
    "views": 22832,
    "year": 2021,
    "style": "Watercolor Portrait"
  },
  {
    "id": 513,
    "title": "The Portrait",
    "artist": "Aiko Johnson",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/513/800/1000",
    "likes": 8383,
    "views": 18948,
    "year": 2021,
    "style": "Digital Portrait"
  },
  {
    "id": 514,
    "title": "Light Muse",
    "artist": "Emily Jackson",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/514/800/1000",
    "likes": 5463,
    "views": 99683,
    "year": 2022,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 515,
    "title": "Tender Whisper",
    "artist": "Ava Carter",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/515/800/1000",
    "likes": 8810,
    "views": 97198,
    "year": 2023,
    "style": "Fantasy Portrait"
  },
  {
    "id": 516,
    "title": "Tender Gaze",
    "artist": "Sophia Johnson",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/516/800/1000",
    "likes": 1379,
    "views": 77092,
    "year": 2025,
    "style": "Male Portrait"
  },
  {
    "id": 517,
    "title": "Cold Soul",
    "artist": "Lucas Johnson",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/517/800/1000",
    "likes": 9827,
    "views": 60652,
    "year": 2024,
    "style": "Female Portrait"
  },
  {
    "id": 518,
    "title": "Gentle Smile",
    "artist": "Mei Thomas",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/518/800/1000",
    "likes": 388,
    "views": 96488,
    "year": 2022,
    "style": "Creative Face Illustration"
  },
  {
    "id": 519,
    "title": "Fierce Thinker",
    "artist": "Alexander Garcia",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/519/800/1000",
    "likes": 4067,
    "views": 59326,
    "year": 2024,
    "style": "Pencil Portrait"
  },
  {
    "id": 520,
    "title": "Hidden Moment",
    "artist": "Amelia Chen",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/520/800/1000",
    "likes": 3295,
    "views": 90508,
    "year": 2020,
    "style": "Charcoal Portrait"
  },
  {
    "id": 521,
    "title": "Hidden Story",
    "artist": "Olivia Jones",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/521/800/1000",
    "likes": 4711,
    "views": 30165,
    "year": 2023,
    "style": "Watercolor Portrait"
  },
  {
    "id": 522,
    "title": "Mystic Soul",
    "artist": "Elijah Kim",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/522/800/1000",
    "likes": 3275,
    "views": 30964,
    "year": 2022,
    "style": "Digital Portrait"
  },
  {
    "id": 523,
    "title": "Broken Stare",
    "artist": "James Yamamoto",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/523/800/1000",
    "likes": 9939,
    "views": 16532,
    "year": 2020,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 524,
    "title": "Hidden Expression",
    "artist": "Mia Okonkwo",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/524/800/1000",
    "likes": 3682,
    "views": 2348,
    "year": 2024,
    "style": "Fantasy Portrait"
  },
  {
    "id": 525,
    "title": "Light Thinker",
    "artist": "Lucas Harris",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/525/800/1000",
    "likes": 1283,
    "views": 29904,
    "year": 2022,
    "style": "Male Portrait"
  },
  {
    "id": 526,
    "title": "Mystic Thinker",
    "artist": "Olivia Miller",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/526/800/1000",
    "likes": 2851,
    "views": 74365,
    "year": 2022,
    "style": "Female Portrait"
  },
  {
    "id": 527,
    "title": "Hopeful Thinker",
    "artist": "Emily Tanaka",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/527/800/1000",
    "likes": 2525,
    "views": 68047,
    "year": 2025,
    "style": "Creative Face Illustration"
  },
  {
    "id": 528,
    "title": "Close Eyes",
    "artist": "Yuki Jackson",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/528/800/1000",
    "likes": 6626,
    "views": 5517,
    "year": 2024,
    "style": "Pencil Portrait"
  },
  {
    "id": 529,
    "title": "Mystic Gaze",
    "artist": "Oliver Martinez",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/529/800/1000",
    "likes": 422,
    "views": 16624,
    "year": 2024,
    "style": "Charcoal Portrait"
  },
  {
    "id": 530,
    "title": "Found Stare",
    "artist": "James Martinez",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/530/800/1000",
    "likes": 3881,
    "views": 98008,
    "year": 2022,
    "style": "Watercolor Portrait"
  },
  {
    "id": 531,
    "title": "The Eyes",
    "artist": "Ethan Jackson",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/531/800/1000",
    "likes": 3017,
    "views": 8498,
    "year": 2022,
    "style": "Digital Portrait"
  },
  {
    "id": 532,
    "title": "Broken Secret",
    "artist": "Ava Thomas",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/532/800/1000",
    "likes": 3840,
    "views": 29920,
    "year": 2024,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 533,
    "title": "Cold Stare",
    "artist": "Mei Martinez",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/533/800/1000",
    "likes": 5486,
    "views": 67403,
    "year": 2023,
    "style": "Fantasy Portrait"
  },
  {
    "id": 534,
    "title": "Hopeful Portrait",
    "artist": "Mei Williams",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/534/800/1000",
    "likes": 2005,
    "views": 18476,
    "year": 2024,
    "style": "Male Portrait"
  },
  {
    "id": 535,
    "title": "Cold Light",
    "artist": "William Yamamoto",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/535/800/1000",
    "likes": 4884,
    "views": 94151,
    "year": 2024,
    "style": "Female Portrait"
  },
  {
    "id": 536,
    "title": "Light Emotion",
    "artist": "Noah Davis",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/536/800/1000",
    "likes": 1725,
    "views": 59142,
    "year": 2023,
    "style": "Creative Face Illustration"
  },
  {
    "id": 537,
    "title": "Warm Visage",
    "artist": "Olivia Okonkwo",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/537/800/1000",
    "likes": 8423,
    "views": 44337,
    "year": 2020,
    "style": "Pencil Portrait"
  },
  {
    "id": 538,
    "title": "Gentle Gaze",
    "artist": "Lucas Nguyen",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/538/800/1000",
    "likes": 6386,
    "views": 83874,
    "year": 2025,
    "style": "Charcoal Portrait"
  },
  {
    "id": 539,
    "title": "Found Visage",
    "artist": "Emily Harris",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/539/800/1000",
    "likes": 7606,
    "views": 46796,
    "year": 2025,
    "style": "Watercolor Portrait"
  },
  {
    "id": 540,
    "title": "Found Expression",
    "artist": "Priya Garcia",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/540/800/1000",
    "likes": 5969,
    "views": 89882,
    "year": 2025,
    "style": "Digital Portrait"
  },
  {
    "id": 541,
    "title": "Dark Portrait",
    "artist": "Noah Martinez",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/541/800/1000",
    "likes": 7842,
    "views": 45217,
    "year": 2023,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 542,
    "title": "Light Visage",
    "artist": "Yuki Davis",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/542/800/1000",
    "likes": 104,
    "views": 31725,
    "year": 2022,
    "style": "Fantasy Portrait"
  },
  {
    "id": 543,
    "title": "Soul Soul",
    "artist": "Emma Rodriguez",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/543/800/1000",
    "likes": 3258,
    "views": 29740,
    "year": 2025,
    "style": "Male Portrait"
  },
  {
    "id": 544,
    "title": "Mystic Gaze",
    "artist": "Isabella Jones",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/544/800/1000",
    "likes": 2215,
    "views": 67715,
    "year": 2022,
    "style": "Female Portrait"
  },
  {
    "id": 545,
    "title": "Lost Profile",
    "artist": "Olivia Kim",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/545/800/1000",
    "likes": 6141,
    "views": 67340,
    "year": 2020,
    "style": "Creative Face Illustration"
  },
  {
    "id": 546,
    "title": "Mystic Face",
    "artist": "Elijah Smith",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/546/800/1000",
    "likes": 8864,
    "views": 44045,
    "year": 2021,
    "style": "Pencil Portrait"
  },
  {
    "id": 547,
    "title": "Broken Face",
    "artist": "Liam Brown",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/547/800/1000",
    "likes": 9801,
    "views": 79356,
    "year": 2021,
    "style": "Charcoal Portrait"
  },
  {
    "id": 548,
    "title": "Found Secret",
    "artist": "Ethan Johnson",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/548/800/1000",
    "likes": 9091,
    "views": 20121,
    "year": 2023,
    "style": "Watercolor Portrait"
  },
  {
    "id": 549,
    "title": "Silent Light",
    "artist": "Yuki Okonkwo",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/549/800/1000",
    "likes": 9481,
    "views": 44600,
    "year": 2024,
    "style": "Digital Portrait"
  },
  {
    "id": 550,
    "title": "Lost Stranger",
    "artist": "Mia Taylor",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/550/800/1000",
    "likes": 6490,
    "views": 93716,
    "year": 2024,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 551,
    "title": "Silent Face",
    "artist": "James Chen",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/551/800/1000",
    "likes": 633,
    "views": 95724,
    "year": 2021,
    "style": "Fantasy Portrait"
  },
  {
    "id": 552,
    "title": "Pale Muse",
    "artist": "Amelia Smith",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/552/800/1000",
    "likes": 4884,
    "views": 11348,
    "year": 2021,
    "style": "Male Portrait"
  },
  {
    "id": 553,
    "title": "Close Stranger",
    "artist": "Ava Patel",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/553/800/1000",
    "likes": 1374,
    "views": 65715,
    "year": 2024,
    "style": "Female Portrait"
  },
  {
    "id": 554,
    "title": "Lost Story",
    "artist": "Isabella Taylor",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/554/800/1000",
    "likes": 9139,
    "views": 6357,
    "year": 2020,
    "style": "Creative Face Illustration"
  },
  {
    "id": 555,
    "title": "Lone Thinker",
    "artist": "Priya Johnson",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/555/800/1000",
    "likes": 208,
    "views": 36917,
    "year": 2023,
    "style": "Pencil Portrait"
  },
  {
    "id": 556,
    "title": "Hopeful Story",
    "artist": "Lucas Nguyen",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/556/800/1000",
    "likes": 2296,
    "views": 47174,
    "year": 2020,
    "style": "Charcoal Portrait"
  },
  {
    "id": 557,
    "title": "Pale Expression",
    "artist": "Noah Jones",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/557/800/1000",
    "likes": 5843,
    "views": 84148,
    "year": 2024,
    "style": "Watercolor Portrait"
  },
  {
    "id": 558,
    "title": "Hidden Profile",
    "artist": "Ava Anderson",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/558/800/1000",
    "likes": 5636,
    "views": 80296,
    "year": 2020,
    "style": "Digital Portrait"
  },
  {
    "id": 559,
    "title": "Found Soul",
    "artist": "Yuki Singh",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/559/800/1000",
    "likes": 7218,
    "views": 22305,
    "year": 2022,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 560,
    "title": "Dream Whisper",
    "artist": "William Martinez",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/560/800/1000",
    "likes": 6173,
    "views": 9868,
    "year": 2021,
    "style": "Fantasy Portrait"
  },
  {
    "id": 561,
    "title": "Found Muse",
    "artist": "Elijah Brown",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/561/800/1000",
    "likes": 3086,
    "views": 53774,
    "year": 2022,
    "style": "Male Portrait"
  },
  {
    "id": 562,
    "title": "Hopeful Shadow",
    "artist": "Isabella White",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/562/800/1000",
    "likes": 9423,
    "views": 41384,
    "year": 2022,
    "style": "Female Portrait"
  },
  {
    "id": 563,
    "title": "Broken Touch",
    "artist": "Oliver Martinez",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/563/800/1000",
    "likes": 4734,
    "views": 55703,
    "year": 2024,
    "style": "Creative Face Illustration"
  },
  {
    "id": 564,
    "title": "Radiant Smile",
    "artist": "Alexander Smith",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/564/800/1000",
    "likes": 3373,
    "views": 78710,
    "year": 2025,
    "style": "Pencil Portrait"
  },
  {
    "id": 565,
    "title": "Lost Stranger",
    "artist": "Ava Williams",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/565/800/1000",
    "likes": 173,
    "views": 48866,
    "year": 2025,
    "style": "Charcoal Portrait"
  },
  {
    "id": 566,
    "title": "Cold Eyes",
    "artist": "Liam Patel",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/566/800/1000",
    "likes": 3051,
    "views": 61358,
    "year": 2024,
    "style": "Watercolor Portrait"
  },
  {
    "id": 567,
    "title": "Fierce Expression",
    "artist": "Olivia Kim",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/567/800/1000",
    "likes": 9777,
    "views": 21277,
    "year": 2020,
    "style": "Digital Portrait"
  },
  {
    "id": 568,
    "title": "Pale Emotion",
    "artist": "Ethan Harris",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/568/800/1000",
    "likes": 4365,
    "views": 20499,
    "year": 2023,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 569,
    "title": "Fierce Emotion",
    "artist": "Mia Kim",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/569/800/1000",
    "likes": 6172,
    "views": 6055,
    "year": 2024,
    "style": "Fantasy Portrait"
  },
  {
    "id": 570,
    "title": "Mystic Face",
    "artist": "Sophia Johnson",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/570/800/1000",
    "likes": 1969,
    "views": 17396,
    "year": 2023,
    "style": "Male Portrait"
  },
  {
    "id": 571,
    "title": "Close Memory",
    "artist": "Mei Martinez",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/571/800/1000",
    "likes": 6367,
    "views": 91865,
    "year": 2021,
    "style": "Female Portrait"
  },
  {
    "id": 572,
    "title": "Warm Expression",
    "artist": "Oliver White",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/572/800/1000",
    "likes": 6331,
    "views": 61688,
    "year": 2021,
    "style": "Creative Face Illustration"
  },
  {
    "id": 573,
    "title": "Golden Shadow",
    "artist": "Amelia Kim",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/573/800/1000",
    "likes": 6746,
    "views": 1838,
    "year": 2022,
    "style": "Pencil Portrait"
  },
  {
    "id": 574,
    "title": "Dark Shadow",
    "artist": "Oliver Yamamoto",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/574/800/1000",
    "likes": 5937,
    "views": 31809,
    "year": 2021,
    "style": "Charcoal Portrait"
  },
  {
    "id": 575,
    "title": "Dream Moment",
    "artist": "Olivia Smith",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/575/800/1000",
    "likes": 4953,
    "views": 7574,
    "year": 2022,
    "style": "Watercolor Portrait"
  },
  {
    "id": 576,
    "title": "Found Touch",
    "artist": "Harper Okonkwo",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/576/800/1000",
    "likes": 8354,
    "views": 90050,
    "year": 2021,
    "style": "Digital Portrait"
  },
  {
    "id": 577,
    "title": "Silent Shadow",
    "artist": "Emily Jones",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/577/800/1000",
    "likes": 5376,
    "views": 59187,
    "year": 2020,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 578,
    "title": "Lost Profile",
    "artist": "Benjamin White",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/578/800/1000",
    "likes": 7068,
    "views": 87623,
    "year": 2022,
    "style": "Fantasy Portrait"
  },
  {
    "id": 579,
    "title": "Close Whisper",
    "artist": "Emma Tanaka",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/579/800/1000",
    "likes": 2137,
    "views": 28205,
    "year": 2025,
    "style": "Male Portrait"
  },
  {
    "id": 580,
    "title": "Mystic Tear",
    "artist": "Ava Singh",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/580/800/1000",
    "likes": 2165,
    "views": 24915,
    "year": 2024,
    "style": "Female Portrait"
  },
  {
    "id": 581,
    "title": "Vivid Moment",
    "artist": "William Martinez",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/581/800/1000",
    "likes": 8076,
    "views": 71372,
    "year": 2024,
    "style": "Creative Face Illustration"
  },
  {
    "id": 582,
    "title": "Cold Light",
    "artist": "Alexander Jackson",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/582/800/1000",
    "likes": 8357,
    "views": 31340,
    "year": 2024,
    "style": "Pencil Portrait"
  },
  {
    "id": 583,
    "title": "Warm Memory",
    "artist": "Ava Johnson",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/583/800/1000",
    "likes": 3342,
    "views": 12412,
    "year": 2021,
    "style": "Charcoal Portrait"
  },
  {
    "id": 584,
    "title": "Cold Secret",
    "artist": "Aiko Miller",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/584/800/1000",
    "likes": 9772,
    "views": 9169,
    "year": 2024,
    "style": "Watercolor Portrait"
  },
  {
    "id": 585,
    "title": "The Muse",
    "artist": "Priya Singh",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/585/800/1000",
    "likes": 9254,
    "views": 43590,
    "year": 2020,
    "style": "Digital Portrait"
  },
  {
    "id": 586,
    "title": "Close Expression",
    "artist": "Harper Williams",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/586/800/1000",
    "likes": 9113,
    "views": 32888,
    "year": 2023,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 587,
    "title": "Soul Touch",
    "artist": "Priya Brown",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/587/800/1000",
    "likes": 9748,
    "views": 99648,
    "year": 2024,
    "style": "Fantasy Portrait"
  },
  {
    "id": 588,
    "title": "Dark Smile",
    "artist": "Noah White",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/588/800/1000",
    "likes": 8124,
    "views": 33565,
    "year": 2020,
    "style": "Male Portrait"
  },
  {
    "id": 589,
    "title": "Gentle Expression",
    "artist": "Alexander Smith",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/589/800/1000",
    "likes": 3268,
    "views": 84289,
    "year": 2024,
    "style": "Female Portrait"
  },
  {
    "id": 590,
    "title": "Close Shadow",
    "artist": "Mia Okonkwo",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/590/800/1000",
    "likes": 8882,
    "views": 20724,
    "year": 2023,
    "style": "Creative Face Illustration"
  },
  {
    "id": 591,
    "title": "Lone Gaze",
    "artist": "William Jones",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/591/800/1000",
    "likes": 159,
    "views": 97266,
    "year": 2020,
    "style": "Pencil Portrait"
  },
  {
    "id": 592,
    "title": "The Voice",
    "artist": "Oliver Williams",
    "category": "Creative Portraits",
    "description": "Charcoal portrait capturing raw, unfiltered emotion and rich texture.",
    "image": "https://picsum.photos/id/592/800/1000",
    "likes": 6775,
    "views": 29353,
    "year": 2023,
    "style": "Charcoal Portrait"
  },
  {
    "id": 593,
    "title": "Lost Story",
    "artist": "Yuki Patel",
    "category": "Creative Portraits",
    "description": "Dreamy watercolor portrait with soft, bleeding colors and ethereal mood.",
    "image": "https://picsum.photos/id/593/800/1000",
    "likes": 7794,
    "views": 81506,
    "year": 2020,
    "style": "Watercolor Portrait"
  },
  {
    "id": 594,
    "title": "Hidden Light",
    "artist": "James Nguyen",
    "category": "Creative Portraits",
    "description": "Digital portrait with cinematic dramatic lighting and powerful mood.",
    "image": "https://picsum.photos/id/594/800/1000",
    "likes": 7772,
    "views": 84666,
    "year": 2021,
    "style": "Digital Portrait"
  },
  {
    "id": 595,
    "title": "Distant Smile",
    "artist": "Isabella Chen",
    "category": "Creative Portraits",
    "description": "Fantasy portrait with ethereal elements and otherworldly, timeless beauty.",
    "image": "https://picsum.photos/id/595/800/1000",
    "likes": 6402,
    "views": 33038,
    "year": 2024,
    "style": "Hyper Realistic Portrait"
  },
  {
    "id": 596,
    "title": "Found Voice",
    "artist": "Alexander Chen",
    "category": "Creative Portraits",
    "description": "Creative face illustration blending realism with abstract artistic freedom.",
    "image": "https://picsum.photos/id/596/800/1000",
    "likes": 9372,
    "views": 88049,
    "year": 2025,
    "style": "Fantasy Portrait"
  },
  {
    "id": 597,
    "title": "Soul Moment",
    "artist": "Isabella Yamamoto",
    "category": "Creative Portraits",
    "description": "Expressive portrait study capturing the inner soul of the subject.",
    "image": "https://picsum.photos/id/597/800/1000",
    "likes": 1738,
    "views": 72559,
    "year": 2023,
    "style": "Male Portrait"
  },
  {
    "id": 598,
    "title": "Pale Breath",
    "artist": "Harper Martinez",
    "category": "Creative Portraits",
    "description": "A striking female portrait with bold colors and confident composition.",
    "image": "https://picsum.photos/id/598/800/1000",
    "likes": 4766,
    "views": 62021,
    "year": 2021,
    "style": "Female Portrait"
  },
  {
    "id": 599,
    "title": "Gentle Tear",
    "artist": "Priya White",
    "category": "Creative Portraits",
    "description": "Male portrait with strong shadows and powerful emotional narrative.",
    "image": "https://picsum.photos/id/599/800/1000",
    "likes": 670,
    "views": 10066,
    "year": 2020,
    "style": "Creative Face Illustration"
  },
  {
    "id": 600,
    "title": "Pale Secret",
    "artist": "Olivia Patel",
    "category": "Creative Portraits",
    "description": "A hyper-realistic pencil portrait with extraordinary fine detail and depth.",
    "image": "https://picsum.photos/id/600/800/1000",
    "likes": 850,
    "views": 98079,
    "year": 2022,
    "style": "Pencil Portrait"
  }
];
