export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const digitalArts: GalleryArtwork[] = [
  {
    "id": 201,
    "title": "Galactic Grid",
    "artist": "Emily Okonkwo",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/201/800/1000",
    "likes": 4819,
    "views": 77607,
    "year": 2025,
    "style": "Digital Painting"
  },
  {
    "id": 202,
    "title": "Digital Frontier",
    "artist": "Emma Carter",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/202/800/1000",
    "likes": 9256,
    "views": 73861,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 203,
    "title": "Galactic Machine",
    "artist": "Olivia Yamamoto",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/203/800/1000",
    "likes": 519,
    "views": 28566,
    "year": 2021,
    "style": "Cyberpunk"
  },
  {
    "id": 204,
    "title": "Bi Samurai",
    "artist": "Isabella Okonkwo",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/204/800/1000",
    "likes": 3569,
    "views": 97729,
    "year": 2022,
    "style": "Sci-Fi"
  },
  {
    "id": 205,
    "title": "Ultra Pulse",
    "artist": "Harper Miller",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/205/800/1000",
    "likes": 4004,
    "views": 59401,
    "year": 2022,
    "style": "Fantasy Art"
  },
  {
    "id": 206,
    "title": "Omni Station",
    "artist": "Harper Singh",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/206/800/1000",
    "likes": 5170,
    "views": 60744,
    "year": 2025,
    "style": "Game Art"
  },
  {
    "id": 207,
    "title": "Synth Blade",
    "artist": "Sophia Johnson",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/207/800/1000",
    "likes": 8474,
    "views": 7366,
    "year": 2020,
    "style": "3D Illustration"
  },
  {
    "id": 208,
    "title": "Holo Samurai",
    "artist": "Yuki Harris",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/208/800/1000",
    "likes": 7695,
    "views": 67799,
    "year": 2022,
    "style": "Environment Art"
  },
  {
    "id": 209,
    "title": "Mega City",
    "artist": "Yuki Yamamoto",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/209/800/1000",
    "likes": 6865,
    "views": 62318,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 210,
    "title": "Galactic Machine",
    "artist": "Isabella Anderson",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/210/800/1000",
    "likes": 5177,
    "views": 53548,
    "year": 2024,
    "style": "Matte Painting"
  },
  {
    "id": 211,
    "title": "Mega Samurai",
    "artist": "Noah Rodriguez",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/211/800/1000",
    "likes": 6656,
    "views": 34474,
    "year": 2024,
    "style": "Neon Art"
  },
  {
    "id": 212,
    "title": "Astro Frontier",
    "artist": "Harper Brown",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/212/800/1000",
    "likes": 4986,
    "views": 36082,
    "year": 2020,
    "style": "Futuristic Art"
  },
  {
    "id": 213,
    "title": "Cosmic Dreams",
    "artist": "Alexander Chen",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/213/800/1000",
    "likes": 9921,
    "views": 12306,
    "year": 2025,
    "style": "Digital Painting"
  },
  {
    "id": 214,
    "title": "Mecha Gate",
    "artist": "Ava Davis",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/214/800/1000",
    "likes": 7255,
    "views": 54652,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 215,
    "title": "Holo Odyssey",
    "artist": "Mia Miller",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/215/800/1000",
    "likes": 193,
    "views": 48866,
    "year": 2021,
    "style": "Cyberpunk"
  },
  {
    "id": 216,
    "title": "Meta City",
    "artist": "Mia Okonkwo",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/216/800/1000",
    "likes": 412,
    "views": 4613,
    "year": 2021,
    "style": "Sci-Fi"
  },
  {
    "id": 217,
    "title": "Hyper Void",
    "artist": "Emily Taylor",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/217/800/1000",
    "likes": 8122,
    "views": 1903,
    "year": 2021,
    "style": "Fantasy Art"
  },
  {
    "id": 218,
    "title": "Future Matrix",
    "artist": "Isabella Patel",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/218/800/1000",
    "likes": 1392,
    "views": 5172,
    "year": 2025,
    "style": "Game Art"
  },
  {
    "id": 219,
    "title": "Quantum Signal",
    "artist": "Lucas Yamamoto",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/219/800/1000",
    "likes": 7488,
    "views": 85540,
    "year": 2021,
    "style": "3D Illustration"
  },
  {
    "id": 220,
    "title": "Infra Machine",
    "artist": "Oliver Jones",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/220/800/1000",
    "likes": 2583,
    "views": 66724,
    "year": 2024,
    "style": "Environment Art"
  },
  {
    "id": 221,
    "title": "Tri City",
    "artist": "Ava Jackson",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/221/800/1000",
    "likes": 6170,
    "views": 77110,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 222,
    "title": "Digital Blade",
    "artist": "Mia Miller",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/222/800/1000",
    "likes": 147,
    "views": 98077,
    "year": 2021,
    "style": "Matte Painting"
  },
  {
    "id": 223,
    "title": "Astro Warrior",
    "artist": "Noah Davis",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/223/800/1000",
    "likes": 7311,
    "views": 48199,
    "year": 2024,
    "style": "Neon Art"
  },
  {
    "id": 224,
    "title": "Proto Signal",
    "artist": "Rahul Rodriguez",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/224/800/1000",
    "likes": 4204,
    "views": 36761,
    "year": 2024,
    "style": "Futuristic Art"
  },
  {
    "id": 225,
    "title": "Mega Storm",
    "artist": "Charlotte Brown",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/225/800/1000",
    "likes": 6122,
    "views": 64411,
    "year": 2020,
    "style": "Digital Painting"
  },
  {
    "id": 226,
    "title": "Infra Void",
    "artist": "Ava Davis",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/226/800/1000",
    "likes": 6369,
    "views": 26335,
    "year": 2022,
    "style": "Concept Art"
  },
  {
    "id": 227,
    "title": "Mega Cyborg",
    "artist": "Ava Taylor",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/227/800/1000",
    "likes": 6643,
    "views": 94683,
    "year": 2025,
    "style": "Cyberpunk"
  },
  {
    "id": 228,
    "title": "Quantum Realm",
    "artist": "Priya Miller",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/228/800/1000",
    "likes": 486,
    "views": 95973,
    "year": 2025,
    "style": "Sci-Fi"
  },
  {
    "id": 229,
    "title": "Bi Link",
    "artist": "Oliver White",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/229/800/1000",
    "likes": 1985,
    "views": 12230,
    "year": 2022,
    "style": "Fantasy Art"
  },
  {
    "id": 230,
    "title": "Proto Void",
    "artist": "Alexander Thomas",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/230/800/1000",
    "likes": 7785,
    "views": 7565,
    "year": 2021,
    "style": "Game Art"
  },
  {
    "id": 231,
    "title": "Nova Zone",
    "artist": "William Taylor",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/231/800/1000",
    "likes": 267,
    "views": 4078,
    "year": 2025,
    "style": "3D Illustration"
  },
  {
    "id": 232,
    "title": "Cosmic Core",
    "artist": "Noah Davis",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/232/800/1000",
    "likes": 1930,
    "views": 58597,
    "year": 2022,
    "style": "Environment Art"
  },
  {
    "id": 233,
    "title": "Quantum Frontier",
    "artist": "Mei Williams",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/233/800/1000",
    "likes": 4248,
    "views": 52431,
    "year": 2023,
    "style": "Character Design"
  },
  {
    "id": 234,
    "title": "Tri Realm",
    "artist": "Liam Martinez",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/234/800/1000",
    "likes": 757,
    "views": 38981,
    "year": 2020,
    "style": "Matte Painting"
  },
  {
    "id": 235,
    "title": "Xeno Pulse",
    "artist": "Ethan White",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/235/800/1000",
    "likes": 6789,
    "views": 76910,
    "year": 2020,
    "style": "Neon Art"
  },
  {
    "id": 236,
    "title": "Astro Machine",
    "artist": "Sophia Taylor",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/236/800/1000",
    "likes": 6803,
    "views": 14784,
    "year": 2024,
    "style": "Futuristic Art"
  },
  {
    "id": 237,
    "title": "Xeno Storm",
    "artist": "Priya Chen",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/237/800/1000",
    "likes": 2783,
    "views": 18029,
    "year": 2021,
    "style": "Digital Painting"
  },
  {
    "id": 238,
    "title": "Nova Cyborg",
    "artist": "Emily White",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/238/800/1000",
    "likes": 7867,
    "views": 71096,
    "year": 2021,
    "style": "Concept Art"
  },
  {
    "id": 239,
    "title": "Ultra Samurai",
    "artist": "Elijah Rodriguez",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/239/800/1000",
    "likes": 2128,
    "views": 89710,
    "year": 2022,
    "style": "Cyberpunk"
  },
  {
    "id": 240,
    "title": "Mega Link",
    "artist": "Rahul Okonkwo",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/240/800/1000",
    "likes": 3548,
    "views": 58941,
    "year": 2023,
    "style": "Sci-Fi"
  },
  {
    "id": 241,
    "title": "Ultra Pulse",
    "artist": "Elijah Patel",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/241/800/1000",
    "likes": 2748,
    "views": 63523,
    "year": 2022,
    "style": "Fantasy Art"
  },
  {
    "id": 242,
    "title": "Holo Zone",
    "artist": "James Chen",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/242/800/1000",
    "likes": 7059,
    "views": 85196,
    "year": 2022,
    "style": "Game Art"
  },
  {
    "id": 243,
    "title": "Mecha Shield",
    "artist": "Sophia Taylor",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/243/800/1000",
    "likes": 3608,
    "views": 33063,
    "year": 2021,
    "style": "3D Illustration"
  },
  {
    "id": 244,
    "title": "Quantum Cyborg",
    "artist": "Mei Harris",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/244/800/1000",
    "likes": 9458,
    "views": 70175,
    "year": 2022,
    "style": "Environment Art"
  },
  {
    "id": 245,
    "title": "Techno Shield",
    "artist": "Priya White",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/245/800/1000",
    "likes": 6247,
    "views": 10905,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 246,
    "title": "Galactic Frontier",
    "artist": "Ethan Miller",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/246/800/1000",
    "likes": 3168,
    "views": 1787,
    "year": 2024,
    "style": "Matte Painting"
  },
  {
    "id": 247,
    "title": "Astro Samurai",
    "artist": "Charlotte Kim",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/247/800/1000",
    "likes": 4857,
    "views": 53768,
    "year": 2022,
    "style": "Neon Art"
  },
  {
    "id": 248,
    "title": "Synth Planet",
    "artist": "Ava Okonkwo",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/248/800/1000",
    "likes": 4956,
    "views": 24898,
    "year": 2020,
    "style": "Futuristic Art"
  },
  {
    "id": 249,
    "title": "Proto Core",
    "artist": "Yuki Davis",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/249/800/1000",
    "likes": 3504,
    "views": 89668,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 250,
    "title": "Mega Zone",
    "artist": "Mei Davis",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/250/800/1000",
    "likes": 3440,
    "views": 15341,
    "year": 2025,
    "style": "Concept Art"
  },
  {
    "id": 251,
    "title": "Meta Grid",
    "artist": "Aiko Harris",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/251/800/1000",
    "likes": 1138,
    "views": 10909,
    "year": 2021,
    "style": "Cyberpunk"
  },
  {
    "id": 252,
    "title": "Future Signal",
    "artist": "Alexander Johnson",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/252/800/1000",
    "likes": 5804,
    "views": 98244,
    "year": 2022,
    "style": "Sci-Fi"
  },
  {
    "id": 253,
    "title": "Proto Odyssey",
    "artist": "Isabella Kim",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/253/800/1000",
    "likes": 4839,
    "views": 14992,
    "year": 2024,
    "style": "Fantasy Art"
  },
  {
    "id": 254,
    "title": "Cosmic Planet",
    "artist": "Rahul Williams",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/254/800/1000",
    "likes": 3576,
    "views": 92164,
    "year": 2022,
    "style": "Game Art"
  },
  {
    "id": 255,
    "title": "Holo Frontier",
    "artist": "Harper Johnson",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/255/800/1000",
    "likes": 2482,
    "views": 95880,
    "year": 2024,
    "style": "3D Illustration"
  },
  {
    "id": 256,
    "title": "Cosmic Gate",
    "artist": "Emily Martinez",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/256/800/1000",
    "likes": 5105,
    "views": 49150,
    "year": 2022,
    "style": "Environment Art"
  },
  {
    "id": 257,
    "title": "Hyper Pulse",
    "artist": "Olivia Jones",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/257/800/1000",
    "likes": 3202,
    "views": 99723,
    "year": 2020,
    "style": "Character Design"
  },
  {
    "id": 258,
    "title": "Hyper Odyssey",
    "artist": "Aiko Jones",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/258/800/1000",
    "likes": 2241,
    "views": 77439,
    "year": 2020,
    "style": "Matte Painting"
  },
  {
    "id": 259,
    "title": "Mecha Blade",
    "artist": "James Harris",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/259/800/1000",
    "likes": 1998,
    "views": 37013,
    "year": 2020,
    "style": "Neon Art"
  },
  {
    "id": 260,
    "title": "Mecha Grid",
    "artist": "Ethan Kim",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/260/800/1000",
    "likes": 1300,
    "views": 72201,
    "year": 2025,
    "style": "Futuristic Art"
  },
  {
    "id": 261,
    "title": "Future Blade",
    "artist": "Priya Garcia",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/261/800/1000",
    "likes": 2035,
    "views": 72154,
    "year": 2020,
    "style": "Digital Painting"
  },
  {
    "id": 262,
    "title": "Infra Realm",
    "artist": "Ava Rodriguez",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/262/800/1000",
    "likes": 6948,
    "views": 16858,
    "year": 2025,
    "style": "Concept Art"
  },
  {
    "id": 263,
    "title": "Galactic Signal",
    "artist": "Mia Okonkwo",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/263/800/1000",
    "likes": 2720,
    "views": 70125,
    "year": 2020,
    "style": "Cyberpunk"
  },
  {
    "id": 264,
    "title": "Omni Odyssey",
    "artist": "Priya Tanaka",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/264/800/1000",
    "likes": 3316,
    "views": 10164,
    "year": 2022,
    "style": "Sci-Fi"
  },
  {
    "id": 265,
    "title": "Tri Dreams",
    "artist": "Rahul Martinez",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/265/800/1000",
    "likes": 9109,
    "views": 77300,
    "year": 2025,
    "style": "Fantasy Art"
  },
  {
    "id": 266,
    "title": "Xeno Core",
    "artist": "Harper Jackson",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/266/800/1000",
    "likes": 1333,
    "views": 26366,
    "year": 2021,
    "style": "Game Art"
  },
  {
    "id": 267,
    "title": "Cyber Machine",
    "artist": "Ethan Harris",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/267/800/1000",
    "likes": 1666,
    "views": 93783,
    "year": 2023,
    "style": "3D Illustration"
  },
  {
    "id": 268,
    "title": "Infra City",
    "artist": "Mei Harris",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/268/800/1000",
    "likes": 5128,
    "views": 61020,
    "year": 2023,
    "style": "Environment Art"
  },
  {
    "id": 269,
    "title": "Quantum Shield",
    "artist": "Sophia Yamamoto",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/269/800/1000",
    "likes": 8407,
    "views": 17577,
    "year": 2021,
    "style": "Character Design"
  },
  {
    "id": 270,
    "title": "Omni Machine",
    "artist": "Isabella Smith",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/270/800/1000",
    "likes": 6798,
    "views": 69051,
    "year": 2025,
    "style": "Matte Painting"
  },
  {
    "id": 271,
    "title": "Omni Frontier",
    "artist": "Mia Rodriguez",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/271/800/1000",
    "likes": 4264,
    "views": 96877,
    "year": 2023,
    "style": "Neon Art"
  },
  {
    "id": 272,
    "title": "Holo Cyborg",
    "artist": "Priya Thomas",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/272/800/1000",
    "likes": 5963,
    "views": 75980,
    "year": 2021,
    "style": "Futuristic Art"
  },
  {
    "id": 273,
    "title": "Proto Machine",
    "artist": "Alexander Carter",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/273/800/1000",
    "likes": 7869,
    "views": 49037,
    "year": 2023,
    "style": "Digital Painting"
  },
  {
    "id": 274,
    "title": "Meta Dreams",
    "artist": "Noah Nguyen",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/274/800/1000",
    "likes": 5048,
    "views": 46056,
    "year": 2022,
    "style": "Concept Art"
  },
  {
    "id": 275,
    "title": "Virtual Station",
    "artist": "Sophia Martinez",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/275/800/1000",
    "likes": 3624,
    "views": 52682,
    "year": 2021,
    "style": "Cyberpunk"
  },
  {
    "id": 276,
    "title": "Mega Matrix",
    "artist": "Oliver White",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/276/800/1000",
    "likes": 2987,
    "views": 68955,
    "year": 2022,
    "style": "Sci-Fi"
  },
  {
    "id": 277,
    "title": "Neon Machine",
    "artist": "Olivia Jones",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/277/800/1000",
    "likes": 8106,
    "views": 95550,
    "year": 2020,
    "style": "Fantasy Art"
  },
  {
    "id": 278,
    "title": "Quantum Pulse",
    "artist": "Isabella Smith",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/278/800/1000",
    "likes": 9856,
    "views": 70927,
    "year": 2025,
    "style": "Game Art"
  },
  {
    "id": 279,
    "title": "Mecha Link",
    "artist": "Emma Harris",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/279/800/1000",
    "likes": 1299,
    "views": 44326,
    "year": 2023,
    "style": "3D Illustration"
  },
  {
    "id": 280,
    "title": "Quantum Pulse",
    "artist": "Olivia Kim",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/280/800/1000",
    "likes": 8196,
    "views": 67441,
    "year": 2021,
    "style": "Environment Art"
  },
  {
    "id": 281,
    "title": "Nova Cyborg",
    "artist": "Harper Jackson",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/281/800/1000",
    "likes": 1329,
    "views": 2024,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 282,
    "title": "Future Dreams",
    "artist": "Liam Nguyen",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/282/800/1000",
    "likes": 3767,
    "views": 38198,
    "year": 2022,
    "style": "Matte Painting"
  },
  {
    "id": 283,
    "title": "Ultra Grid",
    "artist": "Emily Smith",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/283/800/1000",
    "likes": 3914,
    "views": 4846,
    "year": 2020,
    "style": "Neon Art"
  },
  {
    "id": 284,
    "title": "Quantum Void",
    "artist": "Benjamin Harris",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/284/800/1000",
    "likes": 9084,
    "views": 83452,
    "year": 2023,
    "style": "Futuristic Art"
  },
  {
    "id": 285,
    "title": "Ultra Pulse",
    "artist": "Yuki Kim",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/285/800/1000",
    "likes": 1343,
    "views": 88623,
    "year": 2021,
    "style": "Digital Painting"
  },
  {
    "id": 286,
    "title": "Omni Samurai",
    "artist": "Sophia Anderson",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/286/800/1000",
    "likes": 7365,
    "views": 15777,
    "year": 2022,
    "style": "Concept Art"
  },
  {
    "id": 287,
    "title": "Bi Odyssey",
    "artist": "William Thomas",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/287/800/1000",
    "likes": 306,
    "views": 40981,
    "year": 2022,
    "style": "Cyberpunk"
  },
  {
    "id": 288,
    "title": "Galactic Void",
    "artist": "Amelia Singh",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/288/800/1000",
    "likes": 545,
    "views": 54618,
    "year": 2022,
    "style": "Sci-Fi"
  },
  {
    "id": 289,
    "title": "Nano Warrior",
    "artist": "Benjamin Carter",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/289/800/1000",
    "likes": 8957,
    "views": 37684,
    "year": 2020,
    "style": "Fantasy Art"
  },
  {
    "id": 290,
    "title": "Ultra Pulse",
    "artist": "Isabella Miller",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/290/800/1000",
    "likes": 8075,
    "views": 33955,
    "year": 2022,
    "style": "Game Art"
  },
  {
    "id": 291,
    "title": "Virtual Nexus",
    "artist": "Priya Tanaka",
    "category": "Digital Arts",
    "description": "A gritty cyberpunk cityscape bathed in vivid neon lights and rain.",
    "image": "https://picsum.photos/id/291/800/1000",
    "likes": 565,
    "views": 32265,
    "year": 2021,
    "style": "3D Illustration"
  },
  {
    "id": 292,
    "title": "Digital Frontier",
    "artist": "James Taylor",
    "category": "Digital Arts",
    "description": "Futuristic sci-fi environment concept with extraordinary intricate detail.",
    "image": "https://picsum.photos/id/292/800/1000",
    "likes": 9235,
    "views": 31712,
    "year": 2020,
    "style": "Environment Art"
  },
  {
    "id": 293,
    "title": "Hyper Machine",
    "artist": "Alexander Martinez",
    "category": "Digital Arts",
    "description": "Fantasy world-building art with epic scale and immersive atmosphere.",
    "image": "https://picsum.photos/id/293/800/1000",
    "likes": 4584,
    "views": 86491,
    "year": 2022,
    "style": "Character Design"
  },
  {
    "id": 294,
    "title": "Infra Samurai",
    "artist": "Emily Rodriguez",
    "category": "Digital Arts",
    "description": "Game character design with bold colors and a powerful dynamic pose.",
    "image": "https://picsum.photos/id/294/800/1000",
    "likes": 6118,
    "views": 58391,
    "year": 2025,
    "style": "Matte Painting"
  },
  {
    "id": 295,
    "title": "Mecha Shield",
    "artist": "Lucas Taylor",
    "category": "Digital Arts",
    "description": "3D rendered matte painting depicting an alien world at dusk.",
    "image": "https://picsum.photos/id/295/800/1000",
    "likes": 3417,
    "views": 78664,
    "year": 2020,
    "style": "Neon Art"
  },
  {
    "id": 296,
    "title": "Bi Void",
    "artist": "Charlotte Martinez",
    "category": "Digital Arts",
    "description": "Digital painting with cinematic lighting and masterful composition.",
    "image": "https://picsum.photos/id/296/800/1000",
    "likes": 4011,
    "views": 20215,
    "year": 2022,
    "style": "Futuristic Art"
  },
  {
    "id": 297,
    "title": "Holo Frontier",
    "artist": "Sophia Williams",
    "category": "Digital Arts",
    "description": "Neon-drenched futuristic art with glowing elements and deep shadows.",
    "image": "https://picsum.photos/id/297/800/1000",
    "likes": 596,
    "views": 43463,
    "year": 2022,
    "style": "Digital Painting"
  },
  {
    "id": 298,
    "title": "Hyper Droid",
    "artist": "Emma Williams",
    "category": "Digital Arts",
    "description": "Concept art exploring a post-apocalyptic world with striking beauty.",
    "image": "https://picsum.photos/id/298/800/1000",
    "likes": 4509,
    "views": 42514,
    "year": 2025,
    "style": "Concept Art"
  },
  {
    "id": 299,
    "title": "Future Shield",
    "artist": "Elijah Jones",
    "category": "Digital Arts",
    "description": "Character design for a fantasy RPG with unique costume and personality.",
    "image": "https://picsum.photos/id/299/800/1000",
    "likes": 6387,
    "views": 12076,
    "year": 2021,
    "style": "Cyberpunk"
  },
  {
    "id": 300,
    "title": "Virtual Gate",
    "artist": "Sophia Okonkwo",
    "category": "Digital Arts",
    "description": "Environment art showing a sprawling megacity from a bird's-eye view.",
    "image": "https://picsum.photos/id/300/800/1000",
    "likes": 2256,
    "views": 4141,
    "year": 2021,
    "style": "Sci-Fi"
  }
];
