export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const digitalArts: GalleryArtwork[] = [
  {
    "id": 201,
    "title": "Vivid Bloom",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 7425,
    "views": 23964,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 202,
    "title": "Digital Bloom",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 4321,
    "views": 38512,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 203,
    "title": "Golden Portrait",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 2741,
    "views": 53830,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 204,
    "title": "Golden Gaze",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 9488,
    "views": 18740,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 205,
    "title": "Digital Vision",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 7987,
    "views": 35796,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 206,
    "title": "Neon Aura",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 1557,
    "views": 32411,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 207,
    "title": "Aesthetic Bloom",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 6368,
    "views": 24901,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 208,
    "title": "Golden Gaze",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 3207,
    "views": 53588,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 209,
    "title": "Aesthetic Light",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 7926,
    "views": 15306,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 210,
    "title": "Floral Dream",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 6165,
    "views": 27982,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 211,
    "title": "Floral Aura",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 1772,
    "views": 52557,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 212,
    "title": "Digital Aura",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 7244,
    "views": 36584,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 213,
    "title": "Neon Bloom",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 4139,
    "views": 54974,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 214,
    "title": "Golden Dream",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 8473,
    "views": 17338,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 215,
    "title": "Digital Dream",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 5443,
    "views": 27703,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 216,
    "title": "Golden Light",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 5760,
    "views": 12461,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 217,
    "title": "Mystic Dream",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 5539,
    "views": 39428,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 218,
    "title": "Golden Portrait",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 3070,
    "views": 47092,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 219,
    "title": "Mystic Dream",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 2731,
    "views": 26715,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 220,
    "title": "Digital Gaze",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 3668,
    "views": 20893,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 221,
    "title": "Silent Gaze",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 8927,
    "views": 25716,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 222,
    "title": "Aesthetic Portrait",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 7536,
    "views": 13400,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 223,
    "title": "Golden Dream",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 7620,
    "views": 44202,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 224,
    "title": "Mystic Dream",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 6716,
    "views": 24879,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 225,
    "title": "Digital Dream",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 2418,
    "views": 47710,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 226,
    "title": "Golden Bloom",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 3339,
    "views": 39271,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 227,
    "title": "Floral Portrait",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 3937,
    "views": 5792,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 228,
    "title": "Golden Aura",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 5553,
    "views": 53999,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 229,
    "title": "Vivid Portrait",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 7089,
    "views": 32737,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 230,
    "title": "Silent Portrait",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 1931,
    "views": 52151,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 231,
    "title": "Golden Aura",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 3234,
    "views": 44535,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 232,
    "title": "Mystic Light",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 3029,
    "views": 26936,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 233,
    "title": "Aesthetic Gaze",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 7918,
    "views": 6560,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 234,
    "title": "Aesthetic Portrait",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 2367,
    "views": 26111,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 235,
    "title": "Mystic Gaze",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 1581,
    "views": 20733,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 236,
    "title": "Floral Aura",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 2445,
    "views": 33428,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 237,
    "title": "Floral Aura",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 1969,
    "views": 52718,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 238,
    "title": "Neon Gaze",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 6506,
    "views": 13390,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 239,
    "title": "Neon Vision",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 4253,
    "views": 21652,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 240,
    "title": "Neon Bloom",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 2696,
    "views": 44572,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 241,
    "title": "Vivid Aura",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 4292,
    "views": 50955,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 242,
    "title": "Floral Light",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 6907,
    "views": 18160,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 243,
    "title": "Golden Gaze",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 2951,
    "views": 9433,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 244,
    "title": "Floral Dream",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 7559,
    "views": 29024,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 245,
    "title": "Silent Aura",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 9353,
    "views": 5164,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 246,
    "title": "Aesthetic Bloom",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 4527,
    "views": 44559,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 247,
    "title": "Silent Aura",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 3225,
    "views": 23469,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 248,
    "title": "Aesthetic Dream",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 8177,
    "views": 36119,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 249,
    "title": "Neon Gaze",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 3487,
    "views": 10429,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 250,
    "title": "Neon Bloom",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 4391,
    "views": 48486,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 251,
    "title": "Floral Vision",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 4626,
    "views": 32273,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 252,
    "title": "Vivid Portrait",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 5272,
    "views": 53943,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 253,
    "title": "Neon Gaze",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 5653,
    "views": 48611,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 254,
    "title": "Golden Bloom",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 1569,
    "views": 50333,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 255,
    "title": "Digital Light",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 2000,
    "views": 24114,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 256,
    "title": "Silent Light",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 7896,
    "views": 50518,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 257,
    "title": "Golden Bloom",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 3276,
    "views": 23657,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 258,
    "title": "Floral Dream",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 8717,
    "views": 42604,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 259,
    "title": "Digital Aura",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 1761,
    "views": 25020,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 260,
    "title": "Golden Aura",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 7679,
    "views": 15941,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 261,
    "title": "Silent Light",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 7706,
    "views": 37058,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 262,
    "title": "Aesthetic Aura",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 6710,
    "views": 49721,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 263,
    "title": "Mystic Portrait",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 7612,
    "views": 14565,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 264,
    "title": "Silent Bloom",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 3800,
    "views": 41371,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 265,
    "title": "Floral Portrait",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 1881,
    "views": 50989,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 266,
    "title": "Mystic Portrait",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 7630,
    "views": 50076,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 267,
    "title": "Golden Portrait",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 3214,
    "views": 45513,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 268,
    "title": "Golden Bloom",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 3842,
    "views": 48034,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 269,
    "title": "Silent Dream",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 4603,
    "views": 51850,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 270,
    "title": "Digital Vision",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 4470,
    "views": 16660,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 271,
    "title": "Golden Gaze",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 8052,
    "views": 10712,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 272,
    "title": "Silent Light",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 7844,
    "views": 6218,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 273,
    "title": "Silent Aura",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 2727,
    "views": 9159,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 274,
    "title": "Digital Vision",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 8171,
    "views": 11957,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 275,
    "title": "Vivid Portrait",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 1555,
    "views": 39796,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 276,
    "title": "Digital Gaze",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 5594,
    "views": 34178,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 277,
    "title": "Digital Vision",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 2439,
    "views": 16936,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 278,
    "title": "Neon Light",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 2931,
    "views": 5426,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 279,
    "title": "Digital Dream",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 2894,
    "views": 37050,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 280,
    "title": "Neon Gaze",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 8392,
    "views": 18343,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 281,
    "title": "Floral Bloom",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 5857,
    "views": 37829,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 282,
    "title": "Vivid Bloom",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 5506,
    "views": 10039,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 283,
    "title": "Mystic Aura",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 1589,
    "views": 49213,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 284,
    "title": "Silent Vision",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 4940,
    "views": 19249,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 285,
    "title": "Golden Vision",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 1525,
    "views": 26072,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 286,
    "title": "Vivid Aura",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 3355,
    "views": 37609,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 287,
    "title": "Golden Gaze",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 8449,
    "views": 24021,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 288,
    "title": "Digital Gaze",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 2066,
    "views": 10017,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 289,
    "title": "Silent Bloom",
    "artist": "Liam Smith",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 6316,
    "views": 26836,
    "year": 2024,
    "style": "Concept Art"
  },
  {
    "id": 290,
    "title": "Floral Portrait",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 3578,
    "views": 39783,
    "year": 2024,
    "style": "Digital Painting"
  },
  {
    "id": 291,
    "title": "Vivid Dream",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 8932,
    "views": 15350,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 292,
    "title": "Mystic Light",
    "artist": "Mia Martinez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 8233,
    "views": 12174,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 293,
    "title": "Aesthetic Bloom",
    "artist": "Ethan Jackson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 5148,
    "views": 44633,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 294,
    "title": "Golden Bloom",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 3404,
    "views": 38688,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 295,
    "title": "Golden Portrait",
    "artist": "Sofia Gonzalez",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/2.jpg",
    "likes": 2091,
    "views": 41868,
    "year": 2024,
    "style": "Character Design"
  },
  {
    "id": 296,
    "title": "Golden Bloom",
    "artist": "Aiko Tanaka",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/3.jpg",
    "likes": 4287,
    "views": 33764,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 297,
    "title": "Neon Aura",
    "artist": "Yuki Nakamura",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user1.png",
    "likes": 4421,
    "views": 47954,
    "year": 2024,
    "style": "Digital Illustration"
  },
  {
    "id": 298,
    "title": "Mystic Vision",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user2.png",
    "likes": 6331,
    "views": 33801,
    "year": 2024,
    "style": "Anime Aesthetic"
  },
  {
    "id": 299,
    "title": "Neon Bloom",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/user3.png",
    "likes": 4403,
    "views": 34733,
    "year": 2024,
    "style": "Pop Art"
  },
  {
    "id": 300,
    "title": "Digital Aura",
    "artist": "Olivia Johnson",
    "category": "Digital Arts",
    "description": "A stunning digital illustration with vibrant colors and beautiful stylized aesthetic.",
    "image": "/assets/gallery/digital/1.jpg",
    "likes": 2239,
    "views": 22043,
    "year": 2024,
    "style": "Digital Illustration"
  }
];
