export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const mandalaDesigns: GalleryArtwork[] = [
  {
    "id": 308,
    "title": "Lotus Harmony",
    "artist": "Sophia Carter",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP123180.jpg",
    "likes": 4782,
    "views": 93819,
    "year": 2024,
    "style": "Islamic Geometric Art"
  },
  {
    "id": 309,
    "title": "Golden Geometry",
    "artist": "Liam Smith",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP235240.jpg",
    "likes": 7207,
    "views": 70149,
    "year": 2023,
    "style": "Sacred Geometry"
  },
  {
    "id": 310,
    "title": "Inner Peace",
    "artist": "Olivia Johnson",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP235237.jpg",
    "likes": 7603,
    "views": 2502,
    "year": 2024,
    "style": "Mandala Art"
  },
  {
    "id": 311,
    "title": "Cosmic Mandala",
    "artist": "Noah Williams",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP240367.jpg",
    "likes": 6864,
    "views": 49674,
    "year": 2022,
    "style": "Geometric Mandala"
  },
  {
    "id": 312,
    "title": "Sacred Circle",
    "artist": "Emma Brown",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP170373.jpg",
    "likes": 7485,
    "views": 95551,
    "year": 2021,
    "style": "Tibetan Mandala"
  },
  {
    "id": 313,
    "title": "Floral Pattern",
    "artist": "Oliver Jones",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP247581.jpg",
    "likes": 2801,
    "views": 19303,
    "year": 2022,
    "style": "Lotus Mandala"
  },
  {
    "id": 314,
    "title": "Mystic Balance",
    "artist": "Ava Garcia",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP214312.jpg",
    "likes": 8949,
    "views": 7746,
    "year": 2023,
    "style": "Colorful Mandala"
  },
  {
    "id": 315,
    "title": "Zen Symmetry",
    "artist": "Elijah Miller",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP262928.jpg",
    "likes": 2200,
    "views": 87407,
    "year": 2024,
    "style": "Black Ink Mandala"
  },
  {
    "id": 316,
    "title": "Spiritual Bloom",
    "artist": "Isabella Davis",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP160115.jpg",
    "likes": 5682,
    "views": 80813,
    "year": 2020,
    "style": "Zentangle"
  },
  {
    "id": 317,
    "title": "Infinite Wheel",
    "artist": "William Rodriguez",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP367585.jpg",
    "likes": 7622,
    "views": 44520,
    "year": 2024,
    "style": "Arabesque Pattern"
  },
  {
    "id": 318,
    "title": "Divine Sun",
    "artist": "Mia Martinez",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP353091.jpg",
    "likes": 8278,
    "views": 59168,
    "year": 2021,
    "style": "Islamic Geometric Art"
  },
  {
    "id": 319,
    "title": "Radiant Flower",
    "artist": "James Hernandez",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP235239.jpg",
    "likes": 6972,
    "views": 78101,
    "year": 2020,
    "style": "Sacred Geometry"
  },
  {
    "id": 320,
    "title": "Ancient Labyrinth",
    "artist": "Amelia Taylor",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP235238.jpg",
    "likes": 5951,
    "views": 41164,
    "year": 2023,
    "style": "Mandala Art"
  },
  {
    "id": 321,
    "title": "Celestial Vortex",
    "artist": "Benjamin Anderson",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP259713.jpg",
    "likes": 2733,
    "views": 53983,
    "year": 2024,
    "style": "Geometric Mandala"
  },
  {
    "id": 322,
    "title": "Crystal Core",
    "artist": "Charlotte Thomas",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP245045.jpg",
    "likes": 3069,
    "views": 37656,
    "year": 2025,
    "style": "Tibetan Mandala"
  },
  {
    "id": 323,
    "title": "Lotus Geometry",
    "artist": "Ethan Jackson",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP170397.jpg",
    "likes": 4838,
    "views": 60436,
    "year": 2021,
    "style": "Lotus Mandala"
  },
  {
    "id": 324,
    "title": "Golden Peace",
    "artist": "Mansur",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP240655.jpg",
    "likes": 1622,
    "views": 9722,
    "year": 2020,
    "style": "Colorful Mandala"
  },
  {
    "id": 325,
    "title": "Inner Mandala",
    "artist": "Alexander Harris",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP230562.jpg",
    "likes": 5511,
    "views": 74638,
    "year": 2024,
    "style": "Black Ink Mandala"
  },
  {
    "id": 326,
    "title": "Cosmic Circle",
    "artist": "Harper Martin",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP230043.jpg",
    "likes": 1044,
    "views": 72137,
    "year": 2023,
    "style": "Zentangle"
  },
  {
    "id": 327,
    "title": "Sacred Pattern",
    "artist": "Lucas Thompson",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP-17257-001.jpg",
    "likes": 8407,
    "views": 6938,
    "year": 2021,
    "style": "Arabesque Pattern"
  },
  {
    "id": 328,
    "title": "Floral Balance",
    "artist": "Aiko Tanaka",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP253144.jpg",
    "likes": 8374,
    "views": 17304,
    "year": 2020,
    "style": "Islamic Geometric Art"
  },
  {
    "id": 329,
    "title": "Mystic Symmetry",
    "artist": "Yuki Nakamura",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP366351.jpg",
    "likes": 7123,
    "views": 32930,
    "year": 2025,
    "style": "Sacred Geometry"
  },
  {
    "id": 330,
    "title": "Zen Bloom",
    "artist": "Bichitr",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP234016.jpg",
    "likes": 474,
    "views": 33938,
    "year": 2020,
    "style": "Mandala Art"
  },
  {
    "id": 331,
    "title": "Spiritual Wheel",
    "artist": "Rahul Singh",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP123181.jpg",
    "likes": 5808,
    "views": 97587,
    "year": 2020,
    "style": "Geometric Mandala"
  },
  {
    "id": 332,
    "title": "Infinite Sun",
    "artist": "Mei Chen",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP170371.jpg",
    "likes": 3775,
    "views": 27308,
    "year": 2020,
    "style": "Tibetan Mandala"
  },
  {
    "id": 333,
    "title": "Divine Flower",
    "artist": "Diego Ramirez",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP230008.jpg",
    "likes": 998,
    "views": 71582,
    "year": 2021,
    "style": "Lotus Mandala"
  },
  {
    "id": 334,
    "title": "Radiant Labyrinth",
    "artist": "Li Jie",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-15820-005_crd.jpg",
    "likes": 2824,
    "views": 32473,
    "year": 2025,
    "style": "Colorful Mandala"
  },
  {
    "id": 335,
    "title": "Ancient Vortex",
    "artist": "Dai Benxiao",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP160517.jpg",
    "likes": 7059,
    "views": 47637,
    "year": 2024,
    "style": "Black Ink Mandala"
  },
  {
    "id": 336,
    "title": "Celestial Core",
    "artist": "Leila Hassan",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP212300.jpg",
    "likes": 9187,
    "views": 3928,
    "year": 2023,
    "style": "Zentangle"
  },
  {
    "id": 337,
    "title": "Crystal Harmony",
    "artist": "Marco Rossi",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP368497.jpg",
    "likes": 5361,
    "views": 49301,
    "year": 2024,
    "style": "Arabesque Pattern"
  },
  {
    "id": 338,
    "title": "Lotus Peace",
    "artist": "Sophia Carter",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP236373.jpg",
    "likes": 4117,
    "views": 79243,
    "year": 2025,
    "style": "Islamic Geometric Art"
  },
  {
    "id": 339,
    "title": "Golden Mandala",
    "artist": "Liam Smith",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP218716.jpg",
    "likes": 2860,
    "views": 51829,
    "year": 2020,
    "style": "Sacred Geometry"
  },
  {
    "id": 340,
    "title": "Inner Circle",
    "artist": "Olivia Johnson",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP227083.jpg",
    "likes": 4788,
    "views": 28782,
    "year": 2023,
    "style": "Mandala Art"
  },
  {
    "id": 341,
    "title": "Cosmic Pattern",
    "artist": "Noah Williams",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP217868.jpg",
    "likes": 2016,
    "views": 67232,
    "year": 2024,
    "style": "Geometric Mandala"
  },
  {
    "id": 342,
    "title": "Sacred Balance",
    "artist": "Emma Brown",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP120823.jpg",
    "likes": 9172,
    "views": 68207,
    "year": 2023,
    "style": "Tibetan Mandala"
  },
  {
    "id": 343,
    "title": "Floral Symmetry",
    "artist": "Oliver Jones",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP-17264-001.jpg",
    "likes": 9416,
    "views": 85093,
    "year": 2020,
    "style": "Lotus Mandala"
  },
  {
    "id": 344,
    "title": "Mystic Bloom",
    "artist": "Ibn Bakhtishu'",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP231330.jpg",
    "likes": 9242,
    "views": 38645,
    "year": 2024,
    "style": "Colorful Mandala"
  },
  {
    "id": 345,
    "title": "Zen Wheel",
    "artist": "Elijah Miller",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP235241.jpg",
    "likes": 4371,
    "views": 76581,
    "year": 2020,
    "style": "Black Ink Mandala"
  },
  {
    "id": 346,
    "title": "Spiritual Sun",
    "artist": "Isabella Davis",
    "category": "Mandala Designs",
    "description": "Beautiful mandala inspired by ancient geometric traditions of the East.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP170372.jpg",
    "likes": 1876,
    "views": 22086,
    "year": 2023,
    "style": "Zentangle"
  },
  {
    "id": 347,
    "title": "Infinite Flower",
    "artist": "Muhammad Qasim",
    "category": "Mandala Designs",
    "description": "Intricate circular pattern with mesmerizing layered geometric symmetry.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP152802.jpg",
    "likes": 234,
    "views": 23597,
    "year": 2025,
    "style": "Arabesque Pattern"
  },
  {
    "id": 348,
    "title": "Divine Labyrinth",
    "artist": "Mia Martinez",
    "category": "Mandala Designs",
    "description": "A stunning geometric artwork with perfect radial symmetry and intricate patterns.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP240048.jpg",
    "likes": 8904,
    "views": 15635,
    "year": 2024,
    "style": "Islamic Geometric Art"
  },
  {
    "id": 349,
    "title": "Radiant Vortex",
    "artist": "James Hernandez",
    "category": "Mandala Designs",
    "description": "Sacred geometric art radiating spiritual energy and meditative calm.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP212285.jpg",
    "likes": 9898,
    "views": 21068,
    "year": 2021,
    "style": "Sacred Geometry"
  },
  {
    "id": 350,
    "title": "Ancient Core",
    "artist": "Amelia Taylor",
    "category": "Mandala Designs",
    "description": "Detailed ornamental art featuring delicate symmetrical Islamic geometric designs.",
    "image": "https://images.metmuseum.org/CRDImages/is/web-large/DP230059.jpg",
    "likes": 8290,
    "views": 52238,
    "year": 2024,
    "style": "Mandala Art"
  }
];
