export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const mandalaDesigns: GalleryArtwork[] = [
  {
    "id": 401,
    "title": "Sacred Core",
    "artist": "Oliver Johnson",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/401/800/1000",
    "likes": 2431,
    "views": 49380,
    "year": 2023,
    "style": "Mandala Art"
  },
  {
    "id": 402,
    "title": "Lunar Mandala",
    "artist": "Harper Okonkwo",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/402/800/1000",
    "likes": 2274,
    "views": 72214,
    "year": 2022,
    "style": "Lotus Mandala"
  },
  {
    "id": 403,
    "title": "Peaceful Ring",
    "artist": "Lucas Taylor",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/403/800/1000",
    "likes": 8911,
    "views": 40506,
    "year": 2021,
    "style": "Circular Mandala"
  },
  {
    "id": 404,
    "title": "Radiant Crown",
    "artist": "Mei Rodriguez",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/404/800/1000",
    "likes": 3449,
    "views": 91081,
    "year": 2021,
    "style": "Geometric Mandala"
  },
  {
    "id": 405,
    "title": "Divine Peace",
    "artist": "Charlotte Kim",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/405/800/1000",
    "likes": 4718,
    "views": 58908,
    "year": 2024,
    "style": "Henna Mandala"
  },
  {
    "id": 406,
    "title": "Cosmic Mandala",
    "artist": "William Carter",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/406/800/1000",
    "likes": 7290,
    "views": 22024,
    "year": 2024,
    "style": "Sacred Geometry"
  },
  {
    "id": 407,
    "title": "Healing Web",
    "artist": "Priya Jones",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/407/800/1000",
    "likes": 7528,
    "views": 31279,
    "year": 2024,
    "style": "Colorful Mandala"
  },
  {
    "id": 408,
    "title": "Divine Mandala",
    "artist": "Lucas Anderson",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/408/800/1000",
    "likes": 9442,
    "views": 36852,
    "year": 2020,
    "style": "Black Ink Mandala"
  },
  {
    "id": 409,
    "title": "Crystal Web",
    "artist": "Amelia Brown",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/409/800/1000",
    "likes": 1423,
    "views": 82545,
    "year": 2025,
    "style": "Zentangle"
  },
  {
    "id": 410,
    "title": "Lunar Crown",
    "artist": "Yuki Singh",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/410/800/1000",
    "likes": 1106,
    "views": 68072,
    "year": 2021,
    "style": "Mandala Art"
  },
  {
    "id": 411,
    "title": "Infinite Geometry",
    "artist": "Priya Carter",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/411/800/1000",
    "likes": 7125,
    "views": 54731,
    "year": 2021,
    "style": "Lotus Mandala"
  },
  {
    "id": 412,
    "title": "Ancient Circle",
    "artist": "Priya Garcia",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/412/800/1000",
    "likes": 557,
    "views": 52975,
    "year": 2025,
    "style": "Circular Mandala"
  },
  {
    "id": 413,
    "title": "Celestial Halo",
    "artist": "Oliver Harris",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/413/800/1000",
    "likes": 3831,
    "views": 80565,
    "year": 2021,
    "style": "Geometric Mandala"
  },
  {
    "id": 414,
    "title": "Blooming Symmetry",
    "artist": "William Davis",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/414/800/1000",
    "likes": 3955,
    "views": 70346,
    "year": 2020,
    "style": "Henna Mandala"
  },
  {
    "id": 415,
    "title": "Lotus Focus",
    "artist": "Sophia Kim",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/415/800/1000",
    "likes": 7630,
    "views": 46641,
    "year": 2021,
    "style": "Sacred Geometry"
  },
  {
    "id": 416,
    "title": "Solar Mandala",
    "artist": "Ava Taylor",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/416/800/1000",
    "likes": 1446,
    "views": 54681,
    "year": 2023,
    "style": "Colorful Mandala"
  },
  {
    "id": 417,
    "title": "Glowing Sphere",
    "artist": "Olivia Tanaka",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/417/800/1000",
    "likes": 5274,
    "views": 23104,
    "year": 2022,
    "style": "Black Ink Mandala"
  },
  {
    "id": 418,
    "title": "Spiritual Focus",
    "artist": "Alexander Okonkwo",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/418/800/1000",
    "likes": 4730,
    "views": 56841,
    "year": 2020,
    "style": "Zentangle"
  },
  {
    "id": 419,
    "title": "Eternal Vortex",
    "artist": "Mia Patel",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/419/800/1000",
    "likes": 9054,
    "views": 47730,
    "year": 2020,
    "style": "Mandala Art"
  },
  {
    "id": 420,
    "title": "Peaceful Mandala",
    "artist": "Liam Tanaka",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/420/800/1000",
    "likes": 4284,
    "views": 65652,
    "year": 2023,
    "style": "Lotus Mandala"
  },
  {
    "id": 421,
    "title": "Sacred Halo",
    "artist": "Noah Tanaka",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/421/800/1000",
    "likes": 7102,
    "views": 83555,
    "year": 2025,
    "style": "Circular Mandala"
  },
  {
    "id": 422,
    "title": "Stellar Harmony",
    "artist": "Sophia Martinez",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/422/800/1000",
    "likes": 9051,
    "views": 44610,
    "year": 2022,
    "style": "Geometric Mandala"
  },
  {
    "id": 423,
    "title": "Glowing Wheel",
    "artist": "Isabella Carter",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/423/800/1000",
    "likes": 3036,
    "views": 66307,
    "year": 2022,
    "style": "Henna Mandala"
  },
  {
    "id": 424,
    "title": "Sacred Web",
    "artist": "Mia Carter",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/424/800/1000",
    "likes": 9221,
    "views": 49025,
    "year": 2025,
    "style": "Sacred Geometry"
  },
  {
    "id": 425,
    "title": "Lotus Crown",
    "artist": "Mia Yamamoto",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/425/800/1000",
    "likes": 9117,
    "views": 63282,
    "year": 2020,
    "style": "Colorful Mandala"
  },
  {
    "id": 426,
    "title": "Mystic Sphere",
    "artist": "Mia Jackson",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/426/800/1000",
    "likes": 6564,
    "views": 84784,
    "year": 2020,
    "style": "Black Ink Mandala"
  },
  {
    "id": 427,
    "title": "Mystic Pattern",
    "artist": "Elijah Harris",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/427/800/1000",
    "likes": 2067,
    "views": 77882,
    "year": 2025,
    "style": "Zentangle"
  },
  {
    "id": 428,
    "title": "Sacred Bloom",
    "artist": "James Smith",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/428/800/1000",
    "likes": 2878,
    "views": 21420,
    "year": 2021,
    "style": "Mandala Art"
  },
  {
    "id": 429,
    "title": "Eternal Aura",
    "artist": "Mia Martinez",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/429/800/1000",
    "likes": 2593,
    "views": 69643,
    "year": 2022,
    "style": "Lotus Mandala"
  },
  {
    "id": 430,
    "title": "Infinite Wheel",
    "artist": "Aiko Yamamoto",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/430/800/1000",
    "likes": 3778,
    "views": 95903,
    "year": 2024,
    "style": "Circular Mandala"
  },
  {
    "id": 431,
    "title": "Stellar Gate",
    "artist": "Amelia White",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/431/800/1000",
    "likes": 3836,
    "views": 77861,
    "year": 2022,
    "style": "Geometric Mandala"
  },
  {
    "id": 432,
    "title": "Crystal Crown",
    "artist": "Emma Kim",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/432/800/1000",
    "likes": 379,
    "views": 1083,
    "year": 2022,
    "style": "Henna Mandala"
  },
  {
    "id": 433,
    "title": "Floral Circle",
    "artist": "Elijah Williams",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/433/800/1000",
    "likes": 9606,
    "views": 63996,
    "year": 2020,
    "style": "Sacred Geometry"
  },
  {
    "id": 434,
    "title": "Glowing Flower",
    "artist": "Mei Davis",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/434/800/1000",
    "likes": 2777,
    "views": 85924,
    "year": 2023,
    "style": "Colorful Mandala"
  },
  {
    "id": 435,
    "title": "Cosmic Gate",
    "artist": "Ethan Kim",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/435/800/1000",
    "likes": 1122,
    "views": 24749,
    "year": 2025,
    "style": "Black Ink Mandala"
  },
  {
    "id": 436,
    "title": "Meditative Peace",
    "artist": "Emily Martinez",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/436/800/1000",
    "likes": 5137,
    "views": 35318,
    "year": 2025,
    "style": "Zentangle"
  },
  {
    "id": 437,
    "title": "Lunar Web",
    "artist": "Liam Williams",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/437/800/1000",
    "likes": 5678,
    "views": 77752,
    "year": 2020,
    "style": "Mandala Art"
  },
  {
    "id": 438,
    "title": "Cosmic Wheel",
    "artist": "Alexander Martinez",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/438/800/1000",
    "likes": 4708,
    "views": 65344,
    "year": 2024,
    "style": "Lotus Mandala"
  },
  {
    "id": 439,
    "title": "Radiant Peace",
    "artist": "Alexander Jones",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/439/800/1000",
    "likes": 3642,
    "views": 8480,
    "year": 2024,
    "style": "Circular Mandala"
  },
  {
    "id": 440,
    "title": "Lunar Crown",
    "artist": "Noah Jones",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/440/800/1000",
    "likes": 6295,
    "views": 84335,
    "year": 2022,
    "style": "Geometric Mandala"
  },
  {
    "id": 441,
    "title": "Crystal Harmony",
    "artist": "Rahul Miller",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/441/800/1000",
    "likes": 7189,
    "views": 70326,
    "year": 2021,
    "style": "Henna Mandala"
  },
  {
    "id": 442,
    "title": "Lunar Symmetry",
    "artist": "Emily Chen",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/442/800/1000",
    "likes": 6960,
    "views": 35149,
    "year": 2020,
    "style": "Sacred Geometry"
  },
  {
    "id": 443,
    "title": "Celestial Circle",
    "artist": "Olivia Jackson",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/443/800/1000",
    "likes": 5568,
    "views": 75901,
    "year": 2021,
    "style": "Colorful Mandala"
  },
  {
    "id": 444,
    "title": "Celestial Balance",
    "artist": "Aiko Martinez",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/444/800/1000",
    "likes": 7007,
    "views": 42090,
    "year": 2022,
    "style": "Black Ink Mandala"
  },
  {
    "id": 445,
    "title": "Glowing Wheel",
    "artist": "Alexander Nguyen",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/445/800/1000",
    "likes": 875,
    "views": 64674,
    "year": 2021,
    "style": "Zentangle"
  },
  {
    "id": 446,
    "title": "Golden Aura",
    "artist": "Sophia Garcia",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/446/800/1000",
    "likes": 2134,
    "views": 35678,
    "year": 2022,
    "style": "Mandala Art"
  },
  {
    "id": 447,
    "title": "Stellar Bloom",
    "artist": "Lucas Carter",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/447/800/1000",
    "likes": 391,
    "views": 78053,
    "year": 2025,
    "style": "Lotus Mandala"
  },
  {
    "id": 448,
    "title": "Meditative Harmony",
    "artist": "Yuki White",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/448/800/1000",
    "likes": 7983,
    "views": 15799,
    "year": 2021,
    "style": "Circular Mandala"
  },
  {
    "id": 449,
    "title": "Peaceful Energy",
    "artist": "Emma Rodriguez",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/449/800/1000",
    "likes": 8035,
    "views": 29768,
    "year": 2021,
    "style": "Geometric Mandala"
  },
  {
    "id": 450,
    "title": "Divine Balance",
    "artist": "Mei Tanaka",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/450/800/1000",
    "likes": 336,
    "views": 98032,
    "year": 2020,
    "style": "Henna Mandala"
  },
  {
    "id": 451,
    "title": "Lotus Focus",
    "artist": "Emma Jones",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/451/800/1000",
    "likes": 2047,
    "views": 71389,
    "year": 2025,
    "style": "Sacred Geometry"
  },
  {
    "id": 452,
    "title": "Golden Peace",
    "artist": "Liam Nguyen",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/452/800/1000",
    "likes": 7630,
    "views": 58006,
    "year": 2022,
    "style": "Colorful Mandala"
  },
  {
    "id": 453,
    "title": "Cosmic Wheel",
    "artist": "Amelia Miller",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/453/800/1000",
    "likes": 5596,
    "views": 19465,
    "year": 2023,
    "style": "Black Ink Mandala"
  },
  {
    "id": 454,
    "title": "Cosmic Sphere",
    "artist": "Noah Yamamoto",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/454/800/1000",
    "likes": 8465,
    "views": 80321,
    "year": 2022,
    "style": "Zentangle"
  },
  {
    "id": 455,
    "title": "Celestial Mandala",
    "artist": "Mei Singh",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/455/800/1000",
    "likes": 8558,
    "views": 85341,
    "year": 2021,
    "style": "Mandala Art"
  },
  {
    "id": 456,
    "title": "Infinite Pattern",
    "artist": "Aiko Brown",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/456/800/1000",
    "likes": 9431,
    "views": 4658,
    "year": 2020,
    "style": "Lotus Mandala"
  },
  {
    "id": 457,
    "title": "Infinite Vortex",
    "artist": "Noah Johnson",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/457/800/1000",
    "likes": 290,
    "views": 58812,
    "year": 2025,
    "style": "Circular Mandala"
  },
  {
    "id": 458,
    "title": "Eternal Geometry",
    "artist": "Alexander Garcia",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/458/800/1000",
    "likes": 565,
    "views": 71841,
    "year": 2025,
    "style": "Geometric Mandala"
  },
  {
    "id": 459,
    "title": "Blooming Mandala",
    "artist": "Charlotte Harris",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/459/800/1000",
    "likes": 7801,
    "views": 95495,
    "year": 2025,
    "style": "Henna Mandala"
  },
  {
    "id": 460,
    "title": "Solar Geometry",
    "artist": "Olivia Davis",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/460/800/1000",
    "likes": 6249,
    "views": 23058,
    "year": 2021,
    "style": "Sacred Geometry"
  },
  {
    "id": 461,
    "title": "Cosmic Mandala",
    "artist": "Emily Harris",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/461/800/1000",
    "likes": 1656,
    "views": 71604,
    "year": 2020,
    "style": "Colorful Mandala"
  },
  {
    "id": 462,
    "title": "Peaceful Geometry",
    "artist": "Lucas Davis",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/462/800/1000",
    "likes": 1213,
    "views": 8475,
    "year": 2021,
    "style": "Black Ink Mandala"
  },
  {
    "id": 463,
    "title": "Celestial Balance",
    "artist": "Alexander White",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/463/800/1000",
    "likes": 8517,
    "views": 78108,
    "year": 2021,
    "style": "Zentangle"
  },
  {
    "id": 464,
    "title": "Meditative Symmetry",
    "artist": "Mia Williams",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/464/800/1000",
    "likes": 6266,
    "views": 1238,
    "year": 2021,
    "style": "Mandala Art"
  },
  {
    "id": 465,
    "title": "Blooming Gate",
    "artist": "Liam Jackson",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/465/800/1000",
    "likes": 6515,
    "views": 26832,
    "year": 2025,
    "style": "Lotus Mandala"
  },
  {
    "id": 466,
    "title": "Spiritual Mandala",
    "artist": "Benjamin Miller",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/466/800/1000",
    "likes": 2426,
    "views": 90060,
    "year": 2024,
    "style": "Circular Mandala"
  },
  {
    "id": 467,
    "title": "Celestial Halo",
    "artist": "Noah Johnson",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/467/800/1000",
    "likes": 8107,
    "views": 62688,
    "year": 2024,
    "style": "Geometric Mandala"
  },
  {
    "id": 468,
    "title": "Tranquil Mandala",
    "artist": "Ethan Smith",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/468/800/1000",
    "likes": 1753,
    "views": 38260,
    "year": 2022,
    "style": "Henna Mandala"
  },
  {
    "id": 469,
    "title": "Sacred Balance",
    "artist": "Noah Brown",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/469/800/1000",
    "likes": 1895,
    "views": 92606,
    "year": 2024,
    "style": "Sacred Geometry"
  },
  {
    "id": 470,
    "title": "Mystic Focus",
    "artist": "Amelia Carter",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/470/800/1000",
    "likes": 5792,
    "views": 68369,
    "year": 2023,
    "style": "Colorful Mandala"
  },
  {
    "id": 471,
    "title": "Celestial Wheel",
    "artist": "William Brown",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/471/800/1000",
    "likes": 7910,
    "views": 24492,
    "year": 2023,
    "style": "Black Ink Mandala"
  },
  {
    "id": 472,
    "title": "Zen Pattern",
    "artist": "Priya Jones",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/472/800/1000",
    "likes": 1889,
    "views": 33493,
    "year": 2025,
    "style": "Zentangle"
  },
  {
    "id": 473,
    "title": "Stellar Ring",
    "artist": "Mia Harris",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/473/800/1000",
    "likes": 4025,
    "views": 95082,
    "year": 2024,
    "style": "Mandala Art"
  },
  {
    "id": 474,
    "title": "Mystic Vortex",
    "artist": "Benjamin Okonkwo",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/474/800/1000",
    "likes": 200,
    "views": 79967,
    "year": 2020,
    "style": "Lotus Mandala"
  },
  {
    "id": 475,
    "title": "Peaceful Flower",
    "artist": "Benjamin Jones",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/475/800/1000",
    "likes": 275,
    "views": 24104,
    "year": 2025,
    "style": "Circular Mandala"
  },
  {
    "id": 476,
    "title": "Healing Eye",
    "artist": "Emma Garcia",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/476/800/1000",
    "likes": 2757,
    "views": 55580,
    "year": 2022,
    "style": "Geometric Mandala"
  },
  {
    "id": 477,
    "title": "Crystal Gate",
    "artist": "James Tanaka",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/477/800/1000",
    "likes": 1216,
    "views": 44882,
    "year": 2022,
    "style": "Henna Mandala"
  },
  {
    "id": 478,
    "title": "Radiant Aura",
    "artist": "Liam Johnson",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/478/800/1000",
    "likes": 228,
    "views": 42000,
    "year": 2022,
    "style": "Sacred Geometry"
  },
  {
    "id": 479,
    "title": "Lotus Aura",
    "artist": "Emma Carter",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/479/800/1000",
    "likes": 8532,
    "views": 27164,
    "year": 2022,
    "style": "Colorful Mandala"
  },
  {
    "id": 480,
    "title": "Lotus Harmony",
    "artist": "Isabella Anderson",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/480/800/1000",
    "likes": 4245,
    "views": 41854,
    "year": 2020,
    "style": "Black Ink Mandala"
  },
  {
    "id": 481,
    "title": "Glowing Labyrinth",
    "artist": "Sophia Martinez",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/481/800/1000",
    "likes": 7911,
    "views": 33975,
    "year": 2021,
    "style": "Zentangle"
  },
  {
    "id": 482,
    "title": "Peaceful Harmony",
    "artist": "Amelia Smith",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/482/800/1000",
    "likes": 7935,
    "views": 27108,
    "year": 2022,
    "style": "Mandala Art"
  },
  {
    "id": 483,
    "title": "Solar Crown",
    "artist": "Priya Carter",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/483/800/1000",
    "likes": 6340,
    "views": 1759,
    "year": 2025,
    "style": "Lotus Mandala"
  },
  {
    "id": 484,
    "title": "Zen Geometry",
    "artist": "Yuki Martinez",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/484/800/1000",
    "likes": 941,
    "views": 8367,
    "year": 2025,
    "style": "Circular Mandala"
  },
  {
    "id": 485,
    "title": "Glowing Aura",
    "artist": "Benjamin Davis",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/485/800/1000",
    "likes": 9538,
    "views": 89554,
    "year": 2024,
    "style": "Geometric Mandala"
  },
  {
    "id": 486,
    "title": "Glowing Geometry",
    "artist": "Liam White",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/486/800/1000",
    "likes": 4048,
    "views": 98332,
    "year": 2020,
    "style": "Henna Mandala"
  },
  {
    "id": 487,
    "title": "Spiritual Peace",
    "artist": "Oliver Smith",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/487/800/1000",
    "likes": 9939,
    "views": 30163,
    "year": 2024,
    "style": "Sacred Geometry"
  },
  {
    "id": 488,
    "title": "Lunar Energy",
    "artist": "Harper Kim",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/488/800/1000",
    "likes": 1610,
    "views": 49083,
    "year": 2025,
    "style": "Colorful Mandala"
  },
  {
    "id": 489,
    "title": "Zen Flower",
    "artist": "Mia Smith",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/489/800/1000",
    "likes": 8501,
    "views": 9937,
    "year": 2025,
    "style": "Black Ink Mandala"
  },
  {
    "id": 490,
    "title": "Celestial Peace",
    "artist": "Elijah Kim",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/490/800/1000",
    "likes": 4085,
    "views": 29198,
    "year": 2021,
    "style": "Zentangle"
  },
  {
    "id": 491,
    "title": "Tranquil Energy",
    "artist": "Mei Anderson",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/491/800/1000",
    "likes": 8495,
    "views": 11438,
    "year": 2022,
    "style": "Mandala Art"
  },
  {
    "id": 492,
    "title": "Lotus Bloom",
    "artist": "Noah Thomas",
    "category": "Mandala Designs",
    "description": "Lotus-inspired mandala with delicately flowing petal patterns.",
    "image": "https://picsum.photos/id/492/800/1000",
    "likes": 3410,
    "views": 86357,
    "year": 2020,
    "style": "Lotus Mandala"
  },
  {
    "id": 493,
    "title": "Blooming Sun",
    "artist": "Ava Yamamoto",
    "category": "Mandala Designs",
    "description": "Sacred geometry mandala featuring intricate interlocking golden patterns.",
    "image": "https://picsum.photos/id/493/800/1000",
    "likes": 3404,
    "views": 13629,
    "year": 2024,
    "style": "Circular Mandala"
  },
  {
    "id": 494,
    "title": "Stellar Vortex",
    "artist": "Olivia Harris",
    "category": "Mandala Designs",
    "description": "Colorful mandala artwork radiating peace, joy, and spiritual harmony.",
    "image": "https://picsum.photos/id/494/800/1000",
    "likes": 3334,
    "views": 29307,
    "year": 2021,
    "style": "Geometric Mandala"
  },
  {
    "id": 495,
    "title": "Celestial Sphere",
    "artist": "Benjamin Carter",
    "category": "Mandala Designs",
    "description": "Black ink mandala with hand-drawn zentangle and fine ornamental details.",
    "image": "https://picsum.photos/id/495/800/1000",
    "likes": 8434,
    "views": 25071,
    "year": 2021,
    "style": "Henna Mandala"
  },
  {
    "id": 496,
    "title": "Divine Web",
    "artist": "Oliver Singh",
    "category": "Mandala Designs",
    "description": "Henna-inspired mandala design with delicate and intricate floral patterns.",
    "image": "https://picsum.photos/id/496/800/1000",
    "likes": 2501,
    "views": 45976,
    "year": 2021,
    "style": "Sacred Geometry"
  },
  {
    "id": 497,
    "title": "Radiant Bloom",
    "artist": "Emma Okonkwo",
    "category": "Mandala Designs",
    "description": "Meditative mandala artwork with calming circular symmetry patterns.",
    "image": "https://picsum.photos/id/497/800/1000",
    "likes": 244,
    "views": 61618,
    "year": 2022,
    "style": "Colorful Mandala"
  },
  {
    "id": 498,
    "title": "Meditative Eye",
    "artist": "Mia Davis",
    "category": "Mandala Designs",
    "description": "A vibrant multicolored mandala with complex layered geometric forms.",
    "image": "https://picsum.photos/id/498/800/1000",
    "likes": 3296,
    "views": 16361,
    "year": 2024,
    "style": "Black Ink Mandala"
  },
  {
    "id": 499,
    "title": "Eternal Sun",
    "artist": "James White",
    "category": "Mandala Designs",
    "description": "Zentangle mandala featuring organic patterns and mindful linework.",
    "image": "https://picsum.photos/id/499/800/1000",
    "likes": 8121,
    "views": 20369,
    "year": 2021,
    "style": "Zentangle"
  },
  {
    "id": 500,
    "title": "Healing Ring",
    "artist": "Alexander Tanaka",
    "category": "Mandala Designs",
    "description": "A geometric mandala with precise symmetry and perfect radial balance.",
    "image": "https://picsum.photos/id/500/800/1000",
    "likes": 5633,
    "views": 93685,
    "year": 2021,
    "style": "Mandala Art"
  }
];
