export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const traditionalArts: GalleryArtwork[] = [
  {
    "id": 101,
    "title": "Royal Heritage",
    "artist": "Zhang Yucai",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP213969_CRD.jpg",
    "likes": 9295,
    "views": 61783,
    "year": 2022,
    "style": "Madhubani"
  },
  {
    "id": 102,
    "title": "Ancient Dance",
    "artist": "Gong Xian",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP161003.jpg",
    "likes": 2765,
    "views": 26608,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 103,
    "title": "Sacred Festival",
    "artist": "Zhao Lingrang",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP165233_CRD.jpg",
    "likes": 3807,
    "views": 93006,
    "year": 2021,
    "style": "Pattachitra"
  },
  {
    "id": 104,
    "title": "Golden Temple",
    "artist": "Dong Qichang",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DT8375.jpg",
    "likes": 7630,
    "views": 53981,
    "year": 2022,
    "style": "Indian Folk Art"
  },
  {
    "id": 105,
    "title": "Divine Goddess",
    "artist": "Li Gonglin",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP151528.jpg",
    "likes": 2026,
    "views": 62345,
    "year": 2022,
    "style": "Miniature Painting"
  },
  {
    "id": 106,
    "title": "Classic Legend",
    "artist": "Oliver Jones",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP704960.jpg",
    "likes": 5303,
    "views": 27069,
    "year": 2023,
    "style": "Japanese Traditional"
  },
  {
    "id": 107,
    "title": "Heritage Pattern",
    "artist": "Chen Hongshou",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/1985_121_A_sf.jpg",
    "likes": 3467,
    "views": 58974,
    "year": 2020,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 108,
    "title": "Cultural Motif",
    "artist": "Unidentified artist",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP213003_CRD.jpg",
    "likes": 8846,
    "views": 13664,
    "year": 2020,
    "style": "Tibetan Thangka"
  },
  {
    "id": 109,
    "title": "Timeless Story",
    "artist": "Ike no Taiga",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP362631.jpg",
    "likes": 6954,
    "views": 37224,
    "year": 2023,
    "style": "African Tribal Art"
  },
  {
    "id": 110,
    "title": "Historic Myth",
    "artist": "Han Gan",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP153705.jpg",
    "likes": 7412,
    "views": 42275,
    "year": 2023,
    "style": "Persian Art"
  },
  {
    "id": 111,
    "title": "Spiritual Ritual",
    "artist": "Ju Jie",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-16369-002.jpg",
    "likes": 1962,
    "views": 48547,
    "year": 2025,
    "style": "Kalamkari"
  },
  {
    "id": 112,
    "title": "Traditional Village",
    "artist": "Gong Xian",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP154033.jpg",
    "likes": 2301,
    "views": 40545,
    "year": 2022,
    "style": "Madhubani"
  },
  {
    "id": 113,
    "title": "Festive Forest",
    "artist": "Dai Benxiao",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP160517.jpg",
    "likes": 2850,
    "views": 44059,
    "year": 2021,
    "style": "Warli"
  },
  {
    "id": 114,
    "title": "Blessed Mountain",
    "artist": "Xianyu Shu",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP230507_CRD.jpg",
    "likes": 3773,
    "views": 92321,
    "year": 2023,
    "style": "Pattachitra"
  },
  {
    "id": 115,
    "title": "Ornate Prayer",
    "artist": "Zhao Mengfu",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP375123_CRD.jpg",
    "likes": 6743,
    "views": 38079,
    "year": 2024,
    "style": "Indian Folk Art"
  },
  {
    "id": 116,
    "title": "Royal Dance",
    "artist": "Fang Congyi",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP213279_CRD.jpg",
    "likes": 9286,
    "views": 52738,
    "year": 2025,
    "style": "Miniature Painting"
  },
  {
    "id": 117,
    "title": "Ancient Festival",
    "artist": "Fan Qi",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP160995.jpg",
    "likes": 1457,
    "views": 47233,
    "year": 2021,
    "style": "Japanese Traditional"
  },
  {
    "id": 118,
    "title": "Sacred Temple",
    "artist": "Li Jie",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-15820-005_crd.jpg",
    "likes": 3200,
    "views": 82432,
    "year": 2024,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 119,
    "title": "Golden Goddess",
    "artist": "Emperor Huizong",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP151504_CRD.jpg",
    "likes": 4203,
    "views": 84092,
    "year": 2025,
    "style": "Tibetan Thangka"
  },
  {
    "id": 120,
    "title": "Divine Legend",
    "artist": "Wang Xuehao",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-42609-001.jpg",
    "likes": 2449,
    "views": 18183,
    "year": 2024,
    "style": "African Tribal Art"
  },
  {
    "id": 121,
    "title": "Classic Pattern",
    "artist": "Guo Xi",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP167812_CRD.jpg",
    "likes": 9899,
    "views": 49776,
    "year": 2025,
    "style": "Persian Art"
  },
  {
    "id": 122,
    "title": "Heritage Motif",
    "artist": "Gong Xian",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/1981_4_1a.jpg",
    "likes": 1721,
    "views": 53631,
    "year": 2024,
    "style": "Kalamkari"
  },
  {
    "id": 123,
    "title": "Cultural Story",
    "artist": "Sheng Maoye",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP160989.jpg",
    "likes": 2515,
    "views": 10810,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 124,
    "title": "Timeless Myth",
    "artist": "Ye Xin",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP153914.jpg",
    "likes": 1849,
    "views": 28441,
    "year": 2023,
    "style": "Warli"
  },
  {
    "id": 125,
    "title": "Historic Ritual",
    "artist": "Ichidon Shōzui",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-24140-002.jpg",
    "likes": 5623,
    "views": 41531,
    "year": 2025,
    "style": "Pattachitra"
  },
  {
    "id": 126,
    "title": "Spiritual Village",
    "artist": "Zhao Mengfu",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-24438-009.jpg",
    "likes": 5075,
    "views": 83940,
    "year": 2021,
    "style": "Indian Folk Art"
  },
  {
    "id": 127,
    "title": "Traditional Forest",
    "artist": "Yelü Chucai",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DT6277_CRD.jpg",
    "likes": 5705,
    "views": 26578,
    "year": 2022,
    "style": "Miniature Painting"
  },
  {
    "id": 128,
    "title": "Festive Mountain",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123259.jpg",
    "likes": 8359,
    "views": 15488,
    "year": 2020,
    "style": "Japanese Traditional"
  },
  {
    "id": 129,
    "title": "Blessed Prayer",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132836.jpg",
    "likes": 901,
    "views": 74739,
    "year": 2024,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 130,
    "title": "Ornate Heritage",
    "artist": "Katsushika Hokusai",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141247.jpg",
    "likes": 4405,
    "views": 69766,
    "year": 2021,
    "style": "Tibetan Thangka"
  },
  {
    "id": 131,
    "title": "Royal Festival",
    "artist": "Yōshū (Hashimoto) Chikanobu",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149363.jpg",
    "likes": 8012,
    "views": 22622,
    "year": 2024,
    "style": "African Tribal Art"
  },
  {
    "id": 132,
    "title": "Ancient Temple",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132861.jpg",
    "likes": 5570,
    "views": 92949,
    "year": 2021,
    "style": "Persian Art"
  },
  {
    "id": 133,
    "title": "Sacred Goddess",
    "artist": "Kitao Masanobu (Santō Kyōden) 北尾政演 (山東京伝)",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP319944_dup.jpg",
    "likes": 2254,
    "views": 23231,
    "year": 2021,
    "style": "Kalamkari"
  },
  {
    "id": 134,
    "title": "Golden Legend",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP120488.jpg",
    "likes": 8725,
    "views": 28462,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 135,
    "title": "Divine Pattern",
    "artist": "Utagawa Kunisada III",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP147663.jpg",
    "likes": 5374,
    "views": 2581,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 136,
    "title": "Classic Motif",
    "artist": "Ryūgetsusai Shinkō",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135903.jpg",
    "likes": 3514,
    "views": 54915,
    "year": 2023,
    "style": "Pattachitra"
  },
  {
    "id": 137,
    "title": "Heritage Story",
    "artist": "Yashima Gakutei",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP114887.jpg",
    "likes": 7834,
    "views": 36327,
    "year": 2022,
    "style": "Indian Folk Art"
  },
  {
    "id": 138,
    "title": "Cultural Myth",
    "artist": "Hishikawa Moronobu",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124582.jpg",
    "likes": 9316,
    "views": 27799,
    "year": 2021,
    "style": "Miniature Painting"
  },
  {
    "id": 139,
    "title": "Timeless Ritual",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122754.jpg",
    "likes": 1371,
    "views": 90842,
    "year": 2023,
    "style": "Japanese Traditional"
  },
  {
    "id": 140,
    "title": "Historic Village",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138856.jpg",
    "likes": 2224,
    "views": 66992,
    "year": 2025,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 141,
    "title": "Spiritual Forest",
    "artist": "Kitagawa Utamaro",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135625.jpg",
    "likes": 9260,
    "views": 52032,
    "year": 2021,
    "style": "Tibetan Thangka"
  },
  {
    "id": 142,
    "title": "Traditional Mountain",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132845.jpg",
    "likes": 8023,
    "views": 86713,
    "year": 2025,
    "style": "African Tribal Art"
  },
  {
    "id": 143,
    "title": "Festive Prayer",
    "artist": "Katsushika Hokusai",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141243.jpg",
    "likes": 5016,
    "views": 15522,
    "year": 2021,
    "style": "Persian Art"
  },
  {
    "id": 144,
    "title": "Blessed Dance",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP134575.jpg",
    "likes": 8178,
    "views": 8873,
    "year": 2021,
    "style": "Kalamkari"
  },
  {
    "id": 145,
    "title": "Ornate Festival",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132870.jpg",
    "likes": 3249,
    "views": 2997,
    "year": 2025,
    "style": "Madhubani"
  },
  {
    "id": 146,
    "title": "Royal Temple",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138238.jpg",
    "likes": 6603,
    "views": 25317,
    "year": 2024,
    "style": "Warli"
  },
  {
    "id": 147,
    "title": "Ancient Goddess",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122216.jpg",
    "likes": 2476,
    "views": 76174,
    "year": 2025,
    "style": "Pattachitra"
  },
  {
    "id": 148,
    "title": "Sacred Legend",
    "artist": "Torii Kiyonaga",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124186.jpg",
    "likes": 2014,
    "views": 6294,
    "year": 2024,
    "style": "Indian Folk Art"
  },
  {
    "id": 149,
    "title": "Golden Pattern",
    "artist": "Kubo Shunman 窪俊満",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135791.jpg",
    "likes": 951,
    "views": 53612,
    "year": 2021,
    "style": "Miniature Painting"
  },
  {
    "id": 150,
    "title": "Divine Motif",
    "artist": "Katsukawa Shun'ei 勝川春英",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP136890.jpg",
    "likes": 6784,
    "views": 70094,
    "year": 2024,
    "style": "Japanese Traditional"
  },
  {
    "id": 151,
    "title": "Classic Story",
    "artist": "Kubo Shunman",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138342.jpg",
    "likes": 8423,
    "views": 90434,
    "year": 2020,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 152,
    "title": "Heritage Myth",
    "artist": "Katsukawa Shunshō",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132862.jpg",
    "likes": 9190,
    "views": 49964,
    "year": 2022,
    "style": "Tibetan Thangka"
  },
  {
    "id": 153,
    "title": "Cultural Ritual",
    "artist": "Katsushika Hokusai",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141263.jpg",
    "likes": 4822,
    "views": 63866,
    "year": 2020,
    "style": "African Tribal Art"
  },
  {
    "id": 154,
    "title": "Timeless Village",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP120477.jpg",
    "likes": 2721,
    "views": 49660,
    "year": 2022,
    "style": "Persian Art"
  },
  {
    "id": 155,
    "title": "Historic Forest",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP121468.jpg",
    "likes": 3605,
    "views": 52658,
    "year": 2021,
    "style": "Kalamkari"
  },
  {
    "id": 156,
    "title": "Spiritual Mountain",
    "artist": "Furuyama Moroshige",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP130161.jpg",
    "likes": 9654,
    "views": 95595,
    "year": 2025,
    "style": "Madhubani"
  },
  {
    "id": 157,
    "title": "Traditional Prayer",
    "artist": "Utagawa Yoshitora",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP148076.jpg",
    "likes": 1650,
    "views": 93541,
    "year": 2022,
    "style": "Warli"
  },
  {
    "id": 158,
    "title": "Festive Heritage",
    "artist": "Isoda Koryūsai",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124222.jpg",
    "likes": 7917,
    "views": 60158,
    "year": 2023,
    "style": "Pattachitra"
  },
  {
    "id": 159,
    "title": "Blessed Dance",
    "artist": "Ishikawa Toyonobu",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135503.jpg",
    "likes": 4360,
    "views": 93589,
    "year": 2025,
    "style": "Indian Folk Art"
  },
  {
    "id": 160,
    "title": "Ornate Temple",
    "artist": "Yashima Gakutei",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP143404.jpg",
    "likes": 6823,
    "views": 73312,
    "year": 2022,
    "style": "Miniature Painting"
  },
  {
    "id": 161,
    "title": "Royal Goddess",
    "artist": "Tosen",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP147738.jpg",
    "likes": 300,
    "views": 91151,
    "year": 2021,
    "style": "Japanese Traditional"
  },
  {
    "id": 162,
    "title": "Ancient Legend",
    "artist": "Katsukawa Shunkō",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141320.jpg",
    "likes": 5756,
    "views": 5256,
    "year": 2022,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 163,
    "title": "Sacred Pattern",
    "artist": "Suzuki Harunobu",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP144642.jpg",
    "likes": 2065,
    "views": 64080,
    "year": 2024,
    "style": "Tibetan Thangka"
  },
  {
    "id": 164,
    "title": "Golden Motif",
    "artist": "Utagawa Yoshiiku",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP148078.jpg",
    "likes": 1382,
    "views": 30896,
    "year": 2022,
    "style": "African Tribal Art"
  },
  {
    "id": 165,
    "title": "Divine Story",
    "artist": "Tachibana Morikuni",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-13246-001.jpg",
    "likes": 8096,
    "views": 55775,
    "year": 2023,
    "style": "Persian Art"
  },
  {
    "id": 166,
    "title": "Classic Myth",
    "artist": "Nishimura Shigenobu",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP130265.jpg",
    "likes": 6204,
    "views": 76954,
    "year": 2025,
    "style": "Kalamkari"
  },
  {
    "id": 167,
    "title": "Heritage Ritual",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122178.jpg",
    "likes": 3820,
    "views": 45230,
    "year": 2025,
    "style": "Madhubani"
  },
  {
    "id": 168,
    "title": "Cultural Village",
    "artist": "Hishikawa Moronobu",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/JIB64_004_crd.jpg",
    "likes": 2330,
    "views": 56679,
    "year": 2022,
    "style": "Warli"
  },
  {
    "id": 169,
    "title": "Timeless Forest",
    "artist": "Katsukawa Shunshō　勝川春章",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP132755.jpg",
    "likes": 3005,
    "views": 88889,
    "year": 2024,
    "style": "Pattachitra"
  },
  {
    "id": 170,
    "title": "Historic Mountain",
    "artist": "Suzuki Harunobu",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP119503.jpg",
    "likes": 2729,
    "views": 40040,
    "year": 2024,
    "style": "Indian Folk Art"
  },
  {
    "id": 171,
    "title": "Spiritual Prayer",
    "artist": "Juka Sekijō",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149193.jpg",
    "likes": 3441,
    "views": 21460,
    "year": 2020,
    "style": "Miniature Painting"
  },
  {
    "id": 172,
    "title": "Traditional Dance",
    "artist": "Itō Jakuchū",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP143349.jpg",
    "likes": 8694,
    "views": 48495,
    "year": 2022,
    "style": "Japanese Traditional"
  },
  {
    "id": 173,
    "title": "Festive Temple",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123295.jpg",
    "likes": 639,
    "views": 6363,
    "year": 2024,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 174,
    "title": "Blessed Goddess",
    "artist": "Kitagawa Utamaro",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135636.jpg",
    "likes": 1183,
    "views": 74094,
    "year": 2021,
    "style": "Tibetan Thangka"
  },
  {
    "id": 175,
    "title": "Ornate Legend",
    "artist": "Nishimura Shigenaga",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP144568.jpg",
    "likes": 5977,
    "views": 95689,
    "year": 2022,
    "style": "African Tribal Art"
  },
  {
    "id": 176,
    "title": "Royal Pattern",
    "artist": "Kubo Shunman",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP139026.jpg",
    "likes": 5746,
    "views": 41613,
    "year": 2025,
    "style": "Persian Art"
  },
  {
    "id": 177,
    "title": "Ancient Motif",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123291.jpg",
    "likes": 3389,
    "views": 16545,
    "year": 2022,
    "style": "Kalamkari"
  },
  {
    "id": 178,
    "title": "Sacred Story",
    "artist": "Chōbunsai Eishi",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP142122.jpg",
    "likes": 2767,
    "views": 99295,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 179,
    "title": "Golden Myth",
    "artist": "Utagawa (Gountei) Sadahide",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP147960.jpg",
    "likes": 4889,
    "views": 92763,
    "year": 2025,
    "style": "Warli"
  },
  {
    "id": 180,
    "title": "Divine Ritual",
    "artist": "Okumura Masanobu",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP124501.jpg",
    "likes": 546,
    "views": 36556,
    "year": 2025,
    "style": "Pattachitra"
  },
  {
    "id": 181,
    "title": "Classic Village",
    "artist": "Utagawa Kunisada",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149026.jpg",
    "likes": 4353,
    "views": 93447,
    "year": 2025,
    "style": "Indian Folk Art"
  },
  {
    "id": 182,
    "title": "Heritage Forest",
    "artist": "Ippitsusai Bunchō",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP114918.jpg",
    "likes": 9825,
    "views": 9705,
    "year": 2022,
    "style": "Miniature Painting"
  },
  {
    "id": 183,
    "title": "Cultural Mountain",
    "artist": "Suzuki Harunobu",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP114928.jpg",
    "likes": 6179,
    "views": 10614,
    "year": 2020,
    "style": "Japanese Traditional"
  },
  {
    "id": 184,
    "title": "Timeless Prayer",
    "artist": "Kubo Shunman",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138969.jpg",
    "likes": 9338,
    "views": 29345,
    "year": 2020,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 185,
    "title": "Historic Dance",
    "artist": "Utagawa Kunisada",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP149040.jpg",
    "likes": 1634,
    "views": 61688,
    "year": 2024,
    "style": "Tibetan Thangka"
  },
  {
    "id": 186,
    "title": "Spiritual Festival",
    "artist": "Katsushika Hokusai 葛飾北斎",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/JIB83_004_crd.jpg",
    "likes": 6931,
    "views": 49745,
    "year": 2025,
    "style": "African Tribal Art"
  },
  {
    "id": 187,
    "title": "Traditional Temple",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP138947.jpg",
    "likes": 5031,
    "views": 19151,
    "year": 2022,
    "style": "Persian Art"
  },
  {
    "id": 188,
    "title": "Festive Goddess",
    "artist": "Utagawa Kuniyoshi",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP143375.jpg",
    "likes": 1062,
    "views": 5302,
    "year": 2025,
    "style": "Kalamkari"
  },
  {
    "id": 189,
    "title": "Blessed Legend",
    "artist": "Sengai Gibon 仙厓義梵",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_805_05_crd.jpg",
    "likes": 5720,
    "views": 21447,
    "year": 2022,
    "style": "Madhubani"
  },
  {
    "id": 190,
    "title": "Ornate Pattern",
    "artist": "Shibata Zeshin 柴田是真",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP142166.jpg",
    "likes": 9178,
    "views": 53322,
    "year": 2021,
    "style": "Warli"
  },
  {
    "id": 191,
    "title": "Royal Motif",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP122119.jpg",
    "likes": 5937,
    "views": 4520,
    "year": 2020,
    "style": "Pattachitra"
  },
  {
    "id": 192,
    "title": "Ancient Story",
    "artist": "Kitagawa Utamaro 喜多川歌麿",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/2013_852_a_b_a_04_crd.jpg",
    "likes": 9664,
    "views": 25046,
    "year": 2022,
    "style": "Indian Folk Art"
  },
  {
    "id": 193,
    "title": "Sacred Myth",
    "artist": "Suzuki Harunobu",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP119504.jpg",
    "likes": 2576,
    "views": 46424,
    "year": 2021,
    "style": "Miniature Painting"
  },
  {
    "id": 194,
    "title": "Golden Ritual",
    "artist": "Utagawa Hiroshige",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP123211.jpg",
    "likes": 3176,
    "views": 23752,
    "year": 2023,
    "style": "Japanese Traditional"
  },
  {
    "id": 195,
    "title": "Divine Village",
    "artist": "Katsushika Hokusai",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP141004.jpg",
    "likes": 1554,
    "views": 36641,
    "year": 2020,
    "style": "Chinese Ink Painting"
  },
  {
    "id": 196,
    "title": "Classic Forest",
    "artist": "Ryūryūkyo Shinsai",
    "category": "Traditional Arts",
    "description": "A beautiful traditional painting with intricate folk motifs and cultural symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135766.jpg",
    "likes": 3247,
    "views": 34617,
    "year": 2025,
    "style": "Tibetan Thangka"
  },
  {
    "id": 197,
    "title": "Heritage Mountain",
    "artist": "Utagawa Toyokuni II",
    "category": "Traditional Arts",
    "description": "Masterful traditional artwork depicting legends and mythological themes.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP135550.jpg",
    "likes": 8525,
    "views": 14343,
    "year": 2020,
    "style": "African Tribal Art"
  },
  {
    "id": 198,
    "title": "Cultural Prayer",
    "artist": "Torii Kiyonaga",
    "category": "Traditional Arts",
    "description": "Detailed miniature painting with vibrant pigments and ancient technique.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP130039.jpg",
    "likes": 6325,
    "views": 60144,
    "year": 2024,
    "style": "Persian Art"
  },
  {
    "id": 199,
    "title": "Timeless Dance",
    "artist": "Kubo Shunman",
    "category": "Traditional Arts",
    "description": "Heritage artwork preserving ancient artistic traditions and cultural stories.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP-14464-031.jpg",
    "likes": 7372,
    "views": 83343,
    "year": 2023,
    "style": "Kalamkari"
  },
  {
    "id": 200,
    "title": "Historic Temple",
    "artist": "Ishikawa Toyomasa",
    "category": "Traditional Arts",
    "description": "Exquisite traditional painting with intricate patterns and rich symbolism.",
    "image": "https://images.metmuseum.org/CRDImages/as/web-large/DP136935.jpg",
    "likes": 4012,
    "views": 91383,
    "year": 2024,
    "style": "Madhubani"
  }
];
