export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const traditionalArts: GalleryArtwork[] = [
  {
    "id": 101,
    "title": "Festive Madhubani",
    "artist": "Ethan Okonkwo",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/101/800/1000",
    "likes": 9033,
    "views": 95033,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 102,
    "title": "Rustic Folk",
    "artist": "Harper Brown",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/102/800/1000",
    "likes": 7966,
    "views": 53056,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 103,
    "title": "Golden Celebration",
    "artist": "Isabella Anderson",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/103/800/1000",
    "likes": 8320,
    "views": 65745,
    "year": 2021,
    "style": "Pattachitra"
  },
  {
    "id": 104,
    "title": "Spiritual Goddess",
    "artist": "Alexander Williams",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/104/800/1000",
    "likes": 229,
    "views": 65428,
    "year": 2022,
    "style": "Kalamkari"
  },
  {
    "id": 105,
    "title": "Heritage Pattern",
    "artist": "Charlotte Nguyen",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/105/800/1000",
    "likes": 241,
    "views": 44953,
    "year": 2020,
    "style": "Miniature Painting"
  },
  {
    "id": 106,
    "title": "Royal Madhubani",
    "artist": "Elijah Tanaka",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/106/800/1000",
    "likes": 7226,
    "views": 16410,
    "year": 2022,
    "style": "Tanjore Painting"
  },
  {
    "id": 107,
    "title": "Sacred Pattern",
    "artist": "Liam Thomas",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/107/800/1000",
    "likes": 9655,
    "views": 42082,
    "year": 2022,
    "style": "Indian Folk Art"
  },
  {
    "id": 108,
    "title": "Holy Kalamkari",
    "artist": "Isabella Brown",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/108/800/1000",
    "likes": 239,
    "views": 87926,
    "year": 2023,
    "style": "Chinese Ink Art"
  },
  {
    "id": 109,
    "title": "Vibrant Pattachitra",
    "artist": "Aiko Chen",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/109/800/1000",
    "likes": 8068,
    "views": 66707,
    "year": 2022,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 110,
    "title": "Timeless Myth",
    "artist": "William Taylor",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/110/800/1000",
    "likes": 8676,
    "views": 27056,
    "year": 2021,
    "style": "African Tribal Art"
  },
  {
    "id": 111,
    "title": "Traditional Myth",
    "artist": "William Carter",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/111/800/1000",
    "likes": 8935,
    "views": 63066,
    "year": 2025,
    "style": "Persian Traditional Art"
  },
  {
    "id": 112,
    "title": "Ethnic Dance",
    "artist": "James Brown",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/112/800/1000",
    "likes": 6342,
    "views": 94522,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 113,
    "title": "Tribal Motif",
    "artist": "Yuki Anderson",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/113/800/1000",
    "likes": 6517,
    "views": 48399,
    "year": 2022,
    "style": "Warli"
  },
  {
    "id": 114,
    "title": "Rustic Motif",
    "artist": "Ava Rodriguez",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/114/800/1000",
    "likes": 4819,
    "views": 24782,
    "year": 2022,
    "style": "Pattachitra"
  },
  {
    "id": 115,
    "title": "Vibrant Myth",
    "artist": "Benjamin Thomas",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/115/800/1000",
    "likes": 2257,
    "views": 77301,
    "year": 2020,
    "style": "Kalamkari"
  },
  {
    "id": 116,
    "title": "Sacred Folk",
    "artist": "James Nguyen",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/116/800/1000",
    "likes": 2184,
    "views": 73444,
    "year": 2025,
    "style": "Miniature Painting"
  },
  {
    "id": 117,
    "title": "Ethnic Folk",
    "artist": "William Martinez",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/117/800/1000",
    "likes": 9641,
    "views": 10171,
    "year": 2021,
    "style": "Tanjore Painting"
  },
  {
    "id": 118,
    "title": "Traditional Goddess",
    "artist": "Harper Garcia",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/118/800/1000",
    "likes": 5412,
    "views": 91737,
    "year": 2024,
    "style": "Indian Folk Art"
  },
  {
    "id": 119,
    "title": "Ethnic Legend",
    "artist": "Ava Johnson",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/119/800/1000",
    "likes": 6412,
    "views": 2314,
    "year": 2023,
    "style": "Chinese Ink Art"
  },
  {
    "id": 120,
    "title": "Folk Mountain",
    "artist": "Harper Martinez",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/120/800/1000",
    "likes": 329,
    "views": 50025,
    "year": 2020,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 121,
    "title": "Festive Story",
    "artist": "Rahul Rodriguez",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/121/800/1000",
    "likes": 8685,
    "views": 53224,
    "year": 2023,
    "style": "African Tribal Art"
  },
  {
    "id": 122,
    "title": "Traditional Pattern",
    "artist": "Rahul Garcia",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/122/800/1000",
    "likes": 4559,
    "views": 53463,
    "year": 2021,
    "style": "Persian Traditional Art"
  },
  {
    "id": 123,
    "title": "Rustic Harvest",
    "artist": "Lucas Chen",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/123/800/1000",
    "likes": 5846,
    "views": 47983,
    "year": 2021,
    "style": "Madhubani"
  },
  {
    "id": 124,
    "title": "Village Warli",
    "artist": "Mei Williams",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/124/800/1000",
    "likes": 500,
    "views": 46582,
    "year": 2021,
    "style": "Warli"
  },
  {
    "id": 125,
    "title": "Village Celebration",
    "artist": "Aiko Johnson",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/125/800/1000",
    "likes": 1698,
    "views": 76235,
    "year": 2025,
    "style": "Pattachitra"
  },
  {
    "id": 126,
    "title": "Divine Madhubani",
    "artist": "Mei Singh",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/126/800/1000",
    "likes": 7481,
    "views": 71590,
    "year": 2024,
    "style": "Kalamkari"
  },
  {
    "id": 127,
    "title": "Royal Tanjore",
    "artist": "Mia Taylor",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/127/800/1000",
    "likes": 6439,
    "views": 36013,
    "year": 2023,
    "style": "Miniature Painting"
  },
  {
    "id": 128,
    "title": "Timeless River",
    "artist": "Oliver Jones",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/128/800/1000",
    "likes": 9912,
    "views": 25840,
    "year": 2023,
    "style": "Tanjore Painting"
  },
  {
    "id": 129,
    "title": "Rustic Harvest",
    "artist": "Yuki Johnson",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/129/800/1000",
    "likes": 7547,
    "views": 26314,
    "year": 2021,
    "style": "Indian Folk Art"
  },
  {
    "id": 130,
    "title": "Divine Folk",
    "artist": "Liam Yamamoto",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/130/800/1000",
    "likes": 2204,
    "views": 37462,
    "year": 2022,
    "style": "Chinese Ink Art"
  },
  {
    "id": 131,
    "title": "Classic Ritual",
    "artist": "Aiko Patel",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/131/800/1000",
    "likes": 7981,
    "views": 18168,
    "year": 2024,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 132,
    "title": "Blessed Festival",
    "artist": "Alexander Smith",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/132/800/1000",
    "likes": 4388,
    "views": 7877,
    "year": 2025,
    "style": "African Tribal Art"
  },
  {
    "id": 133,
    "title": "Vibrant Goddess",
    "artist": "Mei Miller",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/133/800/1000",
    "likes": 8727,
    "views": 5874,
    "year": 2023,
    "style": "Persian Traditional Art"
  },
  {
    "id": 134,
    "title": "Mystic Kalamkari",
    "artist": "Benjamin Kim",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/134/800/1000",
    "likes": 5565,
    "views": 64874,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 135,
    "title": "Cultural Madhubani",
    "artist": "William Martinez",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/135/800/1000",
    "likes": 1422,
    "views": 77684,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 136,
    "title": "Timeless Forest",
    "artist": "Emily Martinez",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/136/800/1000",
    "likes": 5312,
    "views": 74164,
    "year": 2023,
    "style": "Pattachitra"
  },
  {
    "id": 137,
    "title": "Ethnic Krishna",
    "artist": "Alexander Anderson",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/137/800/1000",
    "likes": 3092,
    "views": 39460,
    "year": 2022,
    "style": "Kalamkari"
  },
  {
    "id": 138,
    "title": "Ethnic River",
    "artist": "Oliver Johnson",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/138/800/1000",
    "likes": 8953,
    "views": 60731,
    "year": 2023,
    "style": "Miniature Painting"
  },
  {
    "id": 139,
    "title": "Ethnic Forest",
    "artist": "Rahul Miller",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/139/800/1000",
    "likes": 3754,
    "views": 51521,
    "year": 2021,
    "style": "Tanjore Painting"
  },
  {
    "id": 140,
    "title": "Mystic Prayer",
    "artist": "Liam Yamamoto",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/140/800/1000",
    "likes": 7851,
    "views": 32833,
    "year": 2021,
    "style": "Indian Folk Art"
  },
  {
    "id": 141,
    "title": "Ornate Harvest",
    "artist": "Liam Anderson",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/141/800/1000",
    "likes": 5299,
    "views": 40943,
    "year": 2020,
    "style": "Chinese Ink Art"
  },
  {
    "id": 142,
    "title": "Classic Folk",
    "artist": "Ethan Thomas",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/142/800/1000",
    "likes": 5042,
    "views": 32887,
    "year": 2021,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 143,
    "title": "Timeless Ritual",
    "artist": "Rahul Williams",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/143/800/1000",
    "likes": 2536,
    "views": 89472,
    "year": 2020,
    "style": "African Tribal Art"
  },
  {
    "id": 144,
    "title": "Rustic Pattern",
    "artist": "James Harris",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/144/800/1000",
    "likes": 8312,
    "views": 48660,
    "year": 2020,
    "style": "Persian Traditional Art"
  },
  {
    "id": 145,
    "title": "Rustic Motif",
    "artist": "Yuki Nguyen",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/145/800/1000",
    "likes": 4324,
    "views": 27359,
    "year": 2021,
    "style": "Madhubani"
  },
  {
    "id": 146,
    "title": "Holy Forest",
    "artist": "William Martinez",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/146/800/1000",
    "likes": 2736,
    "views": 67702,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 147,
    "title": "Spiritual Goddess",
    "artist": "Amelia Garcia",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/147/800/1000",
    "likes": 8771,
    "views": 46143,
    "year": 2023,
    "style": "Pattachitra"
  },
  {
    "id": 148,
    "title": "Ornate Legend",
    "artist": "Emma White",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/148/800/1000",
    "likes": 9206,
    "views": 32751,
    "year": 2020,
    "style": "Kalamkari"
  },
  {
    "id": 149,
    "title": "Traditional Dance",
    "artist": "James Anderson",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/149/800/1000",
    "likes": 6946,
    "views": 21089,
    "year": 2020,
    "style": "Miniature Painting"
  },
  {
    "id": 150,
    "title": "Festive Story",
    "artist": "Isabella Jones",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/150/800/1000",
    "likes": 1504,
    "views": 1026,
    "year": 2024,
    "style": "Tanjore Painting"
  },
  {
    "id": 151,
    "title": "Mystic Festival",
    "artist": "Benjamin Taylor",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/151/800/1000",
    "likes": 9441,
    "views": 86912,
    "year": 2025,
    "style": "Indian Folk Art"
  },
  {
    "id": 152,
    "title": "Timeless River",
    "artist": "Mia Carter",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/152/800/1000",
    "likes": 4274,
    "views": 31222,
    "year": 2021,
    "style": "Chinese Ink Art"
  },
  {
    "id": 153,
    "title": "Festive Myth",
    "artist": "Rahul Smith",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/153/800/1000",
    "likes": 5280,
    "views": 17202,
    "year": 2024,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 154,
    "title": "Classic Festival",
    "artist": "Mei White",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/154/800/1000",
    "likes": 7805,
    "views": 22949,
    "year": 2024,
    "style": "African Tribal Art"
  },
  {
    "id": 155,
    "title": "Cultural Legend",
    "artist": "Mia Johnson",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/155/800/1000",
    "likes": 5267,
    "views": 41188,
    "year": 2020,
    "style": "Persian Traditional Art"
  },
  {
    "id": 156,
    "title": "Earthen River",
    "artist": "Oliver Miller",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/156/800/1000",
    "likes": 6611,
    "views": 51020,
    "year": 2024,
    "style": "Madhubani"
  },
  {
    "id": 157,
    "title": "Rustic Tanjore",
    "artist": "Noah Anderson",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/157/800/1000",
    "likes": 2335,
    "views": 5097,
    "year": 2024,
    "style": "Warli"
  },
  {
    "id": 158,
    "title": "Mystic Prayer",
    "artist": "Oliver Chen",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/158/800/1000",
    "likes": 1238,
    "views": 90533,
    "year": 2024,
    "style": "Pattachitra"
  },
  {
    "id": 159,
    "title": "Traditional Ritual",
    "artist": "Harper Kim",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/159/800/1000",
    "likes": 3318,
    "views": 74512,
    "year": 2024,
    "style": "Kalamkari"
  },
  {
    "id": 160,
    "title": "Ethnic Story",
    "artist": "Noah Anderson",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/160/800/1000",
    "likes": 8475,
    "views": 30870,
    "year": 2025,
    "style": "Miniature Painting"
  },
  {
    "id": 161,
    "title": "Sacred Madhubani",
    "artist": "Liam Smith",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/161/800/1000",
    "likes": 2584,
    "views": 74851,
    "year": 2022,
    "style": "Tanjore Painting"
  },
  {
    "id": 162,
    "title": "Tribal Ritual",
    "artist": "Priya Jackson",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/162/800/1000",
    "likes": 8398,
    "views": 13462,
    "year": 2023,
    "style": "Indian Folk Art"
  },
  {
    "id": 163,
    "title": "Spiritual Kalamkari",
    "artist": "Ava Miller",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/163/800/1000",
    "likes": 6932,
    "views": 24110,
    "year": 2022,
    "style": "Chinese Ink Art"
  },
  {
    "id": 164,
    "title": "Cultural River",
    "artist": "Charlotte Davis",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/164/800/1000",
    "likes": 2339,
    "views": 1286,
    "year": 2025,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 165,
    "title": "Village Ritual",
    "artist": "Mia White",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/165/800/1000",
    "likes": 8782,
    "views": 42545,
    "year": 2023,
    "style": "African Tribal Art"
  },
  {
    "id": 166,
    "title": "Sacred Legend",
    "artist": "Liam Patel",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/166/800/1000",
    "likes": 1865,
    "views": 41805,
    "year": 2025,
    "style": "Persian Traditional Art"
  },
  {
    "id": 167,
    "title": "Village Temple",
    "artist": "Yuki Garcia",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/167/800/1000",
    "likes": 7453,
    "views": 54094,
    "year": 2021,
    "style": "Madhubani"
  },
  {
    "id": 168,
    "title": "Earthen Krishna",
    "artist": "Rahul Yamamoto",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/168/800/1000",
    "likes": 503,
    "views": 15745,
    "year": 2023,
    "style": "Warli"
  },
  {
    "id": 169,
    "title": "Vibrant Folk",
    "artist": "Emily Martinez",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/169/800/1000",
    "likes": 888,
    "views": 46721,
    "year": 2022,
    "style": "Pattachitra"
  },
  {
    "id": 170,
    "title": "Earthen Temple",
    "artist": "Benjamin Smith",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/170/800/1000",
    "likes": 3663,
    "views": 47630,
    "year": 2021,
    "style": "Kalamkari"
  },
  {
    "id": 171,
    "title": "Sacred Story",
    "artist": "Oliver Yamamoto",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/171/800/1000",
    "likes": 1508,
    "views": 59852,
    "year": 2021,
    "style": "Miniature Painting"
  },
  {
    "id": 172,
    "title": "Earthen Tanjore",
    "artist": "Isabella Brown",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/172/800/1000",
    "likes": 9405,
    "views": 23950,
    "year": 2023,
    "style": "Tanjore Painting"
  },
  {
    "id": 173,
    "title": "Ornate Kalamkari",
    "artist": "William Anderson",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/173/800/1000",
    "likes": 9255,
    "views": 68656,
    "year": 2025,
    "style": "Indian Folk Art"
  },
  {
    "id": 174,
    "title": "Holy Folk",
    "artist": "Emily Kim",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/174/800/1000",
    "likes": 1297,
    "views": 72682,
    "year": 2022,
    "style": "Chinese Ink Art"
  },
  {
    "id": 175,
    "title": "Vibrant Harvest",
    "artist": "Lucas White",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/175/800/1000",
    "likes": 8190,
    "views": 30240,
    "year": 2025,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 176,
    "title": "Classic Krishna",
    "artist": "Benjamin Jones",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/176/800/1000",
    "likes": 4521,
    "views": 87487,
    "year": 2021,
    "style": "African Tribal Art"
  },
  {
    "id": 177,
    "title": "Traditional Forest",
    "artist": "Elijah Tanaka",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/177/800/1000",
    "likes": 6359,
    "views": 66472,
    "year": 2022,
    "style": "Persian Traditional Art"
  },
  {
    "id": 178,
    "title": "Tribal Myth",
    "artist": "James Carter",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/178/800/1000",
    "likes": 495,
    "views": 62101,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 179,
    "title": "Village Story",
    "artist": "Noah Martinez",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/179/800/1000",
    "likes": 9656,
    "views": 29718,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 180,
    "title": "Tribal Krishna",
    "artist": "William Rodriguez",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/180/800/1000",
    "likes": 1433,
    "views": 57674,
    "year": 2024,
    "style": "Pattachitra"
  },
  {
    "id": 181,
    "title": "Rustic Krishna",
    "artist": "Isabella Rodriguez",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/181/800/1000",
    "likes": 2781,
    "views": 61365,
    "year": 2023,
    "style": "Kalamkari"
  },
  {
    "id": 182,
    "title": "Spiritual Mountain",
    "artist": "Charlotte White",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/182/800/1000",
    "likes": 6816,
    "views": 70134,
    "year": 2025,
    "style": "Miniature Painting"
  },
  {
    "id": 183,
    "title": "Heritage Myth",
    "artist": "James Miller",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/183/800/1000",
    "likes": 904,
    "views": 68071,
    "year": 2020,
    "style": "Tanjore Painting"
  },
  {
    "id": 184,
    "title": "Sacred Folk",
    "artist": "Elijah Nguyen",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/184/800/1000",
    "likes": 9475,
    "views": 58552,
    "year": 2025,
    "style": "Indian Folk Art"
  },
  {
    "id": 185,
    "title": "Spiritual Madhubani",
    "artist": "Olivia Miller",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/185/800/1000",
    "likes": 5674,
    "views": 22276,
    "year": 2022,
    "style": "Chinese Ink Art"
  },
  {
    "id": 186,
    "title": "Blessed Festival",
    "artist": "Oliver Garcia",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/186/800/1000",
    "likes": 960,
    "views": 2527,
    "year": 2023,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 187,
    "title": "Sacred Legend",
    "artist": "Charlotte Jones",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/187/800/1000",
    "likes": 9815,
    "views": 51103,
    "year": 2021,
    "style": "African Tribal Art"
  },
  {
    "id": 188,
    "title": "Heritage Dance",
    "artist": "Emily Smith",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/188/800/1000",
    "likes": 2453,
    "views": 55951,
    "year": 2024,
    "style": "Persian Traditional Art"
  },
  {
    "id": 189,
    "title": "Golden Festival",
    "artist": "Benjamin Brown",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/189/800/1000",
    "likes": 9352,
    "views": 51913,
    "year": 2020,
    "style": "Madhubani"
  },
  {
    "id": 190,
    "title": "Blessed Motif",
    "artist": "Noah Jones",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/190/800/1000",
    "likes": 870,
    "views": 12921,
    "year": 2020,
    "style": "Warli"
  },
  {
    "id": 191,
    "title": "Holy Motif",
    "artist": "Priya Okonkwo",
    "category": "Traditional Arts",
    "description": "A traditional Madhubani painting with intricate folk motifs and geometric borders.",
    "image": "https://picsum.photos/id/191/800/1000",
    "likes": 3952,
    "views": 29705,
    "year": 2023,
    "style": "Pattachitra"
  },
  {
    "id": 192,
    "title": "Classic Madhubani",
    "artist": "Emily Chen",
    "category": "Traditional Arts",
    "description": "Warli art depicting everyday village life through simple geometric forms.",
    "image": "https://picsum.photos/id/192/800/1000",
    "likes": 4573,
    "views": 67910,
    "year": 2023,
    "style": "Kalamkari"
  },
  {
    "id": 193,
    "title": "Golden Forest",
    "artist": "Alexander Johnson",
    "category": "Traditional Arts",
    "description": "Pattachitra scroll painting narrating mythological themes and legends.",
    "image": "https://picsum.photos/id/193/800/1000",
    "likes": 2094,
    "views": 17756,
    "year": 2021,
    "style": "Miniature Painting"
  },
  {
    "id": 194,
    "title": "Timeless Madhubani",
    "artist": "Liam Williams",
    "category": "Traditional Arts",
    "description": "Kalamkari textile art with hand-painted floral and divine motifs.",
    "image": "https://picsum.photos/id/194/800/1000",
    "likes": 1641,
    "views": 2556,
    "year": 2025,
    "style": "Tanjore Painting"
  },
  {
    "id": 195,
    "title": "Blessed Prayer",
    "artist": "Ava Brown",
    "category": "Traditional Arts",
    "description": "A detailed miniature painting with vibrant natural pigments.",
    "image": "https://picsum.photos/id/195/800/1000",
    "likes": 4344,
    "views": 71301,
    "year": 2023,
    "style": "Indian Folk Art"
  },
  {
    "id": 196,
    "title": "Sacred Pattern",
    "artist": "Ethan Miller",
    "category": "Traditional Arts",
    "description": "Tanjore painting adorned with gold foil and precious stones.",
    "image": "https://picsum.photos/id/196/800/1000",
    "likes": 5581,
    "views": 56448,
    "year": 2022,
    "style": "Chinese Ink Art"
  },
  {
    "id": 197,
    "title": "Ritual Celebration",
    "artist": "Alexander Jones",
    "category": "Traditional Arts",
    "description": "Japanese sumi-e ink painting with serene landscape composition.",
    "image": "https://picsum.photos/id/197/800/1000",
    "likes": 8960,
    "views": 32797,
    "year": 2023,
    "style": "Japanese Traditional Painting"
  },
  {
    "id": 198,
    "title": "Vibrant Goddess",
    "artist": "Noah Jones",
    "category": "Traditional Arts",
    "description": "African tribal art celebrating cultural heritage through bold patterns.",
    "image": "https://picsum.photos/id/198/800/1000",
    "likes": 1928,
    "views": 42671,
    "year": 2024,
    "style": "African Tribal Art"
  },
  {
    "id": 199,
    "title": "Classic Mountain",
    "artist": "Mei Carter",
    "category": "Traditional Arts",
    "description": "Persian miniature art with intricate details and precious gold leaf.",
    "image": "https://picsum.photos/id/199/800/1000",
    "likes": 4786,
    "views": 21564,
    "year": 2020,
    "style": "Persian Traditional Art"
  },
  {
    "id": 200,
    "title": "Timeless Motif",
    "artist": "Yuki Garcia",
    "category": "Traditional Arts",
    "description": "Chinese ink painting with elegant calligraphic brushwork.",
    "image": "https://picsum.photos/id/200/800/1000",
    "likes": 2168,
    "views": 4149,
    "year": 2024,
    "style": "Madhubani"
  }
];
