export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const trendingArts: GalleryArtwork[] = [
  {
    "id": 1,
    "title": "Soft Motion",
    "artist": "Emily Garcia",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/1/800/1000",
    "likes": 4962,
    "views": 35688,
    "year": 2025,
    "style": "Modern Painting"
  },
  {
    "id": 2,
    "title": "Abstract Energy",
    "artist": "Yuki Davis",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/2/800/1000",
    "likes": 7872,
    "views": 88330,
    "year": 2020,
    "style": "Abstract Painting"
  },
  {
    "id": 3,
    "title": "Broken Tide",
    "artist": "Priya Anderson",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/3/800/1000",
    "likes": 5179,
    "views": 21021,
    "year": 2024,
    "style": "Oil Painting"
  },
  {
    "id": 4,
    "title": "Raw Symphony",
    "artist": "Aiko Harris",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/4/800/1000",
    "likes": 578,
    "views": 40021,
    "year": 2025,
    "style": "Canvas Art"
  },
  {
    "id": 5,
    "title": "Soft Surge",
    "artist": "Noah Brown",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/5/800/1000",
    "likes": 3062,
    "views": 34059,
    "year": 2023,
    "style": "Landscape Painting"
  },
  {
    "id": 6,
    "title": "Abstract Energy",
    "artist": "Charlotte Yamamoto",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/6/800/1000",
    "likes": 1799,
    "views": 53941,
    "year": 2021,
    "style": "Watercolor"
  },
  {
    "id": 7,
    "title": "Silent Vibe",
    "artist": "Emily Anderson",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/7/800/1000",
    "likes": 121,
    "views": 73066,
    "year": 2022,
    "style": "Creative Illustration"
  },
  {
    "id": 8,
    "title": "Raw Symphony",
    "artist": "Elijah Patel",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/8/800/1000",
    "likes": 4422,
    "views": 58284,
    "year": 2022,
    "style": "Street Art"
  },
  {
    "id": 9,
    "title": "Soft Wave",
    "artist": "Benjamin Patel",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/9/800/1000",
    "likes": 1177,
    "views": 70282,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 10,
    "title": "Mystic Flow",
    "artist": "Alexander Tanaka",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/10/800/1000",
    "likes": 5164,
    "views": 72772,
    "year": 2021,
    "style": "Mixed Media"
  },
  {
    "id": 11,
    "title": "Dense Vision",
    "artist": "Charlotte Martinez",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/11/800/1000",
    "likes": 7783,
    "views": 51059,
    "year": 2020,
    "style": "Modern Painting"
  },
  {
    "id": 12,
    "title": "Vibrant Echo",
    "artist": "Priya Singh",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/12/800/1000",
    "likes": 4174,
    "views": 46662,
    "year": 2022,
    "style": "Abstract Painting"
  },
  {
    "id": 13,
    "title": "Sunset Storm",
    "artist": "Alexander Chen",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/13/800/1000",
    "likes": 5896,
    "views": 56287,
    "year": 2025,
    "style": "Oil Painting"
  },
  {
    "id": 14,
    "title": "Sunset Journey",
    "artist": "Ava Miller",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/14/800/1000",
    "likes": 634,
    "views": 89810,
    "year": 2024,
    "style": "Canvas Art"
  },
  {
    "id": 15,
    "title": "Soft Journey",
    "artist": "Olivia Okonkwo",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/15/800/1000",
    "likes": 6881,
    "views": 28823,
    "year": 2020,
    "style": "Landscape Painting"
  },
  {
    "id": 16,
    "title": "Ocean Calm",
    "artist": "Harper Smith",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/16/800/1000",
    "likes": 7019,
    "views": 99459,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 17,
    "title": "Deep Explosion",
    "artist": "Benjamin Nguyen",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/17/800/1000",
    "likes": 2796,
    "views": 25290,
    "year": 2025,
    "style": "Creative Illustration"
  },
  {
    "id": 18,
    "title": "Ocean Form",
    "artist": "Elijah Singh",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/18/800/1000",
    "likes": 2619,
    "views": 13898,
    "year": 2020,
    "style": "Street Art"
  },
  {
    "id": 19,
    "title": "Deep Stillness",
    "artist": "Noah Brown",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/19/800/1000",
    "likes": 3727,
    "views": 63977,
    "year": 2024,
    "style": "Contemporary Art"
  },
  {
    "id": 20,
    "title": "Ocean Tide",
    "artist": "Priya Yamamoto",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/20/800/1000",
    "likes": 8397,
    "views": 87104,
    "year": 2021,
    "style": "Mixed Media"
  },
  {
    "id": 21,
    "title": "Wild Calm",
    "artist": "Aiko Kim",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/21/800/1000",
    "likes": 5937,
    "views": 64728,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 22,
    "title": "Silent Wave",
    "artist": "William Taylor",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/22/800/1000",
    "likes": 2978,
    "views": 65138,
    "year": 2025,
    "style": "Abstract Painting"
  },
  {
    "id": 23,
    "title": "Light Energy",
    "artist": "Mia Nguyen",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/23/800/1000",
    "likes": 7474,
    "views": 49349,
    "year": 2023,
    "style": "Oil Painting"
  },
  {
    "id": 24,
    "title": "Abstract Bloom",
    "artist": "Alexander Jackson",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/24/800/1000",
    "likes": 115,
    "views": 46695,
    "year": 2023,
    "style": "Canvas Art"
  },
  {
    "id": 25,
    "title": "Dark Vibe",
    "artist": "Rahul Taylor",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/25/800/1000",
    "likes": 4370,
    "views": 28247,
    "year": 2023,
    "style": "Landscape Painting"
  },
  {
    "id": 26,
    "title": "Silent Horizon",
    "artist": "Alexander Singh",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/26/800/1000",
    "likes": 6863,
    "views": 25428,
    "year": 2022,
    "style": "Watercolor"
  },
  {
    "id": 27,
    "title": "Broken Journey",
    "artist": "William Carter",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/27/800/1000",
    "likes": 4329,
    "views": 48666,
    "year": 2025,
    "style": "Creative Illustration"
  },
  {
    "id": 28,
    "title": "Eternal Journey",
    "artist": "Yuki Yamamoto",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/28/800/1000",
    "likes": 4096,
    "views": 28620,
    "year": 2020,
    "style": "Street Art"
  },
  {
    "id": 29,
    "title": "Wild Journey",
    "artist": "William Singh",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/29/800/1000",
    "likes": 9677,
    "views": 88902,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 30,
    "title": "Raw Vision",
    "artist": "James Johnson",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/30/800/1000",
    "likes": 5527,
    "views": 37376,
    "year": 2020,
    "style": "Mixed Media"
  },
  {
    "id": 31,
    "title": "Static Explosion",
    "artist": "Ethan Harris",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/31/800/1000",
    "likes": 2103,
    "views": 84536,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 32,
    "title": "Sunset Canvas",
    "artist": "Harper Miller",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/32/800/1000",
    "likes": 8127,
    "views": 3136,
    "year": 2021,
    "style": "Abstract Painting"
  },
  {
    "id": 33,
    "title": "Bold Mass",
    "artist": "Oliver Martinez",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/33/800/1000",
    "likes": 3529,
    "views": 75607,
    "year": 2021,
    "style": "Oil Painting"
  },
  {
    "id": 34,
    "title": "Wild Dreams",
    "artist": "James Yamamoto",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/34/800/1000",
    "likes": 4965,
    "views": 20313,
    "year": 2021,
    "style": "Canvas Art"
  },
  {
    "id": 35,
    "title": "Color Symphony",
    "artist": "Ethan Tanaka",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/35/800/1000",
    "likes": 6561,
    "views": 68387,
    "year": 2025,
    "style": "Landscape Painting"
  },
  {
    "id": 36,
    "title": "Wild Explosion",
    "artist": "Amelia Martinez",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/36/800/1000",
    "likes": 2029,
    "views": 34887,
    "year": 2024,
    "style": "Watercolor"
  },
  {
    "id": 37,
    "title": "Golden Storm",
    "artist": "Emma Brown",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/37/800/1000",
    "likes": 6933,
    "views": 25493,
    "year": 2022,
    "style": "Creative Illustration"
  },
  {
    "id": 38,
    "title": "Raw Layer",
    "artist": "Oliver Anderson",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/38/800/1000",
    "likes": 6651,
    "views": 38316,
    "year": 2025,
    "style": "Street Art"
  },
  {
    "id": 39,
    "title": "Eternal Symphony",
    "artist": "Emma Miller",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/39/800/1000",
    "likes": 9140,
    "views": 73373,
    "year": 2025,
    "style": "Contemporary Art"
  },
  {
    "id": 40,
    "title": "Dark Mass",
    "artist": "Oliver Smith",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/40/800/1000",
    "likes": 2501,
    "views": 3382,
    "year": 2022,
    "style": "Mixed Media"
  },
  {
    "id": 41,
    "title": "Urban Explosion",
    "artist": "Yuki Thomas",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/41/800/1000",
    "likes": 2704,
    "views": 66655,
    "year": 2023,
    "style": "Modern Painting"
  },
  {
    "id": 42,
    "title": "Modern Energy",
    "artist": "Priya Miller",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/42/800/1000",
    "likes": 6132,
    "views": 82561,
    "year": 2024,
    "style": "Abstract Painting"
  },
  {
    "id": 43,
    "title": "Dense Vision",
    "artist": "Olivia Miller",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/43/800/1000",
    "likes": 6180,
    "views": 64736,
    "year": 2025,
    "style": "Oil Painting"
  },
  {
    "id": 44,
    "title": "Soft Explosion",
    "artist": "Mei Taylor",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/44/800/1000",
    "likes": 9851,
    "views": 92247,
    "year": 2022,
    "style": "Canvas Art"
  },
  {
    "id": 45,
    "title": "Eternal Symphony",
    "artist": "Harper Harris",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/45/800/1000",
    "likes": 7949,
    "views": 58802,
    "year": 2022,
    "style": "Landscape Painting"
  },
  {
    "id": 46,
    "title": "Pure Mass",
    "artist": "Benjamin Okonkwo",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/46/800/1000",
    "likes": 7252,
    "views": 60436,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 47,
    "title": "Static Vision",
    "artist": "Yuki Harris",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/47/800/1000",
    "likes": 1300,
    "views": 67138,
    "year": 2021,
    "style": "Creative Illustration"
  },
  {
    "id": 48,
    "title": "Ocean Journey",
    "artist": "Harper Taylor",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/48/800/1000",
    "likes": 4291,
    "views": 85614,
    "year": 2024,
    "style": "Street Art"
  },
  {
    "id": 49,
    "title": "Dark Explosion",
    "artist": "Priya Anderson",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/49/800/1000",
    "likes": 6394,
    "views": 90174,
    "year": 2025,
    "style": "Contemporary Art"
  },
  {
    "id": 50,
    "title": "Bold Calm",
    "artist": "Yuki Okonkwo",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/50/800/1000",
    "likes": 4096,
    "views": 26579,
    "year": 2022,
    "style": "Mixed Media"
  },
  {
    "id": 51,
    "title": "Static Vibe",
    "artist": "Ava Kim",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/51/800/1000",
    "likes": 3524,
    "views": 12448,
    "year": 2021,
    "style": "Modern Painting"
  },
  {
    "id": 52,
    "title": "Pure Layer",
    "artist": "Mia Davis",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/52/800/1000",
    "likes": 1559,
    "views": 28634,
    "year": 2022,
    "style": "Abstract Painting"
  },
  {
    "id": 53,
    "title": "Neon Gust",
    "artist": "Yuki Martinez",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/53/800/1000",
    "likes": 4109,
    "views": 68005,
    "year": 2024,
    "style": "Oil Painting"
  },
  {
    "id": 54,
    "title": "Fluid Storm",
    "artist": "Liam Johnson",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/54/800/1000",
    "likes": 2638,
    "views": 48176,
    "year": 2021,
    "style": "Canvas Art"
  },
  {
    "id": 55,
    "title": "Dynamic Form",
    "artist": "Emma Johnson",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/55/800/1000",
    "likes": 3066,
    "views": 92284,
    "year": 2022,
    "style": "Landscape Painting"
  },
  {
    "id": 56,
    "title": "Wild Energy",
    "artist": "Olivia Chen",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/56/800/1000",
    "likes": 8353,
    "views": 52176,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 57,
    "title": "Dark Pulse",
    "artist": "Sophia Garcia",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/57/800/1000",
    "likes": 2480,
    "views": 61487,
    "year": 2023,
    "style": "Creative Illustration"
  },
  {
    "id": 58,
    "title": "Urban Layer",
    "artist": "Mia Yamamoto",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/58/800/1000",
    "likes": 3578,
    "views": 76558,
    "year": 2021,
    "style": "Street Art"
  },
  {
    "id": 59,
    "title": "Ocean Explosion",
    "artist": "Harper Tanaka",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/59/800/1000",
    "likes": 7265,
    "views": 56063,
    "year": 2023,
    "style": "Contemporary Art"
  },
  {
    "id": 60,
    "title": "Sunset Form",
    "artist": "Noah Thomas",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/60/800/1000",
    "likes": 1125,
    "views": 97001,
    "year": 2025,
    "style": "Mixed Media"
  },
  {
    "id": 61,
    "title": "Ocean Bloom",
    "artist": "Charlotte Thomas",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/61/800/1000",
    "likes": 3629,
    "views": 58369,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 62,
    "title": "Mystic Echo",
    "artist": "Liam Chen",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/62/800/1000",
    "likes": 5845,
    "views": 23801,
    "year": 2020,
    "style": "Abstract Painting"
  },
  {
    "id": 63,
    "title": "Ocean Echo",
    "artist": "Lucas Chen",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/63/800/1000",
    "likes": 4336,
    "views": 50243,
    "year": 2024,
    "style": "Oil Painting"
  },
  {
    "id": 64,
    "title": "Broken Horizon",
    "artist": "Priya Rodriguez",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/64/800/1000",
    "likes": 1858,
    "views": 34859,
    "year": 2024,
    "style": "Canvas Art"
  },
  {
    "id": 65,
    "title": "Ocean Mass",
    "artist": "Ethan Patel",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/65/800/1000",
    "likes": 3058,
    "views": 45796,
    "year": 2022,
    "style": "Landscape Painting"
  },
  {
    "id": 66,
    "title": "Urban Mass",
    "artist": "Isabella Johnson",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/66/800/1000",
    "likes": 3558,
    "views": 1865,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 67,
    "title": "Mystic Canvas",
    "artist": "Sophia Tanaka",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/67/800/1000",
    "likes": 443,
    "views": 7953,
    "year": 2024,
    "style": "Creative Illustration"
  },
  {
    "id": 68,
    "title": "Neon Vibe",
    "artist": "Yuki Williams",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/68/800/1000",
    "likes": 1551,
    "views": 98962,
    "year": 2022,
    "style": "Street Art"
  },
  {
    "id": 69,
    "title": "Broken Energy",
    "artist": "Rahul Harris",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/69/800/1000",
    "likes": 8653,
    "views": 72878,
    "year": 2021,
    "style": "Contemporary Art"
  },
  {
    "id": 70,
    "title": "Raw Symphony",
    "artist": "Mia Chen",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/70/800/1000",
    "likes": 1362,
    "views": 44479,
    "year": 2024,
    "style": "Mixed Media"
  },
  {
    "id": 71,
    "title": "Broken Wave",
    "artist": "James Davis",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/71/800/1000",
    "likes": 684,
    "views": 2421,
    "year": 2024,
    "style": "Modern Painting"
  },
  {
    "id": 72,
    "title": "Fluid Tide",
    "artist": "Elijah Williams",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/72/800/1000",
    "likes": 8168,
    "views": 13249,
    "year": 2024,
    "style": "Abstract Painting"
  },
  {
    "id": 73,
    "title": "Mystic Calm",
    "artist": "Alexander Singh",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/73/800/1000",
    "likes": 287,
    "views": 71575,
    "year": 2022,
    "style": "Oil Painting"
  },
  {
    "id": 74,
    "title": "Modern Gust",
    "artist": "Amelia Harris",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/74/800/1000",
    "likes": 6476,
    "views": 58794,
    "year": 2023,
    "style": "Canvas Art"
  },
  {
    "id": 75,
    "title": "Sunset Pulse",
    "artist": "Isabella Okonkwo",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/75/800/1000",
    "likes": 3539,
    "views": 58864,
    "year": 2021,
    "style": "Landscape Painting"
  },
  {
    "id": 76,
    "title": "Static Stillness",
    "artist": "Benjamin Davis",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/76/800/1000",
    "likes": 8618,
    "views": 57145,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 77,
    "title": "Ocean Echo",
    "artist": "Noah Taylor",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/77/800/1000",
    "likes": 3122,
    "views": 53164,
    "year": 2021,
    "style": "Creative Illustration"
  },
  {
    "id": 78,
    "title": "Neon Rush",
    "artist": "Harper Chen",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/78/800/1000",
    "likes": 7185,
    "views": 58932,
    "year": 2023,
    "style": "Street Art"
  },
  {
    "id": 79,
    "title": "Dense Explosion",
    "artist": "Emma Kim",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/79/800/1000",
    "likes": 9107,
    "views": 82855,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 80,
    "title": "Abstract Stillness",
    "artist": "Noah Rodriguez",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/80/800/1000",
    "likes": 2939,
    "views": 59615,
    "year": 2025,
    "style": "Mixed Media"
  },
  {
    "id": 81,
    "title": "Wild Journey",
    "artist": "Alexander Singh",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/81/800/1000",
    "likes": 989,
    "views": 70304,
    "year": 2023,
    "style": "Modern Painting"
  },
  {
    "id": 82,
    "title": "Sunset Surge",
    "artist": "Liam Anderson",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/82/800/1000",
    "likes": 7733,
    "views": 88890,
    "year": 2024,
    "style": "Abstract Painting"
  },
  {
    "id": 83,
    "title": "Urban Symphony",
    "artist": "William Johnson",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/83/800/1000",
    "likes": 739,
    "views": 57803,
    "year": 2021,
    "style": "Oil Painting"
  },
  {
    "id": 84,
    "title": "Eternal Vision",
    "artist": "Mei White",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/84/800/1000",
    "likes": 4748,
    "views": 92371,
    "year": 2024,
    "style": "Canvas Art"
  },
  {
    "id": 85,
    "title": "Sunset Flow",
    "artist": "Yuki Nguyen",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/85/800/1000",
    "likes": 2046,
    "views": 36901,
    "year": 2023,
    "style": "Landscape Painting"
  },
  {
    "id": 86,
    "title": "Mystic Explosion",
    "artist": "Benjamin Nguyen",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/86/800/1000",
    "likes": 6636,
    "views": 52421,
    "year": 2022,
    "style": "Watercolor"
  },
  {
    "id": 87,
    "title": "Color Stillness",
    "artist": "Alexander Brown",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/87/800/1000",
    "likes": 9013,
    "views": 46675,
    "year": 2023,
    "style": "Creative Illustration"
  },
  {
    "id": 88,
    "title": "Soft Vision",
    "artist": "Liam Tanaka",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/88/800/1000",
    "likes": 5416,
    "views": 33160,
    "year": 2022,
    "style": "Street Art"
  },
  {
    "id": 89,
    "title": "Golden Pulse",
    "artist": "Lucas Kim",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/89/800/1000",
    "likes": 1294,
    "views": 35896,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 90,
    "title": "Soft Tide",
    "artist": "Emily Smith",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/90/800/1000",
    "likes": 6143,
    "views": 89092,
    "year": 2022,
    "style": "Mixed Media"
  },
  {
    "id": 91,
    "title": "Soft Dreams",
    "artist": "Noah Yamamoto",
    "category": "Trending Arts",
    "description": "A vibrant modern abstract painting bursting with color and dynamic energy.",
    "image": "https://picsum.photos/id/91/800/1000",
    "likes": 653,
    "views": 79775,
    "year": 2024,
    "style": "Modern Painting"
  },
  {
    "id": 92,
    "title": "Dense Horizon",
    "artist": "James Singh",
    "category": "Trending Arts",
    "description": "Contemporary oil painting with rich textures and bold, expressive brushstrokes.",
    "image": "https://picsum.photos/id/92/800/1000",
    "likes": 9343,
    "views": 42766,
    "year": 2021,
    "style": "Abstract Painting"
  },
  {
    "id": 93,
    "title": "Abstract Layer",
    "artist": "William Patel",
    "category": "Trending Arts",
    "description": "An expressive watercolor piece exploring the interplay of light and shadow.",
    "image": "https://picsum.photos/id/93/800/1000",
    "likes": 7172,
    "views": 31225,
    "year": 2025,
    "style": "Oil Painting"
  },
  {
    "id": 94,
    "title": "Silent Vibe",
    "artist": "Ethan Miller",
    "category": "Trending Arts",
    "description": "Mixed media artwork combining photography, paint, and illustration techniques.",
    "image": "https://picsum.photos/id/94/800/1000",
    "likes": 9253,
    "views": 71822,
    "year": 2023,
    "style": "Canvas Art"
  },
  {
    "id": 95,
    "title": "Sunset Horizon",
    "artist": "Elijah Garcia",
    "category": "Trending Arts",
    "description": "Street art-inspired canvas with urban energy and raw visual movement.",
    "image": "https://picsum.photos/id/95/800/1000",
    "likes": 2639,
    "views": 61494,
    "year": 2022,
    "style": "Landscape Painting"
  },
  {
    "id": 96,
    "title": "Abstract Wave",
    "artist": "Noah Garcia",
    "category": "Trending Arts",
    "description": "Landscape painting capturing the serene beauty of the natural world.",
    "image": "https://picsum.photos/id/96/800/1000",
    "likes": 5467,
    "views": 6150,
    "year": 2022,
    "style": "Watercolor"
  },
  {
    "id": 97,
    "title": "Sunset Gust",
    "artist": "Liam Johnson",
    "category": "Trending Arts",
    "description": "Creative illustration with a modern, editorial approach to visual storytelling.",
    "image": "https://picsum.photos/id/97/800/1000",
    "likes": 7992,
    "views": 49778,
    "year": 2025,
    "style": "Creative Illustration"
  },
  {
    "id": 98,
    "title": "Dense Stillness",
    "artist": "Emily Johnson",
    "category": "Trending Arts",
    "description": "Contemporary art piece blurring the lines between media and perception.",
    "image": "https://picsum.photos/id/98/800/1000",
    "likes": 6761,
    "views": 17621,
    "year": 2023,
    "style": "Street Art"
  },
  {
    "id": 99,
    "title": "Dynamic Calm",
    "artist": "Amelia Harris",
    "category": "Trending Arts",
    "description": "A stunning canvas artwork exploring form, color, and depth.",
    "image": "https://picsum.photos/id/99/800/1000",
    "likes": 9758,
    "views": 68915,
    "year": 2021,
    "style": "Contemporary Art"
  },
  {
    "id": 100,
    "title": "Modern Explosion",
    "artist": "Mei Chen",
    "category": "Trending Arts",
    "description": "Mixed media creation featuring layered textures and bold compositional choices.",
    "image": "https://picsum.photos/id/100/800/1000",
    "likes": 9956,
    "views": 91598,
    "year": 2021,
    "style": "Mixed Media"
  }
];
