export interface GalleryArtwork {
  id: number;
  title: string;
  artist: string;
  category: string;
  description: string;
  image: string;
  likes: number;
  views: number;
  year: number;
  style: string;
}

export const trendingArts: GalleryArtwork[] = [
  {
    "id": 1,
    "title": "Color Explosion",
    "artist": "Jacques Louis David",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-13139-001.jpg",
    "likes": 5041,
    "views": 40047,
    "year": 2024,
    "style": "Modern Painting"
  },
  {
    "id": 2,
    "title": "Modern Horizon",
    "artist": "Georges Seurat",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP375450_cropped.jpg",
    "likes": 6095,
    "views": 39649,
    "year": 2024,
    "style": "Abstract Painting"
  },
  {
    "id": 3,
    "title": "Urban Energy",
    "artist": "Sir Thomas Lawrence",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP169218.jpg",
    "likes": 8262,
    "views": 85076,
    "year": 2023,
    "style": "Oil Painting"
  },
  {
    "id": 4,
    "title": "Ocean Dreams",
    "artist": "Giovanni Bellini",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT7219.jpg",
    "likes": 6438,
    "views": 52110,
    "year": 2025,
    "style": "Watercolor"
  },
  {
    "id": 5,
    "title": "Abstract Nature",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-14936-047.jpg",
    "likes": 4604,
    "views": 42628,
    "year": 2025,
    "style": "Contemporary Art"
  },
  {
    "id": 6,
    "title": "Vibrant Canvas",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT2157.jpg",
    "likes": 6713,
    "views": 23271,
    "year": 2025,
    "style": "Mixed Media"
  },
  {
    "id": 7,
    "title": "Dynamic Vision",
    "artist": "Honoré Daumier",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-22554-001.jpg",
    "likes": 8114,
    "views": 95384,
    "year": 2021,
    "style": "Canvas Art"
  },
  {
    "id": 8,
    "title": "Mystic Wave",
    "artist": "Gustave Courbet",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-25035-001.jpg",
    "likes": 5724,
    "views": 30206,
    "year": 2020,
    "style": "Impressionist"
  },
  {
    "id": 9,
    "title": "Silent Journey",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-20100-001.jpg",
    "likes": 4681,
    "views": 78365,
    "year": 2024,
    "style": "Landscape Painting"
  },
  {
    "id": 10,
    "title": "Golden Echo",
    "artist": "French Painter",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP345572.jpg",
    "likes": 8592,
    "views": 84472,
    "year": 2024,
    "style": "Expressionist"
  },
  {
    "id": 11,
    "title": "Wild Symphony",
    "artist": "Jacopo Palma the Younger",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/ep57.170.bw.R.jpg",
    "likes": 1974,
    "views": 71678,
    "year": 2024,
    "style": "Modern Painting"
  },
  {
    "id": 12,
    "title": "Deep Motion",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP317780.jpg",
    "likes": 8354,
    "views": 91211,
    "year": 2020,
    "style": "Abstract Painting"
  },
  {
    "id": 13,
    "title": "Fluid Bloom",
    "artist": "Spanish (Aragonese) Painter",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT8870.jpg",
    "likes": 1779,
    "views": 74500,
    "year": 2024,
    "style": "Oil Painting"
  },
  {
    "id": 14,
    "title": "Bold Surge",
    "artist": "Sir Henry Raeburn",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP169400.jpg",
    "likes": 3829,
    "views": 18681,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 15,
    "title": "Eternal Storm",
    "artist": "Jean Auguste Dominique Ingres",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT403.jpg",
    "likes": 9583,
    "views": 93006,
    "year": 2025,
    "style": "Contemporary Art"
  },
  {
    "id": 16,
    "title": "Color Wave",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1977.jpg",
    "likes": 2616,
    "views": 66202,
    "year": 2025,
    "style": "Mixed Media"
  },
  {
    "id": 17,
    "title": "Modern Dreams",
    "artist": "Hans Memling",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-42409-001.jpg",
    "likes": 1922,
    "views": 39695,
    "year": 2025,
    "style": "Canvas Art"
  },
  {
    "id": 18,
    "title": "Urban Canvas",
    "artist": "Johannes Abrahamsz Beerstraten",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP143154.jpg",
    "likes": 7518,
    "views": 30241,
    "year": 2021,
    "style": "Impressionist"
  },
  {
    "id": 19,
    "title": "Ocean Horizon",
    "artist": "Henri Fantin-Latour",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1576.jpg",
    "likes": 6627,
    "views": 73618,
    "year": 2025,
    "style": "Landscape Painting"
  },
  {
    "id": 20,
    "title": "Abstract Energy",
    "artist": "Andrea Mantegna",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP213831.jpg",
    "likes": 6243,
    "views": 57770,
    "year": 2024,
    "style": "Expressionist"
  },
  {
    "id": 21,
    "title": "Vibrant Journey",
    "artist": "Catena (Vincenzo di Biagio)",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT7237.jpg",
    "likes": 5541,
    "views": 48837,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 22,
    "title": "Dynamic Echo",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-14936-049.jpg",
    "likes": 3916,
    "views": 20317,
    "year": 2025,
    "style": "Abstract Painting"
  },
  {
    "id": 23,
    "title": "Mystic Motion",
    "artist": "Sir Thomas Lawrence",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP162148.jpg",
    "likes": 7366,
    "views": 87569,
    "year": 2024,
    "style": "Oil Painting"
  },
  {
    "id": 24,
    "title": "Silent Bloom",
    "artist": "Frans Hals",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP145901.jpg",
    "likes": 6390,
    "views": 13034,
    "year": 2025,
    "style": "Watercolor"
  },
  {
    "id": 25,
    "title": "Golden Storm",
    "artist": "Vincent van Gogh",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP130999.jpg",
    "likes": 3926,
    "views": 8683,
    "year": 2020,
    "style": "Contemporary Art"
  },
  {
    "id": 26,
    "title": "Wild Wave",
    "artist": "Nicola di Maestro Antonio d'Ancona",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP201412.jpg",
    "likes": 3602,
    "views": 42498,
    "year": 2020,
    "style": "Mixed Media"
  },
  {
    "id": 27,
    "title": "Deep Canvas",
    "artist": "Petrus Christus",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1479.jpg",
    "likes": 1303,
    "views": 60291,
    "year": 2023,
    "style": "Canvas Art"
  },
  {
    "id": 28,
    "title": "Fluid Horizon",
    "artist": "Rogier van der Weyden",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP347297.jpg",
    "likes": 4381,
    "views": 66767,
    "year": 2025,
    "style": "Impressionist"
  },
  {
    "id": 29,
    "title": "Bold Dreams",
    "artist": "François Boucher",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP337751.jpg",
    "likes": 1754,
    "views": 11408,
    "year": 2025,
    "style": "Landscape Painting"
  },
  {
    "id": 30,
    "title": "Eternal Energy",
    "artist": "Northern French Painter",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT7226.jpg",
    "likes": 1588,
    "views": 38808,
    "year": 2022,
    "style": "Expressionist"
  },
  {
    "id": 31,
    "title": "Color Symphony",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT47.jpg",
    "likes": 7363,
    "views": 54265,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 32,
    "title": "Modern Nature",
    "artist": "Ivan Konstantinovich Aivazovsky (Hovhannes Aivazian)",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-27364-001.jpg",
    "likes": 3848,
    "views": 61888,
    "year": 2020,
    "style": "Abstract Painting"
  },
  {
    "id": 33,
    "title": "Urban Vision",
    "artist": "North Netherlandish (Bruges) Painter",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-20751-001.jpg",
    "likes": 5092,
    "views": 16994,
    "year": 2021,
    "style": "Oil Painting"
  },
  {
    "id": 34,
    "title": "Ocean Echo",
    "artist": "Master of the Dinteville Allegory",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1462.jpg",
    "likes": 7405,
    "views": 11961,
    "year": 2021,
    "style": "Watercolor"
  },
  {
    "id": 35,
    "title": "Abstract Canvas",
    "artist": "Lucas Cranach the Elder",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP280784.jpg",
    "likes": 1027,
    "views": 16972,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 36,
    "title": "Vibrant Motion",
    "artist": "Guido Reni",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1138.jpg",
    "likes": 2732,
    "views": 71579,
    "year": 2022,
    "style": "Mixed Media"
  },
  {
    "id": 37,
    "title": "Dynamic Storm",
    "artist": "Joos van Cleve",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-25890-001.jpg",
    "likes": 2737,
    "views": 37984,
    "year": 2021,
    "style": "Canvas Art"
  },
  {
    "id": 38,
    "title": "Mystic Dreams",
    "artist": "Master of the Saint Barbara Legend",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/SF DT1049.jpg",
    "likes": 6719,
    "views": 93604,
    "year": 2022,
    "style": "Impressionist"
  },
  {
    "id": 39,
    "title": "Silent Wave",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP320128.jpg",
    "likes": 6203,
    "views": 26955,
    "year": 2023,
    "style": "Landscape Painting"
  },
  {
    "id": 40,
    "title": "Golden Energy",
    "artist": "Léon Bonnat",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT234058.jpg",
    "likes": 3633,
    "views": 74080,
    "year": 2020,
    "style": "Expressionist"
  },
  {
    "id": 41,
    "title": "Wild Journey",
    "artist": "Master of the Virgin among Virgins",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-23271-001.jpg",
    "likes": 8191,
    "views": 26600,
    "year": 2024,
    "style": "Modern Painting"
  },
  {
    "id": 42,
    "title": "Deep Bloom",
    "artist": "Netherlandish (Brussels) Painter",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT5754.jpg",
    "likes": 1835,
    "views": 17236,
    "year": 2021,
    "style": "Abstract Painting"
  },
  {
    "id": 43,
    "title": "Fluid Vision",
    "artist": "Edgar Degas",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1912.jpg",
    "likes": 7279,
    "views": 67568,
    "year": 2021,
    "style": "Oil Painting"
  },
  {
    "id": 44,
    "title": "Bold Nature",
    "artist": "Jan van Eyck",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/LC-33_92ab-Primary_Temp.jpg",
    "likes": 7846,
    "views": 2180,
    "year": 2022,
    "style": "Watercolor"
  },
  {
    "id": 45,
    "title": "Eternal Canvas",
    "artist": "Duccio di Buoninsegna",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP142735.jpg",
    "likes": 8258,
    "views": 49521,
    "year": 2025,
    "style": "Contemporary Art"
  },
  {
    "id": 46,
    "title": "Color Horizon",
    "artist": "Biagio d'Antonio",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP164778.jpg",
    "likes": 5720,
    "views": 38954,
    "year": 2020,
    "style": "Mixed Media"
  },
  {
    "id": 47,
    "title": "Modern Motion",
    "artist": "Anthony van Dyck",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-25646-001.jpg",
    "likes": 9242,
    "views": 34796,
    "year": 2020,
    "style": "Canvas Art"
  },
  {
    "id": 48,
    "title": "Urban Storm",
    "artist": "Domenico Fetti",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT6682.jpg",
    "likes": 7177,
    "views": 30183,
    "year": 2022,
    "style": "Impressionist"
  },
  {
    "id": 49,
    "title": "Ocean Journey",
    "artist": "Ivan Konstantinovich Aivazovsky (Hovhannes Aivazian)",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-23290-001.jpg",
    "likes": 4706,
    "views": 40105,
    "year": 2021,
    "style": "Landscape Painting"
  },
  {
    "id": 50,
    "title": "Abstract Wave",
    "artist": "Hans Holbein the Younger",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP280366.jpg",
    "likes": 3161,
    "views": 2908,
    "year": 2024,
    "style": "Expressionist"
  },
  {
    "id": 51,
    "title": "Vibrant Bloom",
    "artist": "Lorenzo Lotto",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-17152-001.jpg",
    "likes": 5889,
    "views": 94106,
    "year": 2025,
    "style": "Modern Painting"
  },
  {
    "id": 52,
    "title": "Dynamic Canvas",
    "artist": "Théodore Rousseau",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-31520-001.jpg",
    "likes": 8613,
    "views": 52926,
    "year": 2021,
    "style": "Abstract Painting"
  },
  {
    "id": 53,
    "title": "Mystic Vision",
    "artist": "El Greco (Domenikos Theotokopoulos)",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-17641-001.jpg",
    "likes": 1711,
    "views": 78951,
    "year": 2021,
    "style": "Oil Painting"
  },
  {
    "id": 54,
    "title": "Silent Energy",
    "artist": "Master of the View of Saint Gudula",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP282434.jpg",
    "likes": 9481,
    "views": 13962,
    "year": 2025,
    "style": "Watercolor"
  },
  {
    "id": 55,
    "title": "Golden Nature",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1939.jpg",
    "likes": 3905,
    "views": 70881,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 56,
    "title": "Wild Dreams",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-20099-001.jpg",
    "likes": 9844,
    "views": 84017,
    "year": 2023,
    "style": "Mixed Media"
  },
  {
    "id": 57,
    "title": "Deep Motion",
    "artist": "Bernard van Orley",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP136254.jpg",
    "likes": 2976,
    "views": 37092,
    "year": 2020,
    "style": "Canvas Art"
  },
  {
    "id": 58,
    "title": "Fluid Symphony",
    "artist": "Albrecht Dürer",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-38479-001.jpg",
    "likes": 7271,
    "views": 48240,
    "year": 2023,
    "style": "Impressionist"
  },
  {
    "id": 59,
    "title": "Bold Echo",
    "artist": "Goya (Francisco de Goya y Lucientes)",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-28009-001.jpg",
    "likes": 1660,
    "views": 43119,
    "year": 2025,
    "style": "Landscape Painting"
  },
  {
    "id": 60,
    "title": "Eternal Wave",
    "artist": "John Hoppner",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP162138.jpg",
    "likes": 1849,
    "views": 19367,
    "year": 2023,
    "style": "Expressionist"
  },
  {
    "id": 61,
    "title": "Color Canvas",
    "artist": "Joachim Patinir",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT5549.jpg",
    "likes": 8220,
    "views": 15333,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 62,
    "title": "Modern Energy",
    "artist": "Joseph Mallord William Turner",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-13360-001.jpg",
    "likes": 1315,
    "views": 30238,
    "year": 2021,
    "style": "Abstract Painting"
  },
  {
    "id": 63,
    "title": "Urban Bloom",
    "artist": "Théodore Chassériau",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-18259-001.jpg",
    "likes": 1649,
    "views": 55988,
    "year": 2024,
    "style": "Oil Painting"
  },
  {
    "id": 64,
    "title": "Ocean Vision",
    "artist": "Fra Carnevale (Bartolomeo di Giovanni Corradini)",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP109484.jpg",
    "likes": 5014,
    "views": 90329,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 65,
    "title": "Abstract Storm",
    "artist": "Jan van Eyck",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1484.jpg",
    "likes": 4582,
    "views": 52919,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 66,
    "title": "Vibrant Journey",
    "artist": "Rosa Bonheur",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-23550-001.jpg",
    "likes": 1155,
    "views": 5106,
    "year": 2021,
    "style": "Mixed Media"
  },
  {
    "id": 67,
    "title": "Dynamic Nature",
    "artist": "Luis de Morales",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP370255.jpg",
    "likes": 9120,
    "views": 54288,
    "year": 2021,
    "style": "Canvas Art"
  },
  {
    "id": 68,
    "title": "Mystic Horizon",
    "artist": "Joos van Cleve",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-26502-001.jpg",
    "likes": 8079,
    "views": 42229,
    "year": 2021,
    "style": "Impressionist"
  },
  {
    "id": 69,
    "title": "Silent Canvas",
    "artist": "Joos van Wassenhove",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-16339-001.jpg",
    "likes": 305,
    "views": 43248,
    "year": 2021,
    "style": "Landscape Painting"
  },
  {
    "id": 70,
    "title": "Golden Dreams",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1492.jpg",
    "likes": 8395,
    "views": 89057,
    "year": 2023,
    "style": "Expressionist"
  },
  {
    "id": 71,
    "title": "Wild Echo",
    "artist": "Claude Lorrain (Claude Gellée)",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-27909-001.jpg",
    "likes": 8731,
    "views": 72954,
    "year": 2025,
    "style": "Modern Painting"
  },
  {
    "id": 72,
    "title": "Deep Energy",
    "artist": "Camille Pissarro",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1863.jpg",
    "likes": 1204,
    "views": 78567,
    "year": 2025,
    "style": "Abstract Painting"
  },
  {
    "id": 73,
    "title": "Fluid Storm",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1944.jpg",
    "likes": 9631,
    "views": 54570,
    "year": 2022,
    "style": "Oil Painting"
  },
  {
    "id": 74,
    "title": "Bold Wave",
    "artist": "Follower of Rogier van der Weyden (Master of the Saint Ursula Legend Group, Neth",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-20393-001.jpg",
    "likes": 5180,
    "views": 9728,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 75,
    "title": "Eternal Bloom",
    "artist": "Gerard David",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-26498-001.jpg",
    "likes": 9508,
    "views": 18936,
    "year": 2022,
    "style": "Contemporary Art"
  },
  {
    "id": 76,
    "title": "Color Vision",
    "artist": "Petrus Christus",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT229079.jpg",
    "likes": 2772,
    "views": 39872,
    "year": 2021,
    "style": "Mixed Media"
  },
  {
    "id": 77,
    "title": "Modern Canvas",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP130322.jpg",
    "likes": 3893,
    "views": 36547,
    "year": 2025,
    "style": "Canvas Art"
  },
  {
    "id": 78,
    "title": "Urban Echo",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP231550.jpg",
    "likes": 1562,
    "views": 15940,
    "year": 2021,
    "style": "Impressionist"
  },
  {
    "id": 79,
    "title": "Ocean Energy",
    "artist": "Paul Gauguin",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1025.jpg",
    "likes": 4891,
    "views": 12647,
    "year": 2024,
    "style": "Landscape Painting"
  },
  {
    "id": 80,
    "title": "Abstract Bloom",
    "artist": "Jean Auguste Dominique Ingres",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1926.jpg",
    "likes": 851,
    "views": 74134,
    "year": 2021,
    "style": "Expressionist"
  },
  {
    "id": 81,
    "title": "Vibrant Storm",
    "artist": "Jan Massys",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-13614-001.jpg",
    "likes": 6261,
    "views": 97883,
    "year": 2020,
    "style": "Modern Painting"
  },
  {
    "id": 82,
    "title": "Dynamic Dreams",
    "artist": "Jacopo di Arcangelo (called Jacopo del Sellaio)",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP164779.jpg",
    "likes": 5693,
    "views": 26417,
    "year": 2022,
    "style": "Abstract Painting"
  },
  {
    "id": 83,
    "title": "Mystic Wave",
    "artist": "Joos van Cleve",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT7241.jpg",
    "likes": 5941,
    "views": 77758,
    "year": 2025,
    "style": "Oil Painting"
  },
  {
    "id": 84,
    "title": "Silent Nature",
    "artist": "Edouard Manet",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-25465-001.jpg",
    "likes": 8328,
    "views": 71034,
    "year": 2020,
    "style": "Watercolor"
  },
  {
    "id": 85,
    "title": "Golden Journey",
    "artist": "Giovanni di Tano Fei",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP293271.jpg",
    "likes": 4639,
    "views": 26695,
    "year": 2021,
    "style": "Contemporary Art"
  },
  {
    "id": 86,
    "title": "Wild Canvas",
    "artist": "Sebastiano Ricci",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT9354.jpg",
    "likes": 8625,
    "views": 37660,
    "year": 2024,
    "style": "Mixed Media"
  },
  {
    "id": 87,
    "title": "Deep Vision",
    "artist": "Johann Liss",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-19542-001.jpg",
    "likes": 6196,
    "views": 4135,
    "year": 2020,
    "style": "Canvas Art"
  },
  {
    "id": 88,
    "title": "Fluid Echo",
    "artist": "Velázquez",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP276131.jpg",
    "likes": 529,
    "views": 3276,
    "year": 2022,
    "style": "Impressionist"
  },
  {
    "id": 89,
    "title": "Bold Storm",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-33710-001.jpg",
    "likes": 4026,
    "views": 86976,
    "year": 2020,
    "style": "Landscape Painting"
  },
  {
    "id": 90,
    "title": "Eternal Dreams",
    "artist": "Isidore Pils",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-14274-015.jpg",
    "likes": 5715,
    "views": 94977,
    "year": 2021,
    "style": "Expressionist"
  },
  {
    "id": 91,
    "title": "Color Energy",
    "artist": "Edgar Degas",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1911.jpg",
    "likes": 7004,
    "views": 87428,
    "year": 2022,
    "style": "Modern Painting"
  },
  {
    "id": 92,
    "title": "Modern Bloom",
    "artist": "Dieric Bouts",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-20589-001.jpg",
    "likes": 1038,
    "views": 96661,
    "year": 2025,
    "style": "Abstract Painting"
  },
  {
    "id": 93,
    "title": "Urban Vision",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/77J_045R2M.jpg",
    "likes": 8007,
    "views": 13385,
    "year": 2023,
    "style": "Oil Painting"
  },
  {
    "id": 94,
    "title": "Ocean Canvas",
    "artist": "Paul Cézanne",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT1408.jpg",
    "likes": 3742,
    "views": 34129,
    "year": 2022,
    "style": "Watercolor"
  },
  {
    "id": 95,
    "title": "Abstract Journey",
    "artist": "Antoine Watteau",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP120381.jpg",
    "likes": 6588,
    "views": 81835,
    "year": 2025,
    "style": "Contemporary Art"
  },
  {
    "id": 96,
    "title": "Vibrant Echo",
    "artist": "Jan Sanders van Hemessen",
    "category": "Trending Arts",
    "description": "A vibrant oil painting bursting with rich color and dynamic energy.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT201070.jpg",
    "likes": 9261,
    "views": 26110,
    "year": 2025,
    "style": "Mixed Media"
  },
  {
    "id": 97,
    "title": "Dynamic Horizon",
    "artist": "Adam August Müller",
    "category": "Trending Arts",
    "description": "Contemporary painting with masterful brushstrokes and expressive texture.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-15576-001.jpg",
    "likes": 5956,
    "views": 75552,
    "year": 2021,
    "style": "Canvas Art"
  },
  {
    "id": 98,
    "title": "Mystic Energy",
    "artist": "Jacques Louis David",
    "category": "Trending Arts",
    "description": "Watercolor artwork exploring the delicate interplay of light and shadow.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-19709-001.jpg",
    "likes": 5378,
    "views": 76982,
    "year": 2023,
    "style": "Impressionist"
  },
  {
    "id": 99,
    "title": "Silent Storm",
    "artist": "Master of the Saint Ursula Legend",
    "category": "Trending Arts",
    "description": "Abstract canvas with bold shapes and a harmonious color palette.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DT262309.jpg",
    "likes": 4532,
    "views": 17589,
    "year": 2024,
    "style": "Landscape Painting"
  },
  {
    "id": 100,
    "title": "Golden Wave",
    "artist": "Quinten Massys",
    "category": "Trending Arts",
    "description": "Stunning impressionist painting with masterful composition and visual depth.",
    "image": "https://images.metmuseum.org/CRDImages/ep/web-large/DP-26501-001.jpg",
    "likes": 9642,
    "views": 94243,
    "year": 2021,
    "style": "Expressionist"
  }
];
